### ISSUE TITLE
`TemplateDeployment` times out on destroy

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-azure#1001]
Related: https://github.com/pulumi/examples/issues/1138

This appears to be an upstream issue tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/14626
I was able to confirm that downgrading to `pulumi-azure` v4.29.0 does resolve the issue

**Comment by mikhailshilkov** [comment]
Closing as the upstream issue is closed
