### ISSUE TITLE
Python | Azure stack | Application Insights picks up changes when there's no actual change

### ISSUE THREAD

**Issue by venura9** [pulumi/pulumi-azure#1091]
![Screen Shot 2020-05-11 at 8 17 47 pm](https://user-images.githubusercontent.com/13330516/81551269-e569a300-93c4-11ea-9c07-bab36586fe28.png)

**Comment by mikhailshilkov** [comment]
I ran the repro today and got the following warning:

> azure:appservice/appService:AppService::todo-dev-webapp verification warning: The `azurerm_app_service` resource has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources. Whilst this resource will continue to be available in the 2.x and 3.x releases it is feature-frozen for compatibility purposes, will no longer receive any updates and will be removed in a future major release of the Azure Provider.

Since the resource is out of date and the issue is so old, I'll go ahead and close it.
