### ISSUE TITLE
Failure to Diff changes on Azure-CosmosDB

### ISSUE THREAD

**Issue by Guacam-Ole** [pulumi/pulumi-azure#1109]
We create Resouces in an Azure subscription. These Resources contain a CosmosDB - Database and the Resources required to get to that point.

While everything works without any issue, the second time ´pulumi up´ is called (without having made any changes to the code) the following error occurs directly at start:

> panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:dev::AzureDeploy::azure:cosmosdb/account:Account::dev-pulumi-cosmosdb-test
    goroutine 29 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/go/common/util/contract/failfast.go:23
   [...]

When renaming the CosmosDB-Account-Name everything works (old Resource gets deleted, new Resource gets created)

I do not have this issue on any other resource type (Storage, Resourcegroup and so on)

Code for CosmosAccount-Creation:
```
  private Az.CosmosDB.Account CreateCosmosAccount(ResourceGroup resourceGroup, string cosmosAccountName)
    {
        var cosmosAccount = new Az.CosmosDB.Account(cosmosAccountName, new Az.CosmosDB.AccountArgs
        {
            Name=CosmosAccountName,
            Location = resourceGroup.Location,
            ResourceGroupName = resourceGroup.Name,
            OfferType = "Standard",
            Kind = "MongoDB",
            EnableAutomaticFailover = true,
            Capabilities =
            {
                new Az.CosmosDB.Inputs.AccountCapabilityArgs
                {
                    Name = "EnableAggregationPipeline",
                },
                new Az.CosmosDB.Inputs.AccountCapabilityArgs
                {
                    Name = "mongoEnableDocLevelTTL",
                },
                new Az.CosmosDB.Inputs.AccountCapabilityArgs
                {
                    Name = "MongoDBv3.4",
                },
            },
            ConsistencyPolicy = new Az.CosmosDB.Inputs.AccountConsistencyPolicyArgs
            {
                ConsistencyLevel = "BoundedStaleness",
                MaxIntervalInSeconds = 10,
                MaxStalenessPrefix = 200
            },
            GeoLocations =
            {
                new Az.CosmosDB.Inputs.AccountGeoLocationArgs
                {
                    Location = resourceGroup.Location,
                    FailoverPriority = 0
                }
            }
        });
        return cosmosAccount;
    }
```
If I remove the "Name="-Property the problem still exists (just with a randomized accountname instead)

## Expected Behavior
Diff on CosmosDb-Account gets retrieved and changes are shown 

## Current Behavior
Exception when trying to retrieve the CosmosDB-Account configuration from Azure

## Steps to Reproduce
1. Write pulumi-code for CosmosDB-Account-creation
2. Run `pulumi up`
3. Select <yes> to deploy the resource
4. Run `pulumi up` again without changing the code
5. Exception occurs

## Context (Environment)
C# .net Core 3.1 - project (created by pulumi new `azure-csharp`)

**Comment by mikhailshilkov** [comment]
I tried this today with the latest version and couldn't repro the issue. I had to add one more capability to deploy a cosmos account, but otherwise my code was exactly the same. A subsequence `pulumi up` caused no diffs.

```
new Az.CosmosDB.Inputs.AccountCapabilityArgs
{
    Name = "EnableMongo",
},
```
