### ISSUE TITLE
azure:postgresql:FlexibleServer polling after Create InternalServerError

### ISSUE THREAD

**Issue by rgl** [pulumi/pulumi-azure#1123]
### What happened?

When trying to create a Azure Database for PostgreSQL Flexible Server instance pulumi fails with a InternalServerError.

### Steps to reproduce

Create a PostgreSQL Flexible Server instance as https://github.com/rgl/pulumi-typescript-azure-classic-postgres/blob/main/index.ts#L19-L32

### Expected Behavior

It should have been able to create the instance.

### Actual Behavior

```
PS C:\rgl\pulumi-typescript-azure-classic-postgres> pulumi up
Previewing update (dev):
     Type                                Name         Plan
 +   pulumi:pulumi:Stack                 example-dev  create
 +   ├─ azure:core:ResourceGroup         example      create
 +   ├─ random:index:RandomPassword      postgres     create
 +   └─ azure:postgresql:FlexibleServer  postgres     create

Outputs:
    fqdn    : "postgresc4408c8.postgres.database.azure.com"
    password: output<string>

Resources:
    + 4 to create

Do you want to perform this update? yes
Updating (dev):
     Type                                Name         Status                  Info
 +   pulumi:pulumi:Stack                 example-dev  **creating failed**     1 error
 +   ├─ azure:core:ResourceGroup         example      created
 +   ├─ random:index:RandomPassword      postgres     created
 +   └─ azure:postgresql:FlexibleServer  postgres     **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (example-dev):
    error: update failed

  azure:postgresql:FlexibleServer (postgres):
    error: 1 error occurred:
        * creating Flexible Server (Subscription: "a4049229-13e3-4c3f-b225-54257fa6eee3"
    Resource Group Name: "example8530bf93"
    Server Name: "postgresa75b40e"): polling after Create: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '2b0e5781-4d51-45ed-914d-32891e6053bb'"

Resources:
    + 3 created

Duration: 2m18s
```

### Output of `pulumi about`

```
PS C:\rgl\pulumi-typescript-azure-classic-postgres> pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
azure   5.15.0
nodejs  unknown
random  4.8.1

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v16.17.0'

Current Stack: dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::example::pulumi:pulumi:Stack::example-dev
pulumi:providers:azure                      urn:pulumi:dev::example::pulumi:providers:azure::default_5_15_0
pulumi:providers:random                     urn:pulumi:dev::example::pulumi:providers:random::default_4_8_1
random:index/randomPassword:RandomPassword  urn:pulumi:dev::example::random:index/randomPassword:RandomPassword::postgres
azure:core/resourceGroup:ResourceGroup      urn:pulumi:dev::example::azure:core/resourceGroup:ResourceGroup::example


Found no pending operations associated with dev
```

### Additional context

I'm trying to port my working terraform example at https://github.com/rgl/terraform-azure-postgres to pulumi, but I'm stuck at the problem described in this issue, and would appreciate any input that you can give.

I'm also stuck trying out the azure-native provider at https://github.com/pulumi/pulumi-azure-native/issues/1921, but it seems to be for another reason.

Also, do you known how do I set the fqdn of a PostgreSQL instance?

Thank you!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
It looks like this might be the same issue [reported upstream](https://github.com/hashicorp/terraform-provider-azurerm/issues/18029)

> Also, do you known how do I set the fqdn of a PostgreSQL instance?

The `fqdn` appears to be an output-only property of `FlexibleServer`.

**Comment by rgl** [comment]
@lblackstone, sorry, I meant to say get. there is no way to get the fqdn, as that property does not exist in the postgres object. it exists in the azure classic provider, but not in this native provider.

**Comment by lblackstone** [comment]
> it exists in the azure classic provider, but not in this native provider.

I'm not sure I understand. It looks like the example program you're running is using the classic provider (and this issue is filed in the classic provider repo), so I'm not sure how it relates to the native provider?

**Comment by rgl** [comment]
oh, I swapped "classic" with "native" in the phrase I wrote before.

I mean, there is no property in this classic provider that exposes the FQDN as an output variable (but it exists in the native provider as `fullyQualifiedDomainName`).

**Comment by lblackstone** [comment]
It looks like it's called [fqdn](https://www.pulumi.com/registry/packages/azure/api-docs/postgresql/flexibleserver/#fqdn_nodejs) in the classic provider.

**Comment by rgl** [comment]
Oh, somehow I missed that property! Its now working nicely. Thank You!
