### ISSUE TITLE
Azure Container App - Ignore template container image changes

### ISSUE THREAD

**Issue by alhardy** [pulumi/pulumi-azure#1143]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am creating a new [ContainerApp](https://www.pulumi.com/registry/packages/azure-native/api-docs/app/containerapp/) setting the Template > Container > ContainerArgs > ImageName to a hello world image on the initial creation. After deploying my application via CICD with the actual container image for the application via `az containerapp update`, I would still like to manage other template setting via Pulumi. However this results in the image being overridden. How can I ignore image changes in subsequence changes to my infrastructure code?

**Comment by danielrbradley** [comment]
Hi @alhardy I think the feature you're looking for is the [IgnoreChanges](https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/) resource option.

**Comment by alhardy** [comment]
I have applied ignore changes however the latest image name still gets overridden, my diff only shows me the changes however the whole container template seems to get replaced. example:

```
var conainterApp = new ContainerApp(containerAppName, new ContainerAppArgs
    {
        ResourceGroupName = resourceGroup.Name,
        ContainerAppName = containerAppName,
        ManagedEnvironmentId = containerAppsEnvironment.Id,
        Configuration = new ConfigurationArgs
        {
            Dapr = new DaprArgs
            {
                Enabled = true,
                AppId = containerAppImageName
            },
            Ingress = new IngressArgs
            {
                External = true,
                TargetPort = 80
            },
            Registries =
            {
                new RegistryCredentialsArgs
                {
                    Server = platformGlobalStackOutput.PlaformGlobalContainerRegistryLoginServer,
                    Username = platformGlobalStackOutput.PlatformGlobalContainerRegistryUsername,
                    PasswordSecretRef = "acrpassword"
                }
            },
            Secrets =
            {
                new SecretArgs
                {
                    Name = "acrpassword",
                    Value = platformGlobalStackOutput.PlatformGlobalContainerRegistryUserPassword
                },
                new SecretArgs
                {
                    Name = "appinsights-key",
                    Value = appInsights.InstrumentationKey
                }
            }
        },
        Template = new TemplateArgs
        {
            Containers =
            {
                new ContainerArgs
                {
                    Name = containerAppImageName,
                    Image = containerAppImage.Name,
                    Probes = new[]
                    {
                        new ContainerAppProbeArgs
                        {
                            HttpGet = new ContainerAppProbeHttpGetArgs
                            {
                                Path = "/hc/liveness",
                                Port = 80
                            },
                            InitialDelaySeconds = 3,
                            PeriodSeconds = 5,
                            Type = Type.Liveness
                        }
                    }
                }
            }
        },
        Identity = new ManagedServiceIdentityArgs
        {
            Type = ManagedServiceIdentityType.SystemAssigned
        },
        Tags = commonTags
    }, new CustomResourceOptions { IgnoreChanges = new List<string> { "template.containers[0].image" } });
```

When I can for example "PeriodSeconds" to another value the image name in the state overrides the last image deployed

**Comment by alhardy** [comment]
Is there a way to pull the image name from the latest revision and set this if it exists to avoid the override or is there another way around it?

**Comment by alhardy** [comment]
Thanks @danielrbradley.

I could perform the update of the image via pulumi in my CD pipeline. Is it possible to pass arguments to pulumi up? I can't find anything in the docs. If so I can build/test the image then pass the image name to pulumi cli
