### ISSUE TITLE
Add explicit top level type for tag structure

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-azure#115]
Similar to how the AWS provider (now) has `aws.Tags` defined as a dictionary object, we should add an explicit type to the Azure provider to avoid having to use `any` in various places.

**Comment by mikhailshilkov** [comment]
@jen20 Could you elaborate a bit? As of now, the tag usage from [this AWS example](https://github.com/pulumi/examples/blob/b01603bc999b56547addb3b39a28d6c631054b9b/aws-ts-stackreference/team/index.ts#L33) seems to apply to Azure. This code

``` ts
const tags = {
    createdBy: "Mikhail",
    project: "Play",
    "Managed By": "Pulumi",
};

const storageAccount = new azure.storage.Account("storage", {
    resourceGroupName: resourceGroup.name,
    accountReplicationType: "LRS",
    accountTier: "Standard",
    accountKind: "StorageV2",
    tags,
});
```

seems to work just fine.

I do see the [aws.Tags](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/tags.ts#L19) type that you mention but I fail to see any usage anywhere.

What's missing on both Azure and AWS sides?

**Comment by jen20** [comment]
Actually this can be closed, it turns out the `aws.Tags` type was a bad idea anyway since it doesn’t allow distinguishing between inputs and outputs - something that would need addressing in the code generator. In practice just using regular objects has not been a problem. Thanks for following up @mikhailshilkov!
