### ISSUE TITLE
Allow log destination options on azure container apps environment

### ISSUE THREAD

**Issue by alhardy** [pulumi/pulumi-azure#1170]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The only option on the log destination of an Azure Container App Managed Environment is "log-analytics", other supported values are "none" and "azure-monitor"

```
var environment = new ManagedEnvironment(name, new ManagedEnvironmentArgs
        {
            EnvironmentName = name,
            ResourceGroupName = args.ResourceGroup.Name,
            Location = args.ResourceGroup.Location,
            AppLogsConfiguration = new AppLogsConfigurationArgs
            {
                Destination = "log-analytics", // none, azure-monitor, log-analytics
            }
        });
```

### Affected area/feature

Unable to create an azure container apps environment with desired log destinations

**Comment by danielrbradley** [comment]
The SDK modells this property as a string ([source](https://github.com/pulumi/pulumi-azure-native/blob/6bf7a168899cdc1916a78a279dbfb4ce1807c2ba/sdk/nodejs/types/app/input.ts#L44)). A couple of questions to help us understand the specific resource details:

- What are you seeing that indicates other values won't work?
- Where are you seeing that other values should be supported?
