### ISSUE TITLE
GetZoneResult doesn't contain the 'name' property

### ISSUE THREAD

**Issue by mpp-oliverh** [pulumi/pulumi-azure#120]
I'm trying to add records to an existing DNS zone but I have to specify the zone name twice - once to retrieve it and again to create the record.

GetZoneArgs requires name and resourceGroupName
GetZoneResult only has resourceGroupName.

ARecordArgs requires zoneName and resourceGroupName.

**Comment by lukehoban** [comment]
Was you expectation that the same name you passed as input to `GetDnsZone` would also be available on the output of that function?

Note that this is ultimately based on the Azure Terraform provider API at https://www.terraform.io/docs/providers/azurerm/d/dns_zone.html.

**Comment by mpp-oliverh** [comment]
Yeah just that.

I guess it's an upstream suggestion but would still be handy.

**Comment by lukehoban** [comment]
Yeah - that sounds right.  Looks like we only project `Computed` properties today: 

https://github.com/pulumi/pulumi-terraform/blob/de82cd6f46d00d799a7a9e9268e3c8654fa14569/pkg/tfgen/generate.go#L733-L737

Interestingly - the code in `tfbridge` looks like perhaps it does pass the values of these back at runtime, but just the generated TypeScrip type doesn't include them?  I have not verified that yet though.

**Comment by oliverholliday** [comment]
Another one is `core.getResourceGroup(): GetResourceGroupResult` - the lack of `name` property on the return value makes it a bit of a pain to use. Using `new core.ResourceGroup` returns an object that has one.
