### ISSUE TITLE
Azure Function App v4 - no support to specify bundle version

### ISSUE THREAD

**Issue by imbelchev** [pulumi/pulumi-azure#1201]
https://github.com/pulumi/pulumi-azure/blob/151eba6e19cc41e70cbc5ffb1817cb777649ead9/sdk/nodejs/appservice/zMixins.ts#L397

With Azure Function App version `~4` the extension bundle version needs to be updated accordingly. Currently, no support to specify the extension bundle version.

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles 

Maybe I am missing how to configure it?

**Comment by thomas11** [comment]
Hi @imbelchev, thanks for raising this. It doesn't seem that it can be configured currently.

I'm not a Functions expert. Would it be enough to change the version range to `[1.*, 4.*]` or similar? Or do different users need different ranges?

**Comment by imbelchev** [comment]
Hi @thomas11,

Thanks for the fast replay.

I am not really a big expert on Azure Functions as well but, from how I understand things - if `[1.*, 4.*]` it should automatically pick up the correct version.

Supported major versions of Azure Functions:
* Functions v1 is still in support.
* Functions v2 is no longer supported.
* Functions v3 end of support is 13-Dec-2022, so probably soon will not be supported.
* Functions v4 is the recommended one

**Comment by imbelchev** [comment]
So I have tested this. There is a mapping `runtime version : extension bundle version` provided by Microsoft which needs to be strictly followed. It's from the same link posted in the issue initially - [Register Azure Functions binding extensions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles)

![image](https://user-images.githubusercontent.com/61695701/215868105-a5502807-7fb1-447e-80c3-17e17018f0a8.png)

**Comment by imbelchev** [comment]
@thomas11 ,

Are these changes enough to accept the PR and release a new version?
https://github.com/pulumi/pulumi-azure/pull/1202

**Comment by thomas11** [comment]
> @thomas11 , @mikhailshilkov , As the contribution was accepted and PR merged, do you have any timeline for when this change might get to an actual public release?

@imbelchev  It should be out by the end of the week unless something unexpected happens.

**Comment by imbelchev** [comment]
@thomas11 , awesome ❤️ 

Thank you!

**Comment by danielrbradley** [comment]
Fixed by https://github.com/pulumi/pulumi-azure/pull/1202
