### ISSUE TITLE
Azure role assignment name needs to be GUID

### ISSUE THREAD

**Issue by carterwilliamson** [pulumi/pulumi-azure#121]
When trying to assign a role to a service principal, the name needs to be a GUID.

The following code -
```
 let roleAssignment = new azure.role.assignment("ra", {
      principalId: servicePrincipal.id,
      roleDefinitionName: "Contributor",
      scope: `/subscriptions/${azure.config.subscriptionId}`
})
```

Will return a 400 error from azure saying that the name must be a valid GUID.

I tested with the `uuid` package and it worked, however this will trigger a change every time `pulumi up` is ran.

```
import * as uuid from "uuid"
let role = new azure.role.assignment("ra", {
     name: uuid.v4(),
     principalId: _sp.id,
     roleDefinitionName: "Contributor",
     scope: `/subscriptions/${azure.config.subscriptionId}`
})
```

**Comment by lukehoban** [comment]
Looks like the underlying provider was already auto-UUID-ing these name properties - but the Pulumi provider was overwriting that with it's own default.  #126 is a fix that would avoid doing that.

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/pulumi-azure/pull/127.

**Comment by SoranaBaciu** [comment]
how did you fix the` Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."` ?
