### ISSUE TITLE
FunctionApp too strict about version

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#122]
I'm trying to set Function App version to ~2:

```
const v2js = new azure.appservice.FunctionApp(`${name}-v1js`, {
    ...resourceGroupArgs,

    appServicePlanId: appServicePlan.id,
    storageConnectionString: storageAccount.primaryConnectionString,

    appSettings: {
        "WEBSITE_RUN_FROM_ZIP": codeBlobUrl
    },

    version: "~2"
});
```

but I get an error back:

```
error: azure:appservice/functionApp:FunctionApp resource '...' has a problem: 
expected version to be one of [~1 beta], got ~2
```

`~2` is a valid version, see [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#changing-version-of-apps-in-azure). 

Moreover, I should be able to pin my app to a specific version like `2.0.11961-alpha`.

**Comment by CyrusNajmabadi** [comment]
This is actually terraform doing the validation.  However, 3 weeks ago, they removed this validation: https://github.com/terraform-providers/terraform-provider-azurerm/pull/1872

I will see about getting us moved to a later version of terraform if possible!

**Comment by CyrusNajmabadi** [comment]
@pgavlin Is working on getting us up to date with the terraform.  That work is being tracked with https://github.com/pulumi/home/issues/265.  Once that goes through, you should be unblocked here!

Note: in the meantime, can you just set 'beta' as as your version?  IIRC, you will also likely have to set an appropriate the WEBSITE_NODE_DEFAULT_VERSION version to the specific version of node you want (if you're trying to get a different version).  More info here if that's helpful: 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings
https://stackoverflow.com/questions/49272104/azure-function-set-node-version

**Comment by mikhailshilkov** [comment]
Yes, thank you @CyrusNajmabadi , I've already set it to `beta` so I'm not blocked.
Also learned about `WEBSITE_NODE_DEFAULT_VERSION` the hard way: they actually default to Node `0.10` where nothing actually works. A cool feature of Pulumi would be to enforce that or default to a more sensible version.

**Comment by CyrusNajmabadi** [comment]
This shoudl now be fixed with: https://github.com/pulumi/pulumi-azure/pull/125

We have upgraded to v1.15 of terraform, which should have loosened this restriction.  You should see this in an upcoming release of Pulumi soon!
