### ISSUE TITLE
Location is deprecated, should be global.       

### ISSUE THREAD

**Issue by drmanhatin** [pulumi/pulumi-azure#1238]
File: [themes/default/content/docs/reference/pkg/azure/frontdoor/frontdoor.md](https://www.pulumi.com/docs/reference/pkg/azure/frontdoor/frontdoor/)

Location is deprecated, should be global.       

azure:frontdoor:Frontdoor exampleFrontdoor  warning: urn:pulumi:dev::apiappservice::azure:frontdoor/frontdoor:Frontdoor::exampleFrontdoor verification warning: "location": [DEPRECATED] Due to the service's API changing 'location' must now always be set to 'Global' for new resources, however if the Front Door service was created prior 2020/03/10 it may continue to exist in a specific current location

This error happens when you use the sample code.

**Comment by mikhailshilkov** [comment]
The linked example doesn't have a location set for FrontDoor anymore, so I'll close as fixed
