### ISSUE TITLE
Creating VMs with Shared and Community galleries

### ISSUE THREAD

**Issue by Zviger** [pulumi/pulumi-azure#1241]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hello Pulumi team

I'm working on a project where I need to be able to use public and shared Images. Azure api and sdks already have possibility to do this. As I understand, also, Terraform uses VM api of 2021-11-01 and it has what I need.  This is a [link](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2021_11_01.models.imagereference?view=azure-python) to the Azure sdk docs where the needed attributes (shared_gallery_image_id and community_gallery_image_id) are provided. Do u have in a plans to add them in pulumi azure classic? The same question regarding native)

### Affected area/feature

Pulumi Azure Classic Compute

**Comment by rquitales** [comment]
Hi @Zviger

It looks like this is already supported in Azure Classic. You should be able to use `source_image_id` when defining your VirtualMachine resource. As per our docs, `source_image_id` supports specifying a shared_gallery_image_id and community_gallery_image_id.

Reference doc:
https://www.pulumi.com/registry/packages/azure/api-docs/compute/linuxvirtualmachine/#source_image_id_python
