### ISSUE TITLE
Python test code fails on SkuArgs

### ISSUE THREAD

**Issue by FergusKidd** [pulumi/pulumi-azure#1257]
File: [docs/reference/pkg/azure/appservice/plan.md](https://www.pulumi.com/docs/reference/pkg/azure/appservice/plan/)

The example code requires access to SkuArgs under azure.appservice.SkuArgs, but fails with error:

AttributeError: module 'pulumi_azure.appservice' has no attribute 'PlanSkuArgs'

**Comment by mikhailshilkov** [comment]
Hi @FergusKidd, `PlanSkuArgs` do exist: https://github.com/pulumi/pulumi-azure/blob/master/sdk/python/pulumi_azure/appservice/_inputs.py#L21380

The following program actually succeeds to preview for me (with a somewhat confusing warning):

```
import pulumi
import pulumi_azure as azure

example_resource_group = azure.core.ResourceGroup("exampleResourceGroup", location="West Europe")
example_plan = azure.appservice.Plan("examplePlan",
    location=example_resource_group.location,
    resource_group_name=example_resource_group.name,
    sku=azure.appservice.PlanSkuArgs(
        tier="Standard",
        size="S1",
    ))
```

I wonder if something else is going on for you...

**Comment by mikhailshilkov** [comment]
By the warning says you should rather use this resource instead of `azure.appservice.Plan`: https://www.pulumi.com/registry/packages/azure/api-docs/appservice/serviceplan/

Do you want to give it a try?

**Comment by mikhailshilkov** [comment]
I think I responded the original question, so closing as "by design"
