### ISSUE TITLE
Import command is failing due to lower case 'r' in redis.

### ISSUE THREAD

**Issue by kwrightepc** [pulumi/pulumi-azure#1275]
File: [themes/default/content/registry/packages/azure/api-docs/redis/cache/_index.md](https://www.pulumi.com/registry/packages/azure/api-docs/redis/cache/)

When using the import command I'm receiving an error stating that "Error parsing Resource ID pulumi import azure:redis/cache:Cache cache1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Cache/redis/cache1: ID was missing the `Redis` element" 

this seems to be resolved when I change the /redis/ to /Redis/.  Please update the page to reflect the upper case.

**Comment by susanev** [comment]
thx for the report @kwrightepc! we will take a look as soon as we can.

**Comment by aq17** [comment]
Going to close this for now if no additional comments/ issues.
