### ISSUE TITLE
Pull in new terraform azurerm provider 1.16.0

### ISSUE THREAD

**Issue by slikk66** [pulumi/pulumi-azure#134]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.16.0/CHANGELOG.md

Looks like they've added since October 1st a new azure provider, which adds support "data_actions" which I need for my project:

https://github.com/terraform-providers/terraform-provider-azurerm/pull/2000

Thanks!

**Comment by slikk66** [comment]
Adding note from developer that it's in azurerm provider 1.16.0 - https://github.com/terraform-providers/terraform-provider-azurerm/issues/1538

**Comment by slikk66** [comment]
Thanks @lukehoban @joeduffy this came at a great time and will help get my company on board for going full Pulumi!! 🍻 💯

**Comment by joeduffy** [comment]
Excellent to hear this!! :+1: :100:

**Comment by lukehoban** [comment]
This is now available in v0.16.1 of https://www.npmjs.com/package/@pulumi/azure.
