### ISSUE TITLE
Use terraform-provider-azurerm v1.18.0.

### ISSUE THREAD

**Issue by mpp-oliverh** [pulumi/pulumi-azure#141]
Terraform-provider-azurerm v1.18.0 was released on the 2nd November. v1.17.0 was mid Oct.

https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v1.18.0

I have a very minor patch merged into v1.17.0 which I need to be able to use managed identities (it exposes the clientId property).

Is there any info about when this might be done - I've tried a few workarounds but none of them work both locally and on VSTS/DevOps and it's a blocker for me.

Many thanks!

**Comment by lukehoban** [comment]
> I have a very minor patch merged into v1.17.0 which I need to be able to use managed identities (it exposes the clientId property).

Note that I believe we are up to date with 1.17.0. Definitely should add information about what version is currently supported somewhere clear though.

**Comment by mpp-oliverh** [comment]
Oh you're right! Fantastic news. 

I saw https://github.com/pulumi/pulumi-azure/pull/136 and thought it was v1.16.0 but UserAssignedIdentity has the clientId property now.

Thanks a lot.
