### ISSUE TITLE
Preview fails when setting FunctionApp/AppService siteConfig.use32BitWorkerProcess property

### ISSUE THREAD

**Issue by johlrich** [pulumi/pulumi-azure#157]
Preview fails when setting siteConfig.use32BitWorkerProcess property on a FunctionApp or AppService. It looks like the tf mapping is off by a character based on the error message: `error: azure:appservice/appService:AppService resource 'abc-stage-clbdir' has a problem: site_config.0: invalid or unknown key: use32_bit_worker_process`

use32_bit_worker_process looks like it should be passed down as [use_32_bit_worker_process](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#use_32_bit_worker_process)

**Comment by lukehoban** [comment]
@jen20 Is this an issue in the `tfbridge` name translation?

**Comment by jen20** [comment]
Yes, it looks like that is the issue. I'll look at what can be done to fix this.

**Comment by jen20** [comment]
Adding a test for this in `pulumi-terraform` shows that it is the problem:

```
=== RUN   TestPulumiToTerraformName
--- FAIL: TestPulumiToTerraformName (0.00s)
	Error Trace:	names_test.go:32
	Error:		Not equal: "use_32_bit_worker_process" (expected)
        	        != "use32_bit_worker_process" (actual)
```

@lukehoban: is it sufficient here to override the `Name` of the property in the mapping of the resources in question to fix this?

**Comment by ebashmakov** [comment]
@lukehoban @jen20 are you guys to close this issue? currently it's not possible to create an AppService (FunctionApp/WebApp) with `"use32BitWorkerProcess": true` (which is the common case).

**Comment by swgillespie** [comment]
Very possible, but I'm not familiar with the code at all, so I'd have to look.

**Comment by jen20** [comment]
A simpler fix for this is to just override the name, I'll open a PR shortly.
