### ISSUE TITLE
Non-empty refresh for LoadBalancer

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-azure#1571]
### What happened?

Getting a non-empty refresh diff after a pulumi up on ./examples/loadbalancer. 

```
No resources will be modified as part of this refresh; just your stack's state will be.
 details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:pulumi:Stack::loadbalancer-loadbalancerchecks]
    ~ azure:lb/natRule:NatRule: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/inboundNatRules/tcp13f0201]
        [urn=urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/natRule:NatRule::tcp]
        [provider=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e::6549b263-cab6-49f7-9d7f-f63f11b1fc3d]
        --outputs:--
      + backendIpConfigurationId   : "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/networkInterfaces/networkinterfaceecbfbf25/ipConfigurations/ipconfig"
    ~ azure:lb/loadBalancer:LoadBalancer: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186]
        [urn=urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/loadBalancer:LoadBalancer::lb]
        [provider=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e::6549b263-cab6-49f7-9d7f-f63f11b1fc3d]
        --outputs:--
      ~ frontendIpConfigurations: [
          ~ [0]: {
                    id                                          : "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/frontendIPConfigurations/LoadBalancerFrontEnd"
                  ~ inboundNatRules                             : [
                      + [0]: "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/inboundNatRules/tcp13f0201"
                    ]
                  ~ loadBalancerRules                           : [
                      + [0]: "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/loadBalancingRules/lbruleaa26d69"
                    ]
                    name                                        : "LoadBalancerFrontEnd"
                    privateIpAddressAllocation                  : "Dynamic"
                    publicIpAddressId                           : "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/publicIPAddresses/lbpipe7568f5b"
                }
        ]
    ~ azure:network/publicIp:PublicIp: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/publicIPAddresses/lbpipe7568f5b]
        [urn=urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/publicIp:PublicIp::lbpip]
        [provider=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e::6549b263-cab6-49f7-9d7f-f63f11b1fc3d]
        --outputs:--
      + ipAddress           : "172.171.200.114"
    ~ azure:lb/probe:Probe: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/probes/lbprobe66c3f98]
        [urn=urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/probe:Probe::lbprobe]
        [provider=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e::6549b263-cab6-49f7-9d7f-f63f11b1fc3d]
        --outputs:--
      ~ loadBalancerRules: [
          + [0]: "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/loadBalancingRules/lbruleaa26d69"
        ]
    ~ azure:lb/backendAddressPool:BackendAddressPool: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/backendAddressPools/backendPool99b61b4]
        [urn=urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/backendAddressPool:BackendAddressPool::backendPool]
        [provider=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e::6549b263-cab6-49f7-9d7f-f63f11b1fc3d]
        --outputs:--
      ~ backendIpConfigurations: [
          + [0]: "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/networkInterfaces/networkinterfaceecbfbf25/ipConfigurations/ipconfig"
        ]
      ~ loadBalancingRules     : [
          + [0]: "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/loadBalancers/lb599ad186/loadBalancingRules/lbruleaa26d69"
        ]
    ~ azure:network/networkInterface:NetworkInterface: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Network/networkInterfaces/networkinterfaceecbfbf25]
        [urn=urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/networkInterface:NetworkInterface::networkinterface]
        [provider=urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e::6549b263-cab6-49f7-9d7f-f63f11b1fc3d]
        --outputs:--
      + macAddress                 : "00-22-48-20-B5-8D"
      + virtualMachineId           : "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourcegroup50931089/providers/Microsoft.Compute/virtualMachines/vmc86c92c5"
```

### Example

See above. 

### Output of `pulumi about`

CLI          
Version      3.97.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
azure   4.42.0
nodejs  unknown

Host     
OS       darwin
Version  14.1.1
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/bin/node' version='v18.18.2'

Current Stack: t0yv0/loadbalancer/loadbalancerchecks

TYPE                                                                                                       URN
pulumi:pulumi:Stack                                                                                        urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:pulumi:Stack::loadbalancer-loadbalancerchecks
pulumi:providers:azure                                                                                     urn:pulumi:loadbalancerchecks::loadbalancer::pulumi:providers:azure::default_5_61_0_alpha_1703713941_4df0901e
azure:core/resourceGroup:ResourceGroup                                                                     urn:pulumi:loadbalancerchecks::loadbalancer::azure:core/resourceGroup:ResourceGroup::resourcegroup
azure:compute/availabilitySet:AvailabilitySet                                                              urn:pulumi:loadbalancerchecks::loadbalancer::azure:compute/availabilitySet:AvailabilitySet::avset
azure:network/virtualNetwork:VirtualNetwork                                                                urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/virtualNetwork:VirtualNetwork::vnet
azure:network/publicIp:PublicIp                                                                            urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/publicIp:PublicIp::lbpip
azure:lb/loadBalancer:LoadBalancer                                                                         urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/loadBalancer:LoadBalancer::lb
azure:lb/backendAddressPool:BackendAddressPool                                                             urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/backendAddressPool:BackendAddressPool::backendPool
azure:lb/probe:Probe                                                                                       urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/probe:Probe::lbprobe
azure:lb/natRule:NatRule                                                                                   urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/natRule:NatRule::tcp
azure:lb/rule:Rule                                                                                         urn:pulumi:loadbalancerchecks::loadbalancer::azure:lb/rule:Rule::lbrule
azure:network/networkInterface:NetworkInterface                                                            urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/networkInterface:NetworkInterface::networkinterface
azure:network/networkInterfaceNatRuleAssociation:NetworkInterfaceNatRuleAssociation                        urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/networkInterfaceNatRuleAssociation:NetworkInterfaceNatRuleAssociation::nat-rule-association
azure:network/networkInterfaceBackendAddressPoolAssociation:NetworkInterfaceBackendAddressPoolAssociation  urn:pulumi:loadbalancerchecks::loadbalancer::azure:network/networkInterfaceBackendAddressPoolAssociation:NetworkInterfaceBackendAddressPoolAssociation::pool-association
azure:storage/account:Account                                                                              urn:pulumi:loadbalancerchecks::loadbalancer::azure:storage/account:Account::storageaccount
azure:compute/virtualMachine:VirtualMachine                                                                urn:pulumi:loadbalancerchecks::loadbalancer::azure:compute/virtualMachine:VirtualMachine::vm

Found no pending operations associated with loadbalancerchecks

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@types/node     10.17.60
@pulumi/azure   4.42.0
@pulumi/pulumi  3.99.0

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/com.apple.shortcuts.mac-helper// by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
This no longer repros.  

The diffs here look like it is all output properties.  The behaviour of refresh changed in https://github.com/pulumi/pulumi/pull/16146 such that these output properties are not reported as refresh diffs.
