### ISSUE TITLE
Large GitHub Runners

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-azure#1632]
This repo uses large GitHub runners:

https://github.com/pulumi/pulumi-azure/blob/6c88b7f781911804ee33c08791020982af1ea6d7/.ci-mgmt.yaml#L27-L30

If possible, we should remove the large runners to reduce cost.

**Comment by VenelinMartinov** [comment]
fixed in https://github.com/pulumi/ci-mgmt/pull/827
