### ISSUE TITLE
Document subscription selection

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-azure#167]
A user in the community slack pointed out that the guide here: https://pulumi.io/quickstart/azure/setup.html does not have information on subscription selection. We should add guidance here.

**Comment by stack72** [comment]
@jen20 The [Azure setup page](https://pulumi.io/quickstart/azure/setup/) now has the following information on it:

```
You also need to obtain a Subscription ID. To retrieve your current Subscription ID, you can use:

$ az account show --query id -o tsv
To list all available subscriptions, you can use:

$ az account list --query '[].{subscriptionName:name,subscriptionId:id}' -o tsv
```

Are you happy that this can be closed out?

**Comment by jen20** [comment]
Yup, the new guidance there seems to cover this.
