### ISSUE TITLE
Sensitive data is exposed using azure classic provider

### ISSUE THREAD

**Issue by GabiSoare** [pulumi/pulumi-azure#1679]
### What happened?

When I initialize the Azure classic provider with Azure sensitive data i.e. client id/client secret to deploy some Azure resources, the sensitive data is not encrypted in the Pulumi stack and there it's exposed in plain text.

We have used Azure Classic instead of Azure native library because of this bug described here: 
https://github.com/pulumi/pulumi-azure-native/issues/684

Can be this solved with another version of Azure Classic provider as the Azure Native is built or what's your recommendation to mitigate this high-security issue? 

If there is not an easy fix to solve this, can you provide me some references about how to migrate from Azure Classic to Azure Native v1 and then to Azure Native v2  WITHOUT deleting the existing resources deployed in a production environment? 

### Example

The invoked object for Azure Classic provider: 
![image](https://github.com/pulumi/pulumi-azure/assets/5207983/50b4a971-80b1-40e8-9734-355cd8cd6218)

Azure Classic provider implementation:
![image](https://github.com/pulumi/pulumi-azure/assets/5207983/30eb69d8-a388-426c-a120-f322942ce4ca)
Here, the sensitive data is NOT encrypted in pulumi stack. 

I would expect to be implemented in the same way as the below
Azure Native provider implementation: 
![image](https://github.com/pulumi/pulumi-azure/assets/5207983/0eb73f3c-9cc6-4020-94dc-b6064fddfc4e)
Here, the sensitive data is encrypted in pulumi stack. 

### Output of `pulumi about`

The id and secret of the client are exposed in plain text in the Pulumi stack for the Azure Classic Provider input. 

### Additional context

For azure native v1 to v2 migration, we have this documentation:
https://www.pulumi.com/registry/packages/azure-native/from-v1-to-v2/

What about Classic to Native migration? It this possible?

BR, Gabriel

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks so much for reporting @GabiSoare indeed it appears that the auth-related fields are not marked as secret which can expose users to unnecessary risk. Correcting this oversight in #1686. 

As to classic to native migration we have some documentation in https://www.pulumi.com/registry/packages/azure-native/from-classic/ but it is far from an automated process at the moment.
