### ISSUE TITLE
Handle migration of Azure AD resources to a separate upstream provider

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-azure#168]
[This document](https://github.com/terraform-providers/terraform-provider-azurerm/blob/31b39db5241fb4cd3ce7805f7b692ccfcb174de1/website/docs/guides/migrating-to-azuread.html.markdown) details that Azure Active Directory management resources have been separate into their own Terraform provider and that the resources in the main provider are deprecated. We need to work out the best way to proceed there.

**Comment by lukehoban** [comment]
It's possible that at this point, most of the users who would have benefitted from this have already gone through the migration process (replacing resources or manually modifying state files).  Is there still significant value in improving this?

**Comment by stack72** [comment]
@lukehoban do we want to apply the work for the Aliasing that @CyrusNajmabadi did in pulumi-terraforn?

**Comment by stack72** [comment]
It has been decided that the deprecation message that has been around in terraform for months has prepared our users that these are actually not maintained anymore. Adding any more messaging in Pulumi would actually confuse things
