### ISSUE TITLE
Write an opinionated guide to how to authenticate for different scenarios

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-azure#170]
Azure provides many different ways to authenticate, which are appropriate in different circumstances. We should have a document which explains which types of credentials are appropriate in which situation (e.g. Pulumi on a dev machine, in CI, on an Azure VM etc) with specific instructions on how to find the relevant pieces of information.

**Comment by lukehoban** [comment]
Is this https://pulumi.io/quickstart/azure/setup.html?

**Comment by jen20** [comment]
Yes - I think this issue could be fixed instead by linking to this in the README for the Azure provider.
