### ISSUE TITLE
Azure Function Dependencies not packaged

### ISSUE THREAD

**Issue by newtack** [pulumi/pulumi-azure#177]
When I write an Azure function without dependencies it got deployed correctly without problems. But when I included an NPM dependency, this was not packaged up. Is this simply not supported or do I need to do something extra?

**Comment by ellismg** [comment]
> But when I included an NPM dependency, this was not packaged up. Is this simply not supported or do I need to do something extra?

No, it should be included by default.  Can you share an example of what's not working and what your `package.json` looks like?

**Comment by ellismg** [comment]
If you could share how you are creating the azure function as well, that would be helpful.

**Comment by newtack** [comment]
I'll see if I can put something together. 
I am using yarn workspaces, could this be a source of the problem?

**Comment by ellismg** [comment]
> I am using yarn workspaces, could this be a source of the problem?

It's certainly possible.  We had issues in the past where Pulumi would fail to run if the `@pulumi/pulumi` was installed using workspaces, which we have sense fixed.  It's possible there's some interaction in our closure serialization code and asset gathing logic and workspaces, and if so, I'd love to fix it.

Just a sketch of the part of your pulumi program that is creating the azure resources would be helpful.  I can fill out the handler to do something interesting using a package installed a workspace myself, I just want to understand how you actually go about creating the function and its supporting infrastructure.

**Comment by mikhailshilkov** [comment]
@newtack Am I guessing correctly that you have been using [`pulumi-azure-serverless`](https://github.com/pulumi/pulumi-azure-serverless) for functions?

If so, the functionality got merged into this repo. Could you maybe give it another try? The feature is summarized in [this blog post](https://blog.pulumi.com/serverless-as-simple-callbacks-with-pulumi-and-azure-functions).

**Comment by newtack** [comment]
Thanks! This is a great improvement.

**Comment by stack72** [comment]
Hi @newtack / @mikhailshilkov 	

Is this still an issue? I'd like to work out what is still missing, if anything, from pulumi-azure

Thanks

Paul

**Comment by stack72** [comment]
Hi @newtack / @mikhailshilkov 	

I am going to close this one out - it doesn't seem to be an issue but if I am wwrong, then please do let me know and we will reopen it

Paul
