### ISSUE TITLE
Async Azure Function

### ISSUE THREAD

**Issue by newtack** [pulumi/pulumi-azure#178]
Are async Azure functions supported? If so, can you provide an example?

**Comment by lukehoban** [comment]
You can see a raw examples of Azure Functions at https://github.com/pulumi/examples/tree/master/azure-ts-functions. 

You can find some examples of Azure Functions hooked up to Azure event sources at https://github.com/pulumi/pulumi-azure-serverless/blob/master/nodejs/azure-serverless/examples.  That `@pulumi/azure-serverless` library is very early, but shows some of the patterns of what can be built on top of the core `pulumi-azure` resources.  

All of these are "async" in at least some interpretations of the word - if there is something more specific you have in mind - let us know.
