### ISSUE TITLE
Azure tests running out of disk space

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-azure#1810]
### What happened?

We probably need to do the same as in AWS and clean disk space in the preTest step

### Example

https://github.com/pulumi/pulumi-azure/actions/runs/8114975996/job/22182601885?pr=1809

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@VenelinMartinov I'm assign this to you as part of https://github.com/pulumi/pulumi-azure/issues/1632.

**Comment by VenelinMartinov** [comment]
Addressed in https://github.com/pulumi/pulumi-azure/pull/1809/files
