### ISSUE TITLE
When getting an existing cluster, there isn't a way to pull the kubeconfig 

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-azure#186]
In the current cluster object, we can use the `cluster` props: `certificateAuthority`, `name`, and `endpoint` to fill in the blanks in the kubeconfig file https://gist.github.com/b01eeecacccc3e284771463ed626af5e

we only do this right now in the object constructor, when we should actually have a `kubeconfig()` method on the object.

see community slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1550871454193500?thread_ts=1550862777.160400&cid=C84L4E3N1

related: https://github.com/pulumi/pulumi-aws/issues/478

**Comment by joeduffy** [comment]
@metral I am doing a general triage of Azure bugs during the Hackathon today, and ran across this. Is this meant to be an EKS bug? (It's in the Azure repo...)

**Comment by metral** [comment]
Thanks for following up on this one. It turns out AKS has a means of getting the kubeconfig file already: e.g. `pulumi.export('kubeconfig', aks.kube_config_raw)` so we can close this out.
