### ISSUE TITLE
Docs for FunctionApp reference TF provider versions and not Pulumi Provider versions

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-azure#1993]
### What happened?

If you visit https://www.pulumi.com/registry/packages/azure/api-docs/appservice/functionapp/ and look at the "NOTE" at the top of the page, you'll see that it talks about the resource being deprecated in v 3.0 and removed in v4.0 but we're in v5.x of the Azure Classic provider

### Example

<img width="1222" alt="image" src="https://github.com/pulumi/pulumi-azure/assets/109047/9d2d3421-475b-47d8-b0b9-84b0cde6b4f5">

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
@pierskarsenbarg here's the patch: #1997
