### ISSUE TITLE
Unable to define the permissions for the azure app

### ISSUE THREAD

**Issue by moattarwork** [pulumi/pulumi-azure#206]
I have very simple scenario. I've created two azure ad apps for frontend and backend and now I need access to backend to be gven to frontend app.

In azure CLI there are couple of way I can do that:
- With the help of **--required-resource-accesses** flag
- Using **az ad app permission add**

None of them are available in pulumi today as I understand. I'm wonder if there is anything future releases and other ways to achieve the same result.

**Comment by mikhailshilkov** [comment]
I think this issue should be moved to https://github.com/pulumi/pulumi-azuread/ and it probably depends on the upstream https://github.com/terraform-providers/terraform-provider-azuread/issues/33

**Comment by lukehoban** [comment]
I'm going to close this out - as it appear to match what's tracked at terraform-providers/terraform-provider-azuread#33.  Once this is available there, it will be picked up automatically in the `@pulumi/azuread` provider.
