### ISSUE TITLE
There is no azure.msi.getUserAssignedIdentity.

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-azure#207]
There is no `azure.msi.getUserAssignedIdentity`. 

I had a brief look in the terraform here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_user_assigned_identity.go and it seems to list a 'read' method.

**Comment by mikhailshilkov** [comment]
The function is located in a different namespace: `azure.core.getUserAssignedIdentity`. We should probably move it to `msi` as part of #97.

**Comment by stack72** [comment]
Thanks for this @mikhailshilkov - you are indeed correct. That will be handled in this iteration

I am going to close this out and we can track all of this work in #97
