### ISSUE TITLE
Random characters at end of resource name

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi-azure#209]
I did a evaluation of Pulumi if it could be a replacement for Terraform in Cloud projects. I was a bit baffled when I discovered that the Pulumi Azure backend adds always 8 random characters to a resource name

https://github.com/pulumi/pulumi-azure/blob/cf8e011adfd83b3d1f550d35b8dc081224914986/resources.go#L849

https://github.com/pulumi/pulumi-azure/blob/cf8e011adfd83b3d1f550d35b8dc081224914986/resources.go#L844

and why this is not configurable? Well personally I didn't find a possibility to switch off this behavior. According to the code above and where and how the corresponding function `AutoNameWithMaxLength` is called, it doesn't look like this could be configured in any way.

So what's the technical background why the Azure Provider adds those random characters?

**Comment by lblackstone** [comment]
Hi @tmeckel, you should be able to specify the name of the resource manually by setting the `name` argument on the resource inputs. See https://pulumi.io/reference/programming-model.html#autonaming for more info on this behavior.

Closing out this issue for now, but feel free to reopen if you have an example where this isn't working.

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/pulumi/issues/1518 which tracks adding the ability to suppress auto naming at a more coarse-grained level.

**Comment by tmeckel** [comment]
@lblackstone , @lukehoban thanks for the quick answers. Highly appreciated!

Can someone add the fact about **autonaming** more prominently to the official documentation? Even a small hint would be great. :+1:  like some **TL;DR** stuff in the _Getting started_ chapters e.g. https://pulumi.io/quickstart/azure/index.html

I guess this would be very valuable to others because I think when you come from Terraform or another tool to deploy your cloud resources you get quickly confused like me by the default behavior of Pulumi. Especially when I take into account that the name parameter in the costructors for Pulumi Output objects is not the final name and you've to specify the desired name additionally in the `name` property of the object. Like @lblackstone wrote.

That said, and because the https://github.com/pulumi/pulumi/issues/1518 isn't available right now, I changed my exsiting code e.g. for deploying a resource group from 

```typescript
const rg = new azure.core.ResourceGroup(`rg-${resource_prefix}`,
    { location: "West Europe"} 
);
```

to 

```typescript
const rg = new azure.core.ResourceGroup(`rg-${resource_prefix}`,
    { 
        name: `rg-${resource_prefix}`,
        location: "West Europe"
    } 
);
```

Obviously this worked :+1: but now one have to be careful because `pulumi up` only shows, let's call them the, _internal_ names (those which are specified as the constructor parameter) and not those defined as the `name` property. If you're not consistent with your naming (different values in constructor and `name`  property) this could lead to other suprises. Will this be addressed by https://github.com/pulumi/pulumi/issues/1518 as well?

**Comment by jamesianberry** [comment]
Feedback on my experience with https://github.com/pulumi/examples/pull/611
a) auto-naming is fine most of the time although I went out of my way to ensure a dash separator from the random part that comes along during provisioning (is there a setting for this?)
b) where Azure requires e.g. a specific subnet name I allocated a logical name without a trailing dash separator and used the name= to ensure the specific physical name which worked fine
c) I had to change my naming convention to ensure maximum name lengths weren't exceeded
