### ISSUE TITLE
Container registry always gets a "Managed" SKU

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-azure#2136]
### Describe what happened

Creating a container registry seems to always end up with a "Managed" SKU regardless of the value provided.

### Sample program

```ts
import * as azure from "@pulumi/azure";

const rg = new azure.core.ResourceGroup("myrg");
const registry = new azure.containerservice.Registry("myregistry", {
  resourceGroupName: rg.name,
  sku: "Basic", // or "Standard"
});

export const sku = registry.sku;
```

### Log output

```
❯ PULUMI_CONFIG_PASSPHRASE="" pulumi up -s dev
Previewing update (dev):
     Type                                Name              Plan
 +   pulumi:pulumi:Stack                 cbp-azure-ts-dev  create
 +   ├─ azure:core:ResourceGroup         myrg              create
 +   └─ azure:containerservice:Registry  myregistry        create

Outputs:
    sku: "Basic"

Resources:
    + 3 to create

Do you want to perform this update? yes
Updating (dev):
     Type                                Name              Status
 +   pulumi:pulumi:Stack                 cbp-azure-ts-dev  created (35s)
 +   ├─ azure:core:ResourceGroup         myrg              created (9s)
 +   └─ azure:containerservice:Registry  myregistry        created (19s)

Outputs:
    sku: "Managed"

Resources:
    + 3 created

Duration: 36s
```

### Affected Resource(s)

azure:containerservice:Registry

### Output of `pulumi about`

CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  azure   5.80.0
language  nodejs  unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/bryce/.nvm/versions/node/v18.17.0/bin/node' version='v18.17.0'

Backend
Name           Bryces-Work-MBP
URL            file:///Users/bryce/src/pulumi-docker/examples/azure-container-registry/ts/
User           bryce
Organizations
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/azure   5.80.0
@pulumi/pulumi  3.120.0
@types/node     14.18.63

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by akeesari** [comment]
I've been encountering a similar issue recently with my Azure Container Registry. It was created using Terraform as Infrastructure as Code (IaC), and I've configured it for Premium tier. However, every time I run the `terraform plan` command, it consistently displays the same message. Despite applying changes to update the Premium SKU, the issue persists, which is quite frustrating. Additionally, every `terraform apply` operation is taking a long time to update the ACR resource. appreciate for any inputs.

For example: 
 # azurerm_container_registry.acr[0] will be updated in-place
  ~ resource "azurerm_container_registry" "acr" {
        id                            = "/subscriptions/{subscription_id}/resourceGroups/rg-acr-dev/providers/Microsoft.ContainerRegistry/registries/{acr_name}"
        name                          = "acr_name"
      ~ sku                           = "Managed" -> "Premium"
        tags                          = {}
        # (17 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by blampe** [comment]
This was due to an API change in Azure which has been reverted. https://github.com/hashicorp/terraform-provider-azurerm/issues/26414#issuecomment-2187839813
