### ISSUE TITLE
Should `azure.storage.Blob` be marked as delete before create?

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-azure#215]
Many of the properties on the underlying terraform resource are marked as force new, so when they change, pulumi correctly determines it needs to do a replacement.  However, since the name of the resource has to be unique within the container, if we try to create a new version before updating the old one, we fail with an error like this:

```
 azure:storage:Blob (empty412a0b100650):
    error: Plan apply failed: A resource with the ID "https://sa412a0b1006507bbd7861.blob.core.windows.net/data/empty" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_storage_blob" for more information.
```

You can address this by passing `deleteBeforeCreate: true` as part of the resource options, but it feels like this should be the default?

**Comment by stack72** [comment]
After an internal discussion, we have decided that this would be a good candidate for a default behaviour change. It is being tracked as https://github.com/pulumi/pulumi-terraform/issues/383

I am therefore going to close this out - the related issue will show when this is available in the providers
