### ISSUE TITLE
Configure URL and HTTP methods of HttpEventSubscription

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#220]
1. Now, HTTP function always gets the name of `HttpEventSubscription` which isn't very flexible. E.g. I can't have two Function Apps with functions with same names because I can't name Function Apps the same. I may have multiple Apps each having a Function called "http", which isn't possible now.

2. We should use `route` parameter too.

Here is an example of HTTP binding which is not possible with the current serverless extensions:

``` json
{
      "type": "httpTrigger",
      "name": "req",
      "direction": "in",
      "authLevel": "anonymous",
      "route": "{id}",
      "methods": [
        "get"
      ]
    }
```

Note the route which basically allows to accept a parameter in the URL itself and get the parameter value in the binding data: `context.bindingData.id`.

3. While we are here, `methods` should also be configurable to allow POST requests.

**Comment by mikhailshilkov** [comment]
ping @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
So i orignally thought about thsi.  But i don't know why this needs to be on hte binding.  We already pass the user a HttpRequest object that has these values:

```ts
    };
    /**
     * Query string parameter keys and values from the URL.
     */
    query: {
        [key: string]: string;
    };
    /**
     * Route parameter keys and values.
     */
    params: {
        [key: string]: string;
    };
```

Is that not sufficient?

**Comment by mikhailshilkov** [comment]
If you don't have it in the binding, the function won't react to a URL like `https://myapp.bla/anythinggoeshere` but only to `https://myapp.bla/functionname`.

**Comment by CyrusNajmabadi** [comment]
> If you don't have it in the binding, the function won't react to a URL like https://myapp.bla/anythinggoeshere but only to https://myapp.bla/functionname.

Ohhh you mean having a way to do wildcard paths.  Yes, we may need that.  Currently we have that in awsx through the use of a ProxyRoute.  We'd likely need something similar here.  I'll keep this open so we can design it properly.  Thanks!

**Comment by mikhailshilkov** [comment]
Yes, they have a simple templating for Function urls. It can be just `/{name}`, or things like `/{year}/{month}/{day}`. I got blocked because I can't do wildcards (wanted to accept a key of a document to lookup in the database).
