### ISSUE TITLE
Simplify output data flow in callback functions

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#232]
## Problem

We've simplified the definition of Azure Functions so that people could use JS callbacks and deploy them as functions. The event data is provided as an input to the callback.

Typically, a function would need to produce some data and send it somewhere. At the moment, we only support one type of return data: HTTP response. Obviously, there are lots of other scenarios what developers might want to do. Some common examples:

- Send another message from a message-triggered function
- Save another blob from a blob-triggered function
- Save a document to Cosmos DB
- Enqueue a message from HTTP function

Say, I want to implement the last bullet point right now. Here is the code:

``` ts
import { Aborter, QueueURL, MessagesURL, ServiceURL, StorageURL, SharedKeyCredential } from "@azure/storage-queue";

const greeting = new azure.appservice.HttpEventSubscription('greeting', {
    resourceGroup,    
    callback: async (context, args) => {
        const account = storageAccount.name.get();
        const accountKey = storageAccount.primaryAccessKey.get();
        const sharedKeyCredential = new SharedKeyCredential(account, accountKey);
        const pipeline = StorageURL.newPipeline(sharedKeyCredential);
        const serviceURL = new ServiceURL(`https://${account}.queue.core.windows.net`, pipeline);
        const queueName = queue.name.get();
        const queueURL = QueueURL.fromServiceURL(serviceURL, queueName);
        const messagesURL = MessagesURL.fromQueueURL(queueURL);
        const contents = Buffer.from("Hello World!").toString('base64');
        const enqueueQueueResponse = await messagesURL.enqueue(Aborter.none, contents);
      return {
        status: 200,
        body: `Hello World!`
      };
    }
  });
```

This works but... doesn't look entirely clean.

## Approach 1: Helper functions

We could add some mixins to simplify the most typical scenarios and make examples/demos look very clean. For the above snippet, we could enable

``` ts
callback: async (context, args) => {
    const enqueueQueueResponse = await queue.messagesURL().enqueue(Aborter.none, "Hello World!");
    // or simply
    const enqueueQueueResponse = await queue.enqueue("Hello World!");
```

which would do the same but hide the mechanics.

**Pro's**: Clean. Uses simple code and minimum config.
**Con's**: Needs explicit work for each supported scenario. Needs to include and adapt specific SDKs for each sink type.

## Approach 2: Azure Functions output bindings

Functions actually have a solution for this: output bindings. We could add support for those. I prototyped the scenario above and it looks relatively straightforward.

### Accept custom bindings

``` ts
export type HttpEventSubscriptionArgs = //...
    extraBindings?: BindingDefinition[];
}>;
```

### Define output bindings

``` ts
interface QueueOutBindingDefinition extends azure.appservice.BindingDefinition {
    name: string;
    type: "queue";
    direction: "out";
    dataType: "binary";
    queueName: pulumi.Input<string>;
    connection: string;
}
```

### Use the output binding in the callback

``` ts
const greeting = new azure.appservice.HttpEventSubscription('greeting', {
    resourceGroup,    
    extraBindings: [makeQueueOutBindingDefinition("queueOut", queue)],
    callback: async (context, args) => {
        context.bindings.queueOut = "Hello World";
      return {
        status: 200,
        body: `Hello World`
      };
    }
  });
```

**Pro's**: Native to Azure Functions. Reuse what's already available. Could add input bindings the same way.
**Con's**: Less direct API with defining `queueOut` in one place and then using it via untyped `context.bindings.queueOut`. Potentially, less flexible. Might need some trickery to include the right dependencies.

## Approach 3: return values

HTTP functions just return the value which makes total sense. We could try to do something like

``` ts
queue.onEvent("newMessage",  async (context, msg) => {
    return `Hello ${msg}`;
}).pipeTo(queue2);
```

I haven't expored this option further because it feels too opiniated and maybe better suitable to X package. Unless we can make it work in combination with output bindings.

**Comment by mikhailshilkov** [comment]
@lukehoban @CyrusNajmabadi would appreciate your ideas

**Comment by CyrusNajmabadi** [comment]
Definitely leaning toward Approach1.  It feels like a natural way to project things into the JS sdk.  

> Con's: Needs explicit work for each supported scenario. Needs to include and adapt specific SDKs for each sink type.

This doesn't feel too bad.  Just as we've exposed N event-hookup scenarios based on what's available, we can expose the M different sink types as appropriate.

**Comment by lukehoban** [comment]
> Definitely leaning toward Approach1

I'll admit that given the underlying Azure Functions feature here, it feels like approach 2 or 3 would be more "natural"?  

Adding new runtime helpers is fairly awkward for Pulumi - we've generally avoided this nearly completely (the only example I can think of is exposing `aws.sdk` to get access to a runtime copy of the AWS SDK).  

Something where we could declaratively describe the output bindings as an easier way to accomplish what goes in  the current Functions JSON configuration feels  a little more in-line with the platform (and with Pulumi)?

**Comment by CyrusNajmabadi** [comment]
Sorry, i missed particularly that these would be runtime extensions.  I agree with luke that it would make sense ot just try to expose bindings cleanly here.

**Comment by ChristianEder** [comment]
If I may give my opinion:

I'm strongly in favor of option 2 - let me explain why:

**Option 1**
Pro:

- The code looks neat & clean

Con:

- pulumi either basically implements client SDKs for any service that can be used as output, or takes dependencies on existing SDKs
- Most likely, it won't be possible to provide the same value to users that the bindings provided by Microsoft do - like e.g. retry mechanisms and batching storage access
- It doesn't take into account that functions also can have multiple **input** bindings
- pulumi would only support what pulumi implements, not automatically everything thats supported by Microsoft

** Option 2**

Pro

- Supports multiple input and output bindings
- Is probably the thing Azure developers would expect
- Microsoft docs regarding function bindings would also apply to pulumi

Con:

- Code doesn't look as clean as the other options

** Option 3**

Pro:

- Code looks also pretty, clean, at least as clean as option 1
- Compared to option 1, probably less implementation overhead, since it could theoretically map to standard Microsoft provided output bindings

Con:

- It doesn't take into account that functions also can both have multiple **input** and **output** bindings
- pulumi would only support what pulumi implements, not automatically everything thats supported by Microsoft

**Conclusion**

I would propose to go with option 2, but provide helper functions to make it easy for developers to create binding definitions, similar to what you proposed in my PR (https://github.com/pulumi/pulumi-azure/pull/275):

`const storageAccount = new azure.storage.Account(...);

const functionArgs = {
  resourceGroup,
  callback: async (context, req: HttpRequest) => {...},
  bindings: [
    storageAccount.createTableOutputBinding("name",...)
  ]
};
const greeting = new azure.appservice.HttpEventSubscription('greeting', functionArgs)`

**Comment by mikhailshilkov** [comment]
Here is an example usage for my current suggestion:

``` ts
// Two queues are used as an example of the output
const queue = new azure.storage.Queue("queue", {
   resourceGroupName: resourceGroup.name,
   storageAccountName: storageAccount.name
});

const queue2 = new azure.storage.Queue("queue2", {
    resourceGroupName: resourceGroup.name,
    storageAccountName: storageAccount.name
});

// An HTTP function which also has an output to a queue
const greeting = new azure.appservice.HttpEventSubscription('greeting-out', {
    resourceGroup,   
    // Output bindings are defined as a dictionary with values created by mixins 
    outputBindings: {
        queueOut: queue.output(),
    },
    callback: async (context, request) => {
        const name = request.query["name"] || "World";
        return {
            // The callback returns ExtendedHttpStatus with HTTP response property and output data
            response: {
                status: 200,
                body: `Hi ${name}, this is the HTTP response`,
            },
            // The name of this property must match the name of the binding above
            queueOut: [`Hi ${name}, this is sent tot the queue`, "And one more"],
        };
    }
});

// One more example: a queue-triggered function with an output
queue.onEvent("queue-message",  {
    outputBindings: {
        queueOut: queue2.output(),
    },
    callback: async (context, msg) => {
        const text = msg.toString();
        return {
            queueOut: `Forwarding ${text}`
        };
    }
});
```

Every call to the HTTP endpoint will result in two messages in `queue` and then two messages in `queue2`.

---

A have a prototype code where this example works. Everything seems to be doable. The highlights of the changes:

``` ts
// Two return options for HTTP functions (note ExtendedHttpResponse)
export type HttpEventSubscriptionArgs = util.Overwrite<mod.CallbackFunctionAppArgs<
    mod.Context<HttpResponse>, HttpRequest, HttpResponse | ExtendedHttpResponse>

// Args accept bindings
export type XyzSubscriptionArgs = ... {
    ...
    outputBindings?: {[key: string]: appservice.AzureFunctionOutputBinding};
}>;

// Binding is an interface implemented by each destination
export class QueueOutputBinding implements appservice.AzureFunctionOutputBinding { ... }

// A mixin for a queue
declare module "./queue" {
    interface Queue {
        output(): appservice.AzureFunctionOutputBinding;
    }
}
Queue.prototype.output = function(this: Queue) {
    return new QueueOutputBinding(this);
}
```

---

Any opinions and suggestions are welcome!

**Comment by mikhailshilkov** [comment]
Actually, the same technique can be applied to Input Bindings too. If generalize the above, I can also make this work:

``` ts
// A table containing input data
const table1 = new azure.storage.Table("table1", {
    resourceGroupName: resourceGroup.name,
    storageAccountName: storageAccount.name,
});

// The input object will be loaded as an input argument
queue.onEvent("queue-message",  {
    bindings: {
        tableIn: table1.input({ partitionKey: "1", rowKey: "1" }),
        queueOut: queue2.output(),
    },
    callback: async (context, msg, tableIn) => {
        const text = msg.toString();
        return {
            queueOut: `Forwarding ${text} with ${tableIn.text}`
        };
    }
});
```

**Comment by ChristianEder** [comment]
Could you provide the code you used to implement that for my PR? Or should I just close the PR and you will start fresh?

**Comment by ChristianEder** [comment]
I am currently struggling to implement your proposal in my PR

**Comment by mikhailshilkov** [comment]
It's based on my other branch and needs some clean up. Is it okay if you wait until the other PR is merged and then I can contribute (or open a new one, if that's easier)?

**Comment by ChristianEder** [comment]
a) totally ok
b) i assume, opening a new one might be easier
