### ISSUE TITLE
PRC test failures in pulumi-azure

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-azure#2322]
### Describe what happened

A few tests fail under PRC in pulumi-azure: 

- [ ] TestAccAciVolumeMount - update with no diff?
- [x] Test_network - replacement for Subnet (https://github.com/pulumi/pulumi-azure/issues/2323, fix in https://github.com/pulumi/pulumi-azure/pull/2325)
- [x] Test_storage - replacement for Container (https://github.com/pulumi/pulumi-azure/issues/2330, fix in https://github.com/pulumi/pulumi-azure/pull/2331)

Part of https://github.com/pulumi/pulumi-terraform-bridge/issues/1785

### Sample program

https://github.com/pulumi/pulumi-azure/actions/runs/10178181276/job/28152031872?pr=2306

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
The subnet issue is https://github.com/pulumi/pulumi-azure/issues/2323 - this one reproes in terraform, so PRC is technically more truthful to the underlying provider.

We might still want to address it though.

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-azure/pull/2333 has a GRPC repro for the empty diff observed in TestAccAciVolumeMount.
I've had some trouble reproing manually.

**Comment by VenelinMartinov** [comment]
Debugging this a bit more here is the content of the tf instance diff:
```
Attributes: map[string]*terraform.ResourceAttrDiff{
			"network_rule_set.#": *terraform.ResourceAttrDiff{
				Old: "", New: "", NewComputed: true, NewRemoved: false, NewExtra: interface{}(nil), RequiresNew: false, Sensitive: false, Type: 0x0,
			},
		}
```

**Comment by t0yv0** [comment]
"network_rule_set.#" and NewComputed: true

This tells me that the number of set elements is unknown. Can you lift to a dedicated issue? Can be interesting.
