### ISSUE TITLE
Set additional properties of App Service Plan (Premium Functions)

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#235]
If I'm not missing something obvious, [only 3 properties](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/appservice/plan.ts#L115) of an app service plan can be set now.

For Azure Functions Premium, I need to set `maximumElasticWorkerCount` property, otherwise, it defaults to `1` which is kind of useless.

ARM seems to support [several other properties](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-02-01/serverfarms).

I suppose the main reason is that Terraform [doesn't expose](https://www.terraform.io/docs/providers/azurerm/d/app_service_plan.html) them either?

**Comment by lukehoban** [comment]
> I suppose the main reason is that Terraform doesn't expose them either?

Yes, this is most likely a limitation that needs to be fixed in the upstream AzureRM Terraform provider.

**Comment by mikhailshilkov** [comment]
Created a terraform issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/3445

**Comment by stack72** [comment]
Ok, there is a PR open to add this work https://github.com/terraform-providers/terraform-provider-azurerm/pull/3547

Fingers crossed this gets added to the next release of the terraform-provider

**Comment by lukehoban** [comment]
Closing out - as this is tracked in the upstream resource provider now.
