### ISSUE TITLE
Cannot register providers: Microsoft.TimeSeriesInsights

### ISSUE THREAD

**Issue by scottmack11** [pulumi/pulumi-azure#2439]
### Describe what happened

Since yesterday we have been having issues with all of our pipelines throwing the error

Cannot register providers: Microsoft.TimeSeriesInsights

Seems its been deprecated and removed by Azure, Similar issue can be viewed over on the Terraform issues https://github.com/hashicorp/terraform-provider-azurerm/issues/27466

We have tried upgrading Pulumi Azure to the latest version which should use mirror the fix seen on the Terraform issue by using the Azure Resource provider >= v3.90, however it does not fix the problem for us, it still attempts to register Microsoft.TimeSeriesInsights

### Sample program

Any kind of pulumi preview/refresh/update against a pulumi stack using azurerm resource provider <= v3.89 will throw the error

### Log output

Original Error: Cannot register providers: Microsoft.TimeSeriesInsights. Errors were: Cannot register provider Microsoft.TimeSeriesInsights with Azure Resource Manager: unexpected status 400 with error: DisallowedProvider: The operation is not permitted for namespace 'Microsoft.TimeSeriesInsights'. List of permitted provider namespaces is xxxxxxx

### Affected Resource(s)

Provider Microsoft.TimeSeriesInsights

### Output of `pulumi about`

CLI
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME        VERSION
azure       6.0.0
azuread     5.53.4
kubernetes  4.18.1
nodejs      unknown
random      4.16.5

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mpp-paulj** [comment]
I'm also having this issue, be great so help/share with me too please (Y)

**Comment by mikhailshilkov** [comment]
Reading the upstream issue, it sounds like pulumi-azure versions 5.65.0 or later should not have this problem.

@scottmack11 @mpp-paulj To double check - are you still having this issue with the latest version of the provider? Does it occur on a fresh stack/project?

**Comment by scottmack11** [comment]
> Reading the upstream issue, it sounds like pulumi-azure versions 5.65.0 or later should not have this problem.
> 
> [@scottmack11](https://github.com/scottmack11) [@mpp-paulj](https://github.com/mpp-paulj) To double check - are you still having this issue with the latest version of the provider? Does it occur on a fresh stack/project?

Im having this issue with existing stacks on version 5.57.0 but attempting to upgrade and move to version 6.0.0. I havent tried a fresh stack but will come back with results when I have attempted to do so.

**Comment by mikhailshilkov** [comment]
I tested locally on a clean project and 5.64.0 fails for me while 5.65.0 works. I was also able to migrate from a stack that has 5.64.0 in its state (had to edit it manually) to 6.0.0. Looking forward to other experience reports.

**Comment by scottmack11** [comment]
> I tested locally on a clean project and 5.64.0 fails for me while 5.65.0 works. I was also able to migrate from a stack that has 5.64.0 in its state (had to edit it manually) to 6.0.0. Looking forward to other experience reports.

Can confirm works fine from 6.0.0 directly its just the upgrade path

What did you need to manually edit in state to get this to work? Its painful having hundreds of stacks, but may be the quickest solution for me.

**Comment by mpp-paulj** [comment]
> I tested locally on a clean project and 5.64.0 fails for me while 5.65.0 works. I was also able to migrate from a stack that has 5.64.0 in its state (had to edit it manually) to 6.0.0. Looking forward to other experience reports.

Yes this is also the issue for me, trying to get the stack updated to the latest.

**Comment by mikhailshilkov** [comment]
@scottmack11 @mpp-paulj What is the exact command that you run after upgrading the SDK version? Any chance you run a refresh or a delete that are still on the old version of the provider?

**Comment by scottmack11** [comment]
So the first command my pipelines usually run when we are deploying is

npm install
pulumi refresh -y --skip-preview --suppress-outputs --non-interactive

For the sake of testing I have also pulled it all down locally and tried running all combinations of pulumi refresh/preview/up

Both versions, 5.57.0 (My old version) and 6.0.0 (What im upgrading to) throw the same error as is in the original post with all three pulumi commands.

**Comment by thomas11** [comment]
Here's a complete sequence of commands that I just tried out. To start with, since it's not possible anymore to create a new project on 5.64, I created a minimal project with one resource group on 5.65. Then, I hand-edited the stack, replacing all occurrences of 5.65 and 5_65 with 5.64/5_64.

Then:
```
> yarn add @pulumi/azure@5.64.0
[...]
info All dependencies
└─ @pulumi/azure@5.64.0
✨  Done in 4.33s.


> pulumi up -s dev
Previewing update (dev):
     Type                         Name                    Plan     Info
     pulumi:pulumi:Stack          azure-2439-upgrade-dev
     └─ azure:core:ResourceGroup  resourceGroup                    1 error

Diagnostics:
  azure:core:ResourceGroup (resourceGroup):
    error: 1 error occurred:
    	* Error ensuring Resource Providers are registered.
  [...]
    Original Error: Cannot register providers: Microsoft.TimeSeriesInsights. [...]


> pulumi stack export
{
    "version": 3,
    "deployment": {
        [...]
        "resources": [
            {
                "urn": "urn:pulumi:dev::azure-2439-upgrade::pulumi:providers:azure::default_5_64_0",
                "custom": true,
                "id": "104e1cbe-e119-488b-96fc-bd7327e93bc7",
                "type": "pulumi:providers:azure",
                "inputs": {
                    "__internal": {},
                    "version": "5.64.0"
                },
                "outputs": {
                    "version": "5.64.0"
                },
                "created": "2024-09-24T15:47:53.337195Z",
                "modified": "2024-09-24T15:47:53.337195Z"
            },
            [...]
        ]
    }
}


> yarn add @pulumi/azure@5.65.0
[...]
info All dependencies
└─ @pulumi/azure@5.65.0
✨  Done in 1.41s.


> pulumi up -s dev
Previewing update (dev):
     Type                 Name                    Plan
     pulumi:pulumi:Stack  azure-2439-upgrade-dev

Resources:
    2 unchanged

Do you want to perform this update? yes
Updating (dev):
     Type                 Name                    Status
     pulumi:pulumi:Stack  azure-2439-upgrade-dev

Resources:
    2 unchanged

Duration: 8s


> pulumi stack export
{
    "version": 3,
    "deployment": {
        [...]
        "resources": [
            {
                "urn": "urn:pulumi:dev::azure-2439-upgrade::pulumi:providers:azure::default_5_65_0",
                "custom": true,
                "id": "0f9a7296-782a-4d32-9ec9-8537b940fb2b",
                "type": "pulumi:providers:azure",
                "inputs": {
                    "__internal": {},
                    "version": "5.65.0"
                },
                "outputs": {
                    "version": "5.65.0"
                },
                "created": "2024-09-24T15:53:58.537993Z",
                "modified": "2024-09-24T15:53:58.537993Z"
            },
            [...]
       ]
    }
}
```

**Comment by scottmack11** [comment]
> Here's a complete sequence of commands that I just tried out. To start with, since it's not possible anymore to create a new project on 5.64, I created a minimal project with one resource group on 5.65. Then, I hand-edited the stack, replacing all occurrences of 5.65 and 5_65 with 5.64/5_64.
> 
> Then:
> 
> ```
> > yarn add @pulumi/azure@5.64.0
> [...]
> info All dependencies
> └─ @pulumi/azure@5.64.0
> ✨  Done in 4.33s.
> 
> 
> > pulumi up -s dev
> Previewing update (dev):
>      Type                         Name                    Plan     Info
>      pulumi:pulumi:Stack          azure-2439-upgrade-dev
>      └─ azure:core:ResourceGroup  resourceGroup                    1 error
> 
> Diagnostics:
>   azure:core:ResourceGroup (resourceGroup):
>     error: 1 error occurred:
>     	* Error ensuring Resource Providers are registered.
>   [...]
>     Original Error: Cannot register providers: Microsoft.TimeSeriesInsights. [...]
> 
> 
> > pulumi stack export
> {
>     "version": 3,
>     "deployment": {
>         [...]
>         "resources": [
>             {
>                 "urn": "urn:pulumi:dev::azure-2439-upgrade::pulumi:providers:azure::default_5_64_0",
>                 "custom": true,
>                 "id": "104e1cbe-e119-488b-96fc-bd7327e93bc7",
>                 "type": "pulumi:providers:azure",
>                 "inputs": {
>                     "__internal": {},
>                     "version": "5.64.0"
>                 },
>                 "outputs": {
>                     "version": "5.64.0"
>                 },
>                 "created": "2024-09-24T15:47:53.337195Z",
>                 "modified": "2024-09-24T15:47:53.337195Z"
>             },
>             [...]
>         ]
>     }
> }
> 
> 
> > yarn add @pulumi/azure@5.65.0
> [...]
> info All dependencies
> └─ @pulumi/azure@5.65.0
> ✨  Done in 1.41s.
> 
> 
> > pulumi up -s dev
> Previewing update (dev):
>      Type                 Name                    Plan
>      pulumi:pulumi:Stack  azure-2439-upgrade-dev
> 
> Resources:
>     2 unchanged
> 
> Do you want to perform this update? yes
> Updating (dev):
>      Type                 Name                    Status
>      pulumi:pulumi:Stack  azure-2439-upgrade-dev
> 
> Resources:
>     2 unchanged
> 
> Duration: 8s
> 
> 
> > pulumi stack export
> {
>     "version": 3,
>     "deployment": {
>         [...]
>         "resources": [
>             {
>                 "urn": "urn:pulumi:dev::azure-2439-upgrade::pulumi:providers:azure::default_5_65_0",
>                 "custom": true,
>                 "id": "0f9a7296-782a-4d32-9ec9-8537b940fb2b",
>                 "type": "pulumi:providers:azure",
>                 "inputs": {
>                     "__internal": {},
>                     "version": "5.65.0"
>                 },
>                 "outputs": {
>                     "version": "5.65.0"
>                 },
>                 "created": "2024-09-24T15:53:58.537993Z",
>                 "modified": "2024-09-24T15:53:58.537993Z"
>             },
>             [...]
>        ]
>     }
> }
> ```

Ah I see my mistake, im going to give this a try tomorrow when im back in work will post results

**Comment by scottmack11** [comment]
Just FYI anybody reading this with the same issue, the above post by @thomas11 has given me a path to migrate

**Comment by amsreinhardt** [comment]
I get this error with latest 5.x, with 6.0 and also with 6.1 alpha. None work with my existing project.

**Comment by mikhailshilkov** [comment]
@amsreinhardt Your Redis error looks incomplete? What is the command that you are running? We are fairly sure that this error comes only from old provider versions - what you see is likely that the old provider version is still executed from resources that are in your state file. You either need to upgrade them with a `pulumi up` command without refresh or delete operations, or edit your state file as explained above.

**Comment by thomas11** [comment]
A correction for my statement above.
> it's not possible anymore to create a new project on 5.64

It _is_ possible when setting `azure:skipProviderRegistration`, just not with the default config.

```
> rg pulumi/azure package.json
9:        "@pulumi/azure": "5.64.0",


> pulumi up -s dev
Previewing update (dev):
     Type                         Name              Plan       Info
 +   pulumi:pulumi:Stack          azure-2439-2-dev  create
     └─ azure:core:ResourceGroup  resourceGroup                1 error

Diagnostics:
  azure:core:ResourceGroup (resourceGroup):
    error: 1 error occurred:
    	* Error ensuring Resource Providers are registered.
...


> pulumi config -s dev set azure:skipProviderRegistration true


> pulumi up -s dev
Previewing update (dev):
     Type                         Name              Plan
 +   pulumi:pulumi:Stack          azure-2439-2-dev  create
 +   └─ azure:core:ResourceGroup  resourceGroup     create

Resources:
    + 2 to create

Do you want to perform this update?  [Use arrows to move, type to filter]
> yes
  no
  details
```

Not sure why `azure:skipProviderRegistration` didn't work for you, @scottmack11 . I set it like this: `pulumi config -s dev set azure:skipProviderRegistration true`.

**Comment by mikhailshilkov** [comment]
We established that this issue only applies to versions 3.64.0 and below of the provider, so I'll go ahead and close it as fixed. I'll summarize the findings below.

If you are getting this error, you are probably still on 3.64.0 or earlier, either in your program dependencies or in your state file. We recommend you upgrade to the version 3.65.0 (and subsequently to later versions) with the following two steps:

1. Upgrade the Pulumi Azure Classic dependency to 3.65.0 in your program (in package.json, requirements.txt, csproj, etc)
2. Run `pulumi up` to apply this upgrade to your stack.

Note that both steps are required for a successful upgrade. If you only do (1) and then run `pulumi refresh`, `pulumi up --refresh`, `pulumi preview --refresh`, `pulumi destroy` or similar, the old provider version from your stack's state file will still be used, which will cause the same error, regardless of what you have in your program dependency.

If you can't run `pulumi up` directly, e.g. when your pipeline has a `refresh` step baked it, we recommend setting the config variable `azure:skipProviderRegistration true` in your stack settings, and then keeping it until all the versions in the state file are upgraded. You can also set this config and keep using an older version of the provider until you are ready to upgrade (hopefully, soon).

In an exceptional case, you can choose to manually update all the dependency versions in your state file as described in [this comment](https://github.com/pulumi/pulumi-azure/issues/2439#issuecomment-2371711927) but this is manual and error-prone, so we don't recommend this option unless all other ways are somehow ruled out.

Also, a friendly reminder that we generally recommend using the [Azure Native provider](https://www.pulumi.com/registry/packages/azure-native/) where we have more control over mechanics like this one.

**Comment by wjavierdpc** [comment]
@mikhailshilkov do you mean 5.65 and not 3.65?
