### ISSUE TITLE
Upgrading LinkedServiceKeyVault in Pulumi.Azure 4.14.0 to 5.xx

### ISSUE THREAD

**Issue by joel-korpela** [pulumi/pulumi-azure#2457]
Hello,
we are doing .net8 update on our projects, and part of it is Pulumi side, so we can deploy functions and webapps correctly. Right now we are facing an issue, where LinkedServiceKeyVault resource has changed so, that ResourceGroupName and DataFactoryName properties have gone, and instead we have DataFactoryId field. This change triggers replace- operation in Pulumi. Replace wants to delete and create again the resource, but linked services (in datafactory) are heavily connected there, meaning several other are referencing this linked service, and those linked services are referenced by datasets and so on. Meaning, the deletion of those linkedservices would be a really tedious task, and not preferrable. The error we are receiving in our pulumi up command is: 

```
azure:datafactory:LinkedServiceKeyVault (datakeyvaultlinkedservice):
  error: sdk-v2/provider2.go:385: sdk.helper_schema:
    deleting Data Factory Key Vault Linked Service: (Name "DataKeyVault" / Factory Name "test-xxx" / Resource Group "test-xxx"):
      datafactory.LinkedServicesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error:
        autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The document cannot be deleted since it is referenced by xxx_Database." Target="/subscriptions/xxx/resourceGroups/test-xxx/providers/Microsoft.DataFactory/factories/test-xxxdataFactory/linkedservices/DataKeyVault": provider=[azurerm@5.89.0](mailto:azurerm@5.89.0)

error: deleting urn:pulumi:hcdataplatform_test::hcdataplatform::azure:datafactory/linkedServiceKeyVault:LinkedServiceKeyVault::datakeyvaultlinkedservice: 1 error occurred:
* deleting Data Factory Key Vault Linked Service: (Name "DataKeyVault" / Factory Name "test-xxx" / Resource Group "test-xxx"):
    datafactory.LinkedServicesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error:
      autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The document cannot be deleted since it is referenced by xxx_Database." Target="/subscriptions/xxx/resourceGroups/test-xxx/providers/Microsoft.DataFactory/factories/test-xxx/linkedservices/DataKeyVault"
```

The changes in code were like this ![Image](https://github.com/user-attachments/assets/89ba49cd-349c-4a48-8c03-b5381963100a)

Is it really so, that one change of field would require us a huge work regarding linkedservices? Or am I missing something here? Thanks in advance!

**Comment by danielrbradley** [comment]
Hi @joel-korpela sorry to see you're having some issues upgrading.

From the details you've included, it sounds like you're not expecting a delete during the upgrade process so the delete failing is not so much the issue - more that the plan is attempting a re-create in the first place?

Am I understanding correctly that between v4 and v5 the primary identifier of this resource has changed from being the `ResourceGroupName` and `DataFactoryName` to just the `DataFactoryId`? If so, this is almost certainly going to trigger pulumi to try to re-create the resource as it doesn't know that the old and new identifiers are actually pointing at the same resource.

There's two possible quick workarounds I could see for this issue:
1. Remove the existing resource from the state using [`pulumi state delete`](https://www.pulumi.com/docs/iac/cli/commands/pulumi_state_delete/) then re-import it after completing the upgrade using [`pulumi import`](https://www.pulumi.com/docs/iac/cli/commands/pulumi_import/).
2. Manually edit the Pulumi State file to fix these fields at the same time as updating the provider version:
   1. Export: `pulumi stack export` (also save a copy of the original state in case of making a mistake)
   2. Find and replace the provider version
   3. Fix the fields for any LinkedServiceKeyVault resources
   4. Re-import: `pulumi stack import`.

Hope that helps unblock your upgrade.
