### ISSUE TITLE
Document how to integrate with Health Integrated Rollouts

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#246]
We've been asked from time to time how to integrate with the Health Integrated Rollouts feature of Deployment Manager: https://azure.microsoft.com/en-us/blog/introducing-health-integrated-rollouts-to-azure-deployment-manager/. (Note that this is also sometimes referred to by its codename, "EV2.") This is possible, however, we should document how.

**Comment by stack72** [comment]
@joeduffy do you mean we need a blog post on this or something different, like an addition to pulumi/examples?

**Comment by mikhailshilkov** [comment]
This looks very stale at this point, I'll take the liberty to close
