### ISSUE TITLE
Cosmos DB - database and collection resources

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#252]
Currently, Pulumi only supports creating Cosmos DB accounts - not databases or collections.

Terraform just [merged](https://github.com/terraform-providers/terraform-provider-azurerm/pull/3442) this support, so I'm creating this issue to make sure we transfer this capability to Pulumi.

In addition, we need to add/update an example and enable serverless trigger on the collection resource level.

**Comment by mikhailshilkov** [comment]
Ok, the databases are supported now, but not SQL Collections yet.

**Comment by stack72** [comment]
@mikhailshilkov can you give me a quick TL;DR of what is still required for this issue? Is this a limitation upstream?

**Comment by mikhailshilkov** [comment]
Yes, they added a database and some collection types, but not the "SQL Collection" - a native Cosmos DB collection, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/3506

**Comment by mikhailshilkov** [comment]
Yes, they added a database and some collection types, but not the "SQL Collection" - a native Cosmos DB collection, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/3506

**Comment by stack72** [comment]
@mikhailshilkov, as this is a missing resource upstream, I am going to close this out. When the work to add support for `SQL Collections` is added, we will get a warning in the code generation that we need to add it

I am going to link https://github.com/terraform-providers/terraform-provider-azurerm/issues/3506 as the correct place for the questions on this
