### ISSUE TITLE
pulumi_azure.Provider.subscription_id is a secret despite not being sensitive

### ISSUE THREAD

**Issue by filip-taxamo** [pulumi/pulumi-azure#2571]
### Describe what happened

When building values using `Provider.subscription_id`, we end up with `[secret]` in pulumi preview even though the value is not sensitive.

### Sample program

https://github.com/pulumi/pulumi-azure/blob/b92fab31efb193cb53e5c1ada546d921e74a5a14/sdk/python/pulumi_azure/provider.py#L689

This seems to be a case with a lot of other non-senstive properties:
- https://github.com/pulumi/pulumi-azure/blob/b92fab31efb193cb53e5c1ada546d921e74a5a14/sdk/python/pulumi_azure/provider.py#L656
- https://github.com/pulumi/pulumi-azure/blob/b92fab31efb193cb53e5c1ada546d921e74a5a14/sdk/python/pulumi_azure/provider.py#L657
- https://github.com/pulumi/pulumi-azure/blob/b92fab31efb193cb53e5c1ada546d921e74a5a14/sdk/python/pulumi_azure/provider.py#L659
- https://github.com/pulumi/pulumi-azure/blob/b92fab31efb193cb53e5c1ada546d921e74a5a14/sdk/python/pulumi_azure/provider.py#L660

etc.

### Log output

```
             ~ roleDefinitionId: "/subscriptions/<subscription_id>/providers/Microsoft.Authorization/roleDefinitions/<role-def-id>" => [secret]
```

### Affected Resource(s)

`pulumi_azure.Provider`

### Output of `pulumi about`

```
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  aws           6.55.0
resource  azure         6.6.0
resource  azure-native  2.67.0
resource  github        6.3.2
language  python        3.137.0
resource  tls           5.0.8

Host     
OS       darwin
Version  15.0.1
Arch     arm64

This project is written in python: executable='/Users/Filip.Zyzniewski/Library/Caches/pypoetry/virtualenvs/infra-78jFhTa2-py3.12/bin/python' version='3.12.4'

[...]
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @filip-taxamo thanks for getting in touch. This is by-design out of an abundance of caution to avoid accidental sharing of subscription ids which could theoretically be of value to an attacker.

If you want to avoid propegating the secretness of this value into other resources, you can explicitly mark an output type as not secret by using the `unsecret` method ([python reference](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.Output.unsecret)).

**Comment by filip-taxamo** [comment]
@danielrbradley most of the resource attribute values could be of value to attackers - it does not seem like a good reason to obfuscate them this way.

Is there a reason why the Azure provider differs in design from other providers:

## AWS

- https://github.com/pulumi/pulumi-aws/blob/03de9a671213c78e16403ce7eac48dcfa2935794/sdk/python/pulumi_aws/provider.py#L727
- https://github.com/pulumi/pulumi-aws/blob/03de9a671213c78e16403ce7eac48dcfa2935794/sdk/python/pulumi_aws/provider.py#L742

## GCP

- https://github.com/pulumi/pulumi-gcp/blob/00e0f921da6642c37bda9afa72c95d07e5867467/sdk/python/pulumi_gcp/provider.py#L2588
- https://github.com/pulumi/pulumi-gcp/blob/00e0f921da6642c37bda9afa72c95d07e5867467/sdk/python/pulumi_gcp/provider.py#L2694

## Github

- https://github.com/pulumi/pulumi-github/blob/507b03570a7293780d8af6ec8a3c70135c54be85/sdk/python/pulumi_github/provider.py#L336

**Comment by filip-taxamo** [comment]
@danielrbradley actually, this approach does not seem to make sense at all.

It looks that each Azure resource exposes the subscription ID in its id property (which is not a secret), for example:

- `azure:authorization:UserAssignedIdentity`: id has a value of `/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity-name>`
- `azure:armmsi:FederatedIdentityCredential`: id has a value of `/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity-name>/federatedIdentityCredentials/<credentials-name>`
- `azure:authorization:Assignment`: id has a value of `/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Authorization/roleAssignments/<assignment-id>`

Why is the subscription ID considered sensitive as `pulumi_azure.Provider().subscription_id` but not in `pulumi_azure.authorization.UserAssignedIdentity().id`, `pulumi_azure.armmsi.FederatedIdentityCredential().id` or `pulumi_azure.authorization.Assignment().id`?
