### ISSUE TITLE
Static websites on Azure Blob Storage

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#260]
I want to make a sample of [Static website hosting in Azure Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website) on Pulumi, with CDN, custom domain, etc.

However, it turned out that [Terraform doesn't support this feature](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1903). And looks like it won't in the nearest future.

Apart from getting rid of terraform, my second-best idea is to use this case to illustrate how Pulumi could allow workarounds for missing features. 

[This comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1903#issuecomment-451248765) suggests a trick in terraform by calling out to `az` CLI. My other idea is to use an embedded ARM template similar to [this example](https://github.com/pulumi/examples/tree/master/azure-ts-arm-template).

What's the "official" guidance for this case? @lukehoban

**Comment by lukehoban** [comment]
For one-off missing things, using an embedded ARM template is probably best (assuming it’s supported in ARM).

Next best is using dynamic providers to wrap `az` CLI invocations.

**Comment by mikhailshilkov** [comment]
It appeared I was wrong and ARM doesn't support it either. Took a stab at implementing a dynamic provider, seems to work, see the PR above.

**Comment by mikhailshilkov** [comment]
An example is now available at https://github.com/pulumi/examples/tree/master/azure-ts-static-website
