### ISSUE TITLE
Replace HttpFunction example with more "official" support

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#261]
We have a fairly complex example in the pulumi/examples repo showing how to create a Function triggered by HTTP: https://github.com/pulumi/examples/tree/master/azure-ts-functions.

This is a helpful bit of functionality, but I (mistakenly) thought we had a `HttpFunction` in the Azure package itself that we could use (similar to the `CallbackFunction` we have in the AWS package).

Since most people are more interested in provisioning HTTP functions than seeing how to build a component for them, it would be good to add support in the package and then revise the example.

/cc @CyrusNajmabadi @mikhailshilkov

**Comment by mikhailshilkov** [comment]
@joeduffy Maybe have a look at https://github.com/pulumi/pulumi-azure/pull/255 while you are here, as that might change the API surface

**Comment by joeduffy** [comment]
Oh, perfect! That looks very nice! After merging, do you mind updating that https://github.com/pulumi/examples/tree/master/azure-ts-functions example to use the new types? This is going to be _very_ powerful and helpful to have :+1:

**Comment by CyrusNajmabadi** [comment]
> This is a helpful bit of functionality, but I (mistakenly) thought we had a HttpFunction in the Azure package itself that we could use (similar to the CallbackFunction we have in the AWS package).

We do.  We call it [HttpEventSubscription](https://github.com/pulumi/pulumi-azure/blob/884d6300f8134ec539c61e3a5a0488a32e246348/sdk/nodejs/appservice/zMixins_http.ts#L112).  Is that not sufficient for what you're trying to do here?

**Comment by CyrusNajmabadi** [comment]
Oh strange.  For some reason github didn't show the responses to the original post.  I see that @mikhailshilkov already gave this info :)

**Comment by mikhailshilkov** [comment]
Closed with https://github.com/pulumi/examples/pull/316
