### ISSUE TITLE
Hiding App Service behind a VNet

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#263]
One problem with Azure App Service has always been the fact that it's open to the internet. This is changing: Azure has a preview feature to [Integrate your app with an Azure Virtual Network](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet) in combination with [Access Restrictions](https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions) and [Service Endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview).

[This post](https://markheath.net/post/securing-backend-appservice-webapps) summarizes how to use this integration to isolate backend API from public access.

The feature is in preview, and the tooling is somewhat half-baked so far. There is a [How do we integrate the new vnet integration with ARM templates?](https://github.com/MicrosoftDocs/azure-docs/issues/20348) issue for ARM templates docs, but the feature [seems to work](https://github.com/ScottHolden/ARMExamples/blob/master/AppService-VnetNew-Storage/deploy.json).

Terraform still lags behind: [App Service VNET integration not working](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2254), [Problem with IP Restriction rules in azurerm_app_service resource](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2488). Therefore, Pulumi support is lacking too.

I'm creating this issue to track progress, as the case seems to be important for enterprisy Azure users.

**Comment by NoNameProvided** [comment]
Hi @viveklak! 

I see this landed in the next-gen version, this means this wont be backported to the current Azure provider?

**Comment by viveklak** [comment]
> Hi @viveklak!
> 
> I see this landed in the next-gen version, this means this wont be backported to the current Azure provider?

I believe complete support for this in the azure provider is currently still blocked behind https://github.com/terraform-providers/terraform-provider-azurerm/issues/2488. However, it is entirely possible for you to mix providers and use the nextgen provider to achieve this.
