### ISSUE TITLE
Namespace problem: azure.keyvault.Certifiate

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-azure#269]
Typo in the namespace - should be `azure.keyvault.Certificate`

**Comment by lukehoban** [comment]
Related https://github.com/pulumi/pulumi-azure/issues/97 and https://github.com/pulumi/pulumi-azure/issues/210.

**Comment by stack72** [comment]
Going to close this out as it's linked to #97 

We can track all of the work in that issue rather than have multiple issues tracking a similar issue
