### ISSUE TITLE
Improve the error message to help set the default location

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#278]
The following definition is perfectly valid (see #216):

``` ts
const rg = new azure.core.ResourceGroup("rg");
```

but it requires a config parameter `azure:location` to be set for the current stack. If the parameter is NOT set, the following error is shown to the user:

```
Diagnostics:
  azure:core:ResourceGroup (rg):
    error: azure:core/resourceGroup:ResourceGroup resource 'rg' has a problem: 
        "location": required field is not set
```

AWS provider is much more helpful in a similar case:

```
    error: 1 error occurred:
        * missing required configuration key "aws:region": 
            The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
    Set a value using the command `pulumi config set aws:region <value>`.
```

We should change the Azure provider to report a similar hint of setting a config value instead of suggesting the user's code is broken.

**Comment by stack72** [comment]
@mikhailshilkov now that your work has been merged into Pulumi-terraform, do we still have action here?

**Comment by mikhailshilkov** [comment]
Just tested it with the new version:

```
error: azure:core/resourceGroup:ResourceGroup resource 'resourceGroup' has a problem: Missing required property 'location'. Either
set it explicitly or configure it with 'pulumi config set azure:location <value>'.
```

The copy pasted command produces the valid configuration.
