### ISSUE TITLE
Stop using dataType=binary for queue-triggered subscriptions (functions)?

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#290]
Our `QueueEventSubscription` and `QueueFunction` use the binding which defines 

```
/**
 * How we want the message represented when passed into the callback. We specify 'binary'
 * so that all data is passed in as a buffer.  Otherwise, Azure will attempt to sniff
 * the content and convert it accordingly. This gives us a consistent way to know what
 * data will be passed into the function.
 */
dataType: "binary";
```

I think this might be a wrong configuration for several reasons:

1. [The official guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#trigger---configuration) doesn't mention `dataType`. I suspect we copied it from Blob Trigger where it is documented. However, it does work for queues too.

2. As a consequence of the configuration, we use `Buffer` as the input type for callbacks. That means that a message `{ "name": "John" }` needs to be deserialized in every callback: `JSON.parse(buffer.toString())`. While `Buffer` may be okay as an advanced option, I estimate that most people just send JSON or strings over the wire, so their life gets a bit more complicated.

3. Azure Functions have a feature called input bindings. I'm working on supporting it in #289. An example could look like this:

    ``` ts
    queue1.onEvent("NewMessage",  {
        inputOutputs: [
            rolesTable.input("tableIn", { filter: "Name eq '{name}'"})
        ],
        callback: async (context, person, roles: any[]) => {
            // roles contains data from the table storage looked up by name
        },
    });
    ```

    Note how the input binding data lookup is bound to the `name` property of the incoming message. This works if the data type is not binary (i.e. `person` is just a JS object). The whole input binding expression feature doesn't work for `dataType: binary`.

4. `dataType: binary` doesn't seem to work for the output binding, so it's actually hard to *send* a `Buffer`. (I'd need to try again if we want to be 100% sure)

5. Our implementation of Service Bus queues, topics, and Event Hubs doesn't use `binary`.

We could just remove `dataType: binary` from the queue triggers. Obviously, that's a breaking change. 

Instead, we could introduce an option to configure it. Do we have to leave it as default (which might complicate life before people discover it)? What do we do with `Buffer` type currently used everywhere? Replace it with `any`?

@CyrusNajmabadi thoughts?

**Comment by CyrusNajmabadi** [comment]
> Replace it with any?

We could make it generic.  So users can provide the shape they want.  One thing that's not clear ot me: if we remove this `dataType: "binary"`, what happens with different types of data?  If someone pushes a string, do you get a string?  If someone pushes an object, what do you get? 

Thanks!

**Comment by mikhailshilkov** [comment]
@CyrusNajmabadi Docs say (and I double-checked):

>  If the payload is JSON, it's deserialized into an object.

So, a message `blabla` will be passed as a string, while a message `{ "name": "jack" }` will become an object `{ name: "Jack" }`.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  In that case, i would simply make it `any` and explain the semantics.  Users can then pass an appropriate callback with their type specified.  We could also consider adding: `onStringEvent` and `onBinaryEvent` to pass the right dataType and more strongly indicate the type of callback to provide (though i care less about this)

**Comment by mikhailshilkov** [comment]
Nice, thanks! Do you think we should change the default from binary to object/string? I'd say it totally makes sense but it's a breaking change...

**Comment by CyrusNajmabadi** [comment]
I'm ok with the break if we document it, and specify how to get back to the previous behavior.
