### ISSUE TITLE
Can not create an AKS Windows cluster

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-azure#296]
I hope this is the right place to report this, I've started playing with Pulumi recently, not sure yet how everything fits together.

-----------

I need to deploy an AKS cluster with windows nodes: https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#add-a-windows-server-node-pool

I tried to map the documentation to pulumi and created a cluster with this configuration:

```js
    agentPoolProfiles: [{
        name: "aksagentpool",
        count: 1,
        vmSize: "Standard_B2s",
        vnetSubnetId: aksSubnet.id,
        maxPods: 250,
        type: "VirtualMachineScaleSets"
    }, {
        name: "npwin",
        count: 1,
        vmSize: "Standard_B2s",
        osType: "Windows",
        vnetSubnetId: aksSubnet.id,
        maxPods: 250,
        type: "VirtualMachineScaleSets"
        
    }],
```

The ``az`` commands from the documentation are

```
PASSWORD_WIN="P@ssw0rd1234"

az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-count 1 \
    --enable-addons monitoring \
    --kubernetes-version 1.14.0 \
    --generate-ssh-keys \
    --windows-admin-password $PASSWORD_WIN \
    --windows-admin-username azureuser \
    --enable-vmss \
    --network-plugin azure
```

and 

```
az aks nodepool add \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --os-type Windows \
    --name npwin \
    --node-count 1 \
    --kubernetes-version 1.14.0
```

``pulumi up`` then fails with the following error:

```
 error: Plan apply failed: Error creating/updating Managed Kubernetes Cluster "###-###2299bcd0" (Resource Group "###-###-resourcegroup02959c56"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="OSType Windows is not supported for managed cluster." Target="agentPoolProfile.osType"
```

I found this maybe related issue in terraform: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3751

**Comment by 0x53A** [comment]
Also, i think I somehow need to set the eqivalent of:

```
    --windows-admin-password $PASSWORD_WIN \
    --windows-admin-username azureuser \
```

I could not find any properties named windows on the [``KubernetesClusterArgs`` interface](https://github.com/pulumi/pulumi-azure/blob/65b5942ee84d08161a451950755fb155fe86d9a0/sdk/nodejs/containerservice/kubernetesCluster.ts#L316)

**Comment by mikhailshilkov** [comment]
Yeah, it looks like you should watch for [this PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/3519) to land first...

**Comment by stack72** [comment]
Hi @0x53A 	

Thanks for the request here - as @mikhailshilkov has pointed out, this is something we need to wait for upstream. Rather than having 2 areas to track this, I am going to close this out and we can wait for upstream to merge

As soon as that is released, it will be added to Pulumi

Paul

**Comment by 0x53A** [comment]
Hi @stack72, the PR was merged a few hours ago.

How long does it usually take to make it's way to pulumi? Will I need to update the CLI, or just do a ``npm update``?

Thanks!

**Comment by stack72** [comment]
Hi @0x53A 

I am working on this release right now :)

Paul
