### ISSUE TITLE
NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation issue

### ISSUE THREAD

**Issue by dbilleci-lightstream** [pulumi/pulumi-azure#308]
Hi, I think there's an issue in here, but I'm having trouble spotting it.

First off, the docs seem wrong, and I think that may be because of TF.. those docs looked wrong also: https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/network/networkInterfaceApplicationGatewayBackendAddressPoolAssociation.ts#L100

TF version: https://www.terraform.io/docs/providers/azurerm/r/network_interface_application_gateway_backend_address_pool_association.html

Where does `azurerm_application_gateway_test.backendAddressPool.0.id` come from? The name as far as I can tell should be:

`network.backendAdddressPools[0].id`

This also happens to be right where my issue is.  I'm trying to create an association to an application gateway, and with this code it will get ready to deploy (no errors) but this obviously isn't correct, we want the backend pool ID of the gateway we created above, but it's a similar variable, no issues.

````
let nic_backend_association = new azure.network.NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation(nic_backend_association_name, {
    networkInterfaceId: vm_nic.id,
    ipConfigurationName: 'ipconfig',
    backendAddressPoolId: app_gateway.id
});
````

If I then try to use either of the syntaxes listed above to target the backend address pool ID properly, they don't work:

````
let nic_backend_association = new azure.network.NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation(nic_backend_association_name, {
    networkInterfaceId: vm_nic.id,
    ipConfigurationName: 'ipconfig',
    backendAddressPoolId: app_gateway.backendAddressPools[0].id
});
````
I get:
````
  azure:network:NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation (API-B-P-0-Stage-Cae-Assoc):
    error: azure:network/networkInterfaceApplicationGatewayBackendAddressPoolAssociation:NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation resource 'API-B-P-0-Stage-Cae-Assoc' has a problem: "backend_address_pool_id": required field is not set
````

but it's a valid output (at least I think) off of the same object where `app_gateway.id` worked, so why would one output (id) be empty and another not?

Trying what's shown in the docs (`.backendAddressPool.0.id`) just throws a typescript error, not even valid syntax with these models.

The gateway variable `app_gateway` was created with a backend address pool, and when printing out that item (console.log) I get this, and the auto complete works.. so where is it?

````
    OutputImpl {
      __pulumiOutput: true,
      isKnown: Promise { <pending> },
      isSecret: Promise { <pending> },
      resources: [Function],
      promise: [Function],
      toString: [Function],
      toJSON: [Function],
      apply: [Function],
      get: [Function] }
````

Thanks!  Sorry for the fuzzy details, I've been trying to track this down for a while now today.. still a bit puzzled.

**Comment by mikhailshilkov** [comment]
Thank you for reporting this issue. Your usage of `app_gateway.backendAddressPools[0].id` is correct. However, it fails during the preview.

I believe this is another manifestation of https://github.com/pulumi/pulumi/issues/2433. This causes `undefined` instead of `Unknown` to get passed through, which then gets erased at the marshaling boundary.

The good news is that it only affects the preview stage at the point when the `ApplicationGateway` resource doesn't exist yet. Therefore, you have a couple of workarounds:

1. Do `pulumi up --skip-preview` on the first deployment. This issue only affects when a preview is done before any updates have been done, so will not occur on future pulumi ups.

2. Add a default value in the assignment:
    `backendAddressPoolId: network.backendAddressPools[0].id.apply(id => id || "/subscriptions/11111111-1111-1111-1111-11111111111/resourceGroups/a/providers/Microsoft.Network/applicationGateways/b/backendAddressPools/c"),`
     This default shouldn't be needed (that's the bug here), but will only be seen on the first-ever preview before any deployment has completed. Note that you have to mimic the shape of the ID, but dummy values are fine.

The example is indeed wrong. I wasn't able to find an existing issue for that, so I created https://github.com/pulumi/pulumi-terraform/issues/413

**Comment by mikhailshilkov** [comment]
@dbilleci-lightstream Were you able to proceed with the workarounds I described above?

**Comment by dbilleci-lightstream** [comment]
Hi Mikhail, yes - I went with option #2 (the dummy address) and was able to proceed.

**Comment by mikhailshilkov** [comment]
Thanks for confirming! I'll close this issue as we can track the proper fix in the mentioned upstream issues.
