### ISSUE TITLE
Travis tests failing

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-azure#332]
We've seen a couple of Travis test runs in master fail with errors like the below (though different tests each time, and seemingly not 100% of the time?)

```
[ re/examples/multi-callback-all ]     pulumi:pulumi:Stack azure-multi-callback-all-p-it-travis-job-multi-call-df20f526 **failed** 17 errors; 17 messages
[ re/examples/multi-callback-all ]  
[ re/examples/multi-callback-all ] Diagnostics:
[ re/examples/multi-callback-all ]   pulumi:pulumi:Stack (azure-multi-callback-all-p-it-travis-job-multi-call-df20f526):
[ re/examples/multi-callback-all ]     error: Running program '/tmp/p-it-travis-job-multi-call-df20f526-827200631' failed with an unhandled exception:
[ re/examples/multi-callback-all ]     Error: ENOENT: no such file or directory, lstat '/opt/pulumi/node_modules/@pulumi/azure/node_modules/@azure/functions/node_modules'
```

**Comment by mikhailshilkov** [comment]
Based on the detailed logs of [build 1508](https://travis-ci.com/pulumi/pulumi-azure/builds/122752557), the error looks very weird. Basically, `update-initial` step succeeds, `pulumi-preview-empty` succeeds too, but `update-empty` fails with missing `node_modules` error.

I'm not able to inspect the detailed logs of other builds as I don't have access to the S3 bucket...

**Comment by stack72** [comment]
This can be closed out - @mikhailshilkov was able to identify the last of the legitimate issues in master that we have. We have some transient failures in our builds right now

We have a green master as we speak https://travis-ci.com/pulumi/pulumi-azure/builds/124605861

**Comment by mikhailshilkov** [comment]
The ENOENT error is back https://travis-ci.com/pulumi/pulumi-azure/builds/124666145

**Comment by stack72** [comment]
Ok, I really do believe we got them all this time - going to close this out and we can reopen if they come back :D
