### ISSUE TITLE
Add support for Azure Maps

### ISSUE THREAD

**Issue by xtellurian** [pulumi/pulumi-azure#346]
Azure Maps is supported in Terraform, but not yet in Pulumi.

https://www.terraform.io/docs/providers/azurerm/r/maps_account.html

It would be great for me to have support for Azure Maps, because I'm currently using an ARM template. However, the ARM template doesn't provide the subscription key for the resource.

Thanks :)

**Comment by mikhailshilkov** [comment]
Hi @xtellurian, `azure.maps.Account` has been added in the version `1.0.0-rc.1` which is currently in process of releasing. You'll be able to use it very soon. I hope you find it useful!
