### ISSUE TITLE
EventGridCallbackSubscription sometimes fails (which fails the build)

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#353]
Some builds ([example](https://travis-ci.com/pulumi/pulumi-azure/builds/125850614#L4100)) fail with the following error:

```
Plan apply failed: Error waiting for EventGrid Event Subscription "ondeletedblob2442c348" 
(Scope "/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/eveentgrid-rg93db5886/providers/Microsoft.Storage/storageAccounts/eventgridsa86ade982") 
to become available: Code="Url validation" Message="The attempt to validate the provided
endpoint https://ondeletedblobc7d743dd.azurewebsites.net/runtime/webhooks/eventgrid failed.
For more details, visit https://aka.ms/esvalidation."
```

This comes from our EventGrid mix-ins where [we set the URL of an Event Grid subscription to point to the Function App](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/eventgrid/zMixins.ts#L134-L140).

There is no exact HTTP error in the log that the subscription gets. Most probably, the Function App isn't ready yet so it returns some sort of error which Event Grid interprets as failed validation.

A deep fix would involve either a change in Function Apps, or retries built into the subscription provisioning. I don't think this can be easily done in Terraform, probably it's somewhere further upstream.

We could probably add a validation of the Function App endpoint in our own code. Is there a way to wrap the [`url`](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/eventgrid/zMixins.ts#L134) output into another output which would wait until this URL returns a `200`?

**Comment by lukehoban** [comment]
> Is there a way to wrap the url output into another output which would wait until this URL returns a 200?

You could do something along the lines of this: https://gist.github.com/lukehoban/fd0355ed5b82386bd89c0ffe2a3c916a
