### ISSUE TITLE
Question - is using *FunctionApp with existing resources possible?

### ISSUE THREAD

**Issue by johlrich** [pulumi/pulumi-azure#358]
My question is specifically about ArchiveFunctionApp and cousins, but it can apply almost anywhere where a component's args takes another component as input with typescript. 

Given something like the following:

```ts
  const externalResourceGroup = azure.core.getResourceGroup({
    name: "some-existing-rg"
  })

  const azfn = new azure.appservice.ArchiveFunctionApp("appazfn", {
    resourceGroup: externalResourceGroup,
    archive: new pulumi.asset.FileArchive("../dist/app/FunctionApp/0.1.0-alpha.0.zip"),
  })
```

TypeScript will fail this with the message: `Type 'Promise<GetResourceGroupResult> & GetResourceGroupResult' is not assignable to type 'ResourceGroup | undefined'.
  Type 'Promise<GetResourceGroupResult> & GetResourceGroupResult' is missing the following properties from type 'ResourceGroup': urn, getProviderts(2322)`

Is it possible to use the higher level components with existing resources or to somehow get the same type as the created component in a downstream stack? Thanks

**Comment by pgavlin** [comment]
In place of `azure.core.getResourceGroup`, I think you can use `azure.core.ResourceGroup.get`. It's unfortunate, but the former returns different information than the latter due to differences in the underlying Terraform APIs.

```typescript
  const externalResourceGroup = azure.core.ResourceGroup.get("some-existing-rg", "some-existing-rg")

  const azfn = new azure.appservice.ArchiveFunctionApp("appazfn", {
    resourceGroup: externalResourceGroup,
    archive: new pulumi.asset.FileArchive("../dist/app/FunctionApp/0.1.0-alpha.0.zip"),
  })
```

**Comment by johlrich** [comment]
Oh I had not come across these resource based gets, thanks. This worked with the 2nd parameter being the azure resource id.

Thanks again for the quick response!
