### ISSUE TITLE
ResourceGroupNotFound build error

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#373]
This error happens more and more often during builds. [This one](https://travis-ci.com/pulumi/pulumi-azure/jobs/238679489) already has three of them. 

Example:
```
azure:appservice:FunctionApp greeting creating error: Plan apply failed:
 web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=404 
-- Original Error: Code="ResourceGroupNotFound" Message="Resource group 
'resourcegroup89380a4c' could not be found."
```

At the same time, I haven't seen this error even once on my local environment.
Needs to be investigated to improve build stability.

**Comment by lukehoban** [comment]
Build flakiness has been holding up getting a release of this provider out.  We should work around this as needed to get a release out based on local validation if necessary.  We did also get one green run in `master` yesterday: https://travis-ci.com/pulumi/pulumi-azure/builds/130339263

**Comment by mikhailshilkov** [comment]
I opened a support ticket with Microsoft, went through the initial ping-pong, and now it (hopefully) sits with engineering support. Let's see how it goes. Ticket # 119100222002086
I haven't found any workarounds yet. I'm okay to release based on a single green build.

**Comment by lukehoban** [comment]
Any new insights on this from Azure support?  

Should we try running tests in a different region? (I recall they suggested this issue only affected some regions?)

If Azure really is deeply unreliable here, is there an upstream issue we need to open to harden against that throughout the Azure provider?

Anything else we can do to mitigate in the meantime?

**Comment by mikhailshilkov** [comment]
> Any new insights on this from Azure support?

I got another response today and it's still no help, something in line with "have you tried to retry in the portal". I've sent an email to Azure RM PM, maybe they can escalate.

> Should we try running tests in a different region? (I recall they suggested this issue only affected some regions?)

They said there are issues in replicating between regions, which shouldn't immediately cause our error, as we don't have multi-region deploys. They ignored my follow-up question about which other regions we should try. I remember @stack72 switched us from `WestUS2` to `WestUS` with no improvement.

> If Azure really is deeply unreliable here, is there an upstream issue we need to open to harden against that throughout the Azure provider?

The problem is that I failed to repro this error anywhere outside our CI pipeline. If we could repro with pure Terraform, we could open an upstream issue...

> Anything else we can do to mitigate in the meantime?

Do we have any spot in our code to transparently retry resource creation if a specific error occurred?

**Comment by mikhailshilkov** [comment]
Okay, so I chatted with an actual Azure engineer, and the picture is a bit more clear.

Basically, they have an issue when the replication of ARM data lags behind. Especially cross-region. If we hit an API endpoint in region A to create a resource group in region B, and then ask for a resource in that resource group in region B, it may be the case that regin B doesn't know about the resource group yet.

The options are a) retry b) hit the management endpoint in the same region where our resource group exists.

Terraform uses a global endpoint `management.azure.com` which is performance-routed to the nearest region to our current Travis build server. A couple of runs showed two endpoints hit: `northcentralus` most of the time and `canadaeast` once.

Moving the build to `northcentralus` yielded two green builds but the third one failed with one `404` again.

We can permanently change the build location to `northcentralus`, or parse nslookup results for the current region, and see if stats improve. But adding retries seems the only reliable solution on our end.

**Comment by lukehoban** [comment]
Fascinating. It seems deeply weird that Azure doesn't use the region you are asking to create a resource in to process creation of that resource - and lets some other (effectively random) region nearer to where you are making the request try to handle it (even though that region might be "wrong").

I'm surprised this doesn't impact others trying to do automated testing against Azure.  I wonder if somehow Travis is just particularly prone to triggering these cross-region issues?

One proper fix would be to try to override the management endpoints to force them to a specific region - for example `westus2.management.azure.com` instead of `management.azure.com`.  It does not appear that the upstream Terraform provider currently supports this - but it looks like it would be reasonably easy to add.

> Moving the build to northcentralus yielded two green builds but the third one failed with one 404 again.

Sounds like we should at least do this for now.  

> But adding retries seems the only reliable solution on our end.

This would need to be done fairly deep in either the upstream Terraform Azure provider or in the Azure SDKs.

**Comment by mikhailshilkov** [comment]
> One proper fix would be to try to override the management endpoints to force them to a specific region - for example westus2.management.azure.com instead of management.azure.com

Yes, I forgot to mention this, thank you! My doubt is how to pull this to Terraform? Do you have an angle for a suggestion in Terraform that would make them merge such a change? It sounds bizarre without the whole story, and I don't have a repro with TF.

**Comment by lukehoban** [comment]
Another workaround for this is to modify the `hosts` file on the test machines to force redirect `management.azure.com` to the regional endpoint that matches the region resources are being created in (`ARM_LOCATION` for our tests).

PR which takes that approach here: https://github.com/pulumi/pulumi-azure/pull/395.

This is an unfortunate answer - but looks like it may alleviate our testing pain.

**Comment by mikhailshilkov** [comment]
Suddenly, Azure support came back to me saying that the issue is fixed, with not much details:

>As per your request, we have verified with the Backend team and they have advised us that the process in resolving the verbatim is internal. Unfortunately Microsoft does not encloses the procedures as per the process.
>The Backend (ARM) team has detected the cause within their own monitoring and took corrective action, This particular issue was related to a Bug and the mitigation was to roll out a bug fix that was causing resource replication delays and the bug itself was related to an internal dependency.

Do we dare to try reverting the hack?
