### ISSUE TITLE
Unable to disable subscription for azure.apimanagement.Api

### ISSUE THREAD

**Issue by johlrich** [pulumi/pulumi-azure#381]
Leaving off the `subscriptionKeyParameterNames` or explicitly setting it to undefined creates the Api with the subscription enabled with default header / query parameter names.

I am unsure how this resource behaves with just the terraform provider.

**Comment by johlrich** [comment]
While looking into a workaround and I'd guess this is just a case of a missing property in the upstream tf provider

The CreateOrUpdate azurerm body shows a `subscriptionRequired` boolean in addition to the `subscriptionKeyParameterNames` on the azurerm apis https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apis/createorupdate#request-body

The terraform list of parameters only seems to have `subscriptionKeyParameterNames` https://www.terraform.io/docs/providers/azurerm/r/api_management_api.html#argument-reference

**Comment by mikhailshilkov** [comment]
@johlrich  Thanks for checking this!
I believe this is https://github.com/terraform-providers/terraform-provider-azurerm/issues/3863 upstream

**Comment by brunhil** [comment]
This actually referenced in [PR 4885](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4885), please [see my comments](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4885#issuecomment-556181462) for why this can't be implemented just yet.

**Comment by baoduy** [comment]
If you link your API to a Product that is not require API key, you can all you API without key.
```typescript
 const product = new azure.apimanagement.Product(name, {
    resourceGroupName: apimInfo.group,
    apiManagementName: apimInfo.name,
    productId: name,
    displayName: displayName || name,
    published: true,
    subscriptionRequired:false,
    approvalRequired: false
  });
```

**Comment by Gerrit-K** [comment]
Meanwhile this has been fixed in upstream a couple of weeks ago. @mikhailshilkov I'm not familiar with the pulumi release / update cycle, but could you maybe reassess this? Thanks!

**Comment by mikhailshilkov** [comment]
@Gerrit-K We updated to that upstream version in our version `3.11`. Should we close this issue?

**Comment by Gerrit-K** [comment]
@mikhailshilkov sorry for that, apparently my IDE didn't refresh after I updated the npm package. I can confirm that it works now, so I'd agree on closing this.
