### ISSUE TITLE
AKS: after a pulumi refresh it wants to replace the cluster

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-azure#393]
I created an AKS cluster. Then I ran ``pulumi refresh``.

Now on the next ``pulumi up`` it wants to replace the whole cluster: 

```
 +-  ├─ azure:containerservice:KubernetesCluster                                   psd-mes-aks                                                                                         replace     [diff: ~agentPoolProfiles]
```

but when I look at the diff, there aren't any actual changes. In the output, both agentPoolProfiles are exactly the same.

This is the agentPoolProfiles in my script

```js
    agentPoolProfiles: [{
        name: "aksagentpool",
        count: 1,
        vmSize: "Standard_B2s",
        vnetSubnetId: aksSubnet.id,
        maxPods: 250,
        type: "VirtualMachineScaleSets"
    },
    ],

**Comment by stack72** [comment]
Hi @0x53A 

Please can you get the details view that shows what needs to change and post it here (minus any secrets!)

Paul

**Comment by 0x53A** [comment]
oops, I had created a second Windows NodePool in the Portal manually (because Pulumi / TerraForm don't yet support that) and promptly forgot about it. Sorry about that, I'll go home.

Is there a way to tell the diff engine to ignore this?

(for reference, these are the blockers for windows node pool support afaik: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3971
https://github.com/terraform-providers/terraform-provider-azurerm/issues/4001
)

**Comment by lukehoban** [comment]
> Is there a way to tell the diff engine to ignore this?

Yes - you can use `ignoreChanges`: https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges
