### ISSUE TITLE
Azure Maps 'skuName' property has incorrect options 

### ISSUE THREAD

**Issue by xtellurian** [pulumi/pulumi-azure#396]
I'm using Pulumi TypeScript, v1.3.4

> Resource: Azure Maps Account `azure.maps.Account`

There is a mismatch between the skuName returned by Azure and the skuName allowed by Pulumi - this is causing unnecessary updates to be performed.

## Steps to Reproduce:

Create a new azure maps resource:

```ts
const maps = new azure.maps.Account("maps", {
            resourceGroupName: rg.name,
            skuName: "s0",
        });
```

Run `pulumi up` - this should work, and the maps account should now exist.

Run `pulumi up` again, and the maps account will be updated:

```
azure:maps:Account        maps               replace     [diff: ~skuName]
```

Drilling into the diff:

```
~ skuName: "S0" => "s0"
```

Attempting to fix the skuName results in the following error:

```
azure:maps/account:Account resource 'maps' has a problem: expected sku_name to be one of [s0 s1], got S0
```

**Comment by xtellurian** [comment]
This might be an issue with the Terraform provider

https://www.terraform.io/docs/providers/azurerm/r/maps_account.html#sku_name

**Comment by mikhailshilkov** [comment]
Created an issue upstream, let's track it there: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4706
