### ISSUE TITLE
CustomHostnameBinding support import Cert from Keyvault

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azure#401]
Hi Pulumi,
CustomHostnameBinding is supporting to set up the SSL thumbprint. Howver, there is no option to import the cert from Keyvault (or upload cert from file) available yet. Hope this will be soon available.

Thanks
Duy

**Comment by mikhailshilkov** [comment]
Hi Duy,

Why is it not possible? I would expect something along these lines to work:

```ts
const cert = new azure.keyvault.Certifiate("cert", {
    //...
});

const binding = new azure.appservice.CustomHostnameBinding("binding", {
    //...
    thumbprint: cert.thumbprint
});
```

**Comment by baoduy** [comment]
Hi @mikhailshilkov 
I have tried and got cert not found error. Seems the CustomHostnameBinding is not looking up the cert from KeyVault.

**Comment by Wema** [comment]
Hi @baoduy,
I ran into the same problem and managed to resolve this by following the advise [here](https://www.terraform.io/docs/providers/azurerm/r/app_service_certificate.html#argument-reference)
I hope that helps.

**Comment by baoduy** [comment]
I would like to close this issue as I fond the way to import cert from the key vault to CustomHostnameBinding during deployment already.

**Comment by jrangel84** [comment]
Hi @baoduy,
How did you finally fix this? I'm getting not found on CustomHostnameBinding .
I added  'Secret -> get' and 'Certificate -> get' permissions on the Key Vault containing the certificate.
Any suggestions?

Thanks
