### ISSUE TITLE
Calling GetClientConfig() fails

### ISSUE THREAD

**Issue by jchomarat** [pulumi/pulumi-azure#429]
Hello,

I am trying to call the following (as seen on a couple of samples)

`var clientConfig = await Pulumi.Azure.Core.Invokes.GetClientConfig());`

And each time I run pulumi up, I receive on that line an exception "Object reference not set to an instance of an object"

Basically I want to retrieve from the code basic information (tenantid, subscriptionid etc .. ) as I would do 

`[subscription().tenantId]`

in arm.

Maybe I am not using this the right way?

Thanks for your help

**Comment by mikhailshilkov** [comment]
Hi @jchomarat This is a bug that should be fixed by now.

Could you please update `Pulumi.Azure` to `1.6.0-preview` if you aren't there yet and try again?

Sorry for the inconvenience.

**Comment by jchomarat** [comment]
Yeap, *1.6.0-preview* fixes this issue.
Thanks @mikhailshilkov !
