### ISSUE TITLE
Add more Azure examples

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#43]
We have a dearth of Azure examples at the moment.  This doesn't accurately reflect the completeness of the provider and gives the impression it isn't ready for prime time.

Let's spend some time beefing up core examples around the "Colada" triad -- containers, serverless, and infrastructure -- especially once https://github.com/pulumi/pulumi-azure/issues/42 has landed.

**Comment by scottmckenzie** [comment]
Here is one more:
https://github.com/pulumi/examples/pull/91

**Comment by lukehoban** [comment]
We have three with one more in PR, and a few more planned in the near term.  Going to close this issue out and we'll track individual areas we'd like to add more.
