### ISSUE TITLE
Incorrect FunctionApp settings update

### ISSUE THREAD

**Issue by andreujuanc** [pulumi/pulumi-azure#432]
Hi, 

I just figured that when I deploy a function with appSettings, the `"FUNCTIONS_EXTENSION_VERSION"` entry value is being overridden by `~1` instead of the actual value of `~2` or not properly stored, most probably by azure, but I thought to post it here first.

This is what I have:

``` typescript
const app = new azure.appservice.FunctionApp(appName, {
    appServicePlanId: servicePlan.id,
    resourceGroupName: resourceGroup.name,
    name: appName,
    storageConnectionString: storageAccount.primaryConnectionString,
    appSettings: {
        "FUNCTIONS_EXTENSION_VERSION": "~2",
        "WEBSITE_NODE_DEFAULT_VERSION": "~10",
        "WEBSITE_RUN_FROM_ZIP": codeBlobUrl
    },
})
```

After this being deploy I see this in the configuration section of the app:
`        "FUNCTIONS_EXTENSION_VERSION": "~1"

I'll try to make a reproducible gist ASAP. 

:neutral_face:

**Comment by mikhailshilkov** [comment]
hi @andreujuanc 
It might be confusing but you should actually set `version: "~2",` for your `FunctionApp` instead. It defaults to `~1` and overrides your setting.

**Comment by andreujuanc** [comment]
I see, I went and check the code and found it. Thanks, but and I believe the code/docs should be modified to reflect the actual meaning. 
Currently I says:

> The runtime version associated with the Function App. Defaults to ~1.

It should say something like "it's value is saved on FUNCTIONS_EXTENSION_VERSION", or something similar.
Additionally, we could verify that if version != FUNCTIONS_EXTENSION_VERSION , we can throw an error :)

**Comment by mikhailshilkov** [comment]
Agreed. This is a Terraform component, so there isn't much we can do directly. Any reason why you aren't using `ArchiveFunctionApp` which we control?

**Comment by andreujuanc** [comment]
Initially the App was adopted, so we wanted to test that out, and zip deploy was a good idea not to have additional deployment steps.
Also the example for zipdeploy was using FunctionApp so we figured it was the "way to go".

Using version fixed the issue. So we might just leave it like that, but I still have A TON of functions to migrate to pulumi, this one was the first one for this customer. 

Ill give it a try with ArchiveFunctionApp for the next iteration :)

**Comment by mikhailshilkov** [comment]
Sounds great! Closing this issue for now, feel free to share more feedback in another issue or otherwise
