### ISSUE TITLE
Does not Delete NIC when replacing a VirtualMachine

### ISSUE THREAD

**Issue by jestrjk** [pulumi/pulumi-azure#441]
Maybe related to #440 ?

When changing the hostname of a virtual machine: `azure.compute.VirtualMachine`, the attempt to replace it results in:
```
error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- 
Original Error: Code="NicInUse" Message="Network Interface server-nic159a15ce is used by existing resource /subscriptions/1980e26b-ac5d-4145-9f2e-22243071cc08/resourceGroups/server-rg7f560b7b/providers/Microsoft.Compute/virtualMachines/server-vm5da1da8e. 
In order to delete the network interface, it must be dissociated from the resource. To learn more, see aka.ms/deletenic." Details=[]
```

**Comment by mikhailshilkov** [comment]
Does the error come from the `VirtualMachine` resource, or rather from the `NetworkInterface`?

The issue sounds somewhat similar to #365, although the error is different. My guess is that you should be able to work around this with some combination of `dependsOn` and `deleteBeforeReplace` options.

If you share a repro and console output, I can give a more specific answer. Thanks!

**Comment by PierreBeucher** [comment]
Had the same issue because I had a VM associated to a Network Interface and Azure refused to create a new VM with the same Network Interface (seems fair). Using `deleteBeforeReplace` on VM fixes the issue:

```javascript
const networkInterface = new azure.network.NetworkInterface(`networkInterface`, {
    // ...
    });

new azure.compute.LinuxVirtualMachine(`virtualMachine-${num}`, {
      // ...
      networkInterfaceIds: [networkInterface.id],
      // ...
    }, {
      deleteBeforeReplace: true
    });
```
