### ISSUE TITLE
NetworkWatcherFlowLog not available in v1.8.1

### ISSUE THREAD

**Issue by dokuboyejo** [pulumi/pulumi-azure#445]
The NetworkWatcherFlowLog module is currently not available in the parent module pulumi_azure.network.

**language**: python

**Comment by stack72** [comment]
Hi @dokuboyejo 

This was only added as part of pulumi-azure v1.10.0

Paul

**Comment by dokuboyejo** [comment]
Hi @stack72 
Is v1.10.0 publicly available yet?

**Comment by stack72** [comment]
@dokuboyejo yessir

https://pypi.org/project/pulumi-azure/#history

The latest version is v1.11.0

P.

**Comment by dokuboyejo** [comment]
many hanks @stack72

**Comment by stack72** [comment]
no worries! Let us know if there are any issues
