### ISSUE TITLE
Allow CloudEvents v1 in `azure.eventgrid.EventSubscription#eventDeliverySchema`

### ISSUE THREAD

**Issue by bsideup** [pulumi/pulumi-azure#446]
Hi!

Cloud Events v1 is out and supported by EventGrid.

But, since the validation seems to happen before hitting the Azure's API, there is currently no way to use it. Currently it says: `Possible values include: 'EventGridSchema', 'CloudEventV01Schema', 'CustomInputSchema'.`, which is not entirely true :)

**Comment by stack72** [comment]
Hi @bsideup 

I am not sure what error you are getting here. If you want to use the new CloudEvents v1 delivery schema, then then you just need to use the parameter as `CloudEventV01Schema`

is this not working for you?

Paul

**Comment by bsideup** [comment]
Hi @stack72,

`CloudEventV01Schema` will use version `0.1` and not `1.0`. I can confirm that after creating the resource, it is also displayed as `0.1` in the UI and the events are sent in `0.1` format.

**Comment by stack72** [comment]
Hi @stack72 

I am working on #573 which will fix this.

I can see this in the upstream provider:

```
			"event_delivery_schema": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
				Default:  string(eventgrid.EventGridSchema),
				ValidateFunc: validation.StringInSlice([]string{
					string(eventgrid.EventGridSchema),
					string(eventgrid.CloudEventSchemaV10),
					string(eventgrid.CustomInputSchema),
				}, false),
			},
```
