### ISSUE TITLE
Create Key Vault Linked Service in Data Factory

### ISSUE THREAD

**Issue by joshusdaog** [pulumi/pulumi-azure#447]
It doesn't appear that Pulumi (or Terraform for that matter) supports provisioning Key Vault Linked Services--other than through ARM template deployment. 

A best practice for Data Factory is to access tokens & connection strings required for Linked Services via Key Vault. Doing this requires a Key Vault Linked Service (among other things like a managed identity for Data Factory and a Key Vault access policy). It would be beneficial to provision a skeleton Data Factory instance with a Key Vault Linked Service.

**Comment by mikhailshilkov** [comment]
@joshusdaog Could you please add some description to the issue?

**Comment by stack72** [comment]
We've not heard back on this in approx 1 month so I am going to close this out. If you have any more information @joshusdaog then please let us know and we can reopen it
