### ISSUE TITLE
Property scopes of azure.network.MetricAlert should be a list of string

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure#449]
Hello,

Affecting current azure version (v1.11.0).

Regarding the [terraform  example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/monitor_metric_alert.html.markdown)
```
resource "azurerm_monitor_metric_alert" "example" {
  name                = "example-metricalert"
  resource_group_name = "${azurerm_resource_group.main.name}"
  scopes              = ["${azurerm_storage_account.to_monitor.id}"]
```

the [`scopes` property of `azure.network.MetricAlert`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/monitoring/#MetricAlertArgs-scopes) should be a `list of string`. Currently, it's a simple `string`.

**Comment by stack72** [comment]
Hi @boillodmanuel 

I am not sure what issue you are hitting here. I am looking at 

azure.monitoring.MetricAlert and scopes is currently a List of string

Is this still a problem for you?

Paul

**Comment by boillodmanuel** [comment]
In the documentation (as well as in the code), the scope type is `scopes: pulumi.Input<string>;` which is not a List but a single string.

**Comment by stack72** [comment]
Hi @boillodmanuel 

So we've had a look at this and we *think* that Pulumi is correct here. The Terraform code looks as follows:

```
"scopes": {
				Type:     schema.TypeSet,
				Required: true,
				MinItems: 1,
				MaxItems: 1,
				Elem: &schema.Schema{
					Type:         schema.TypeString,
					ValidateFunc: azure.ValidateResourceID,
				},
				Set: schema.HashString,
			},
```

This is a required Set of Strings with a max 1 and a min of 1 - so that essentially is a string - Set itself doesn't really suit the parameter here

In the Terraform codebase I see the following comment:

```
// TODO: Multiple resource IDs (Remove MaxItems) support is missing in SDK
// Issue to track: https://github.com/Azure/azure-sdk-for-go/issues/2920
// But to prevent potential state migration in the future, let's stick to use Set now
```

Therefore, when Terraform changes, Pulumi will update as expected

Thoughts?

Paul

**Comment by boillodmanuel** [comment]
Okay, so you convert a Set of (1:1) in a single value. 
It's an implementation choice that I respect totally.
It could be surprising when we compare the pulumi and terraform schema (as I did).

For information, the terraform issue that follow that point: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3719

Feel free to close this issue.

Manuel

**Comment by stack72** [comment]
Hi @boillodmanuel 

I am going to close this specific issue out - the issue you linked is actually one of our developers so we will know when it gets addressed

When it does get addressed, then Pulumi will reflect the new change

If you feel differently, then we can reopen :) Sorry about the confusion here

Paul
