### ISSUE TITLE
Azure AccountStorage has an 'accountType' property which doesn't exist on terraform side

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure#456]
Hello,

Affecting current azure version (v1.11.0).

In the documentation  of AccountStorage, there is an 'accountType' property: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/storage/#AccountArgs-accountType

This property doesn't exist on terraform side: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/storage_account.html.markdown#argument-reference

**Comment by mikhailshilkov** [comment]
Thank you for reporting this.

The property [exists](https://github.com/terraform-providers/terraform-provider-azurerm/blob/3059f231d3d88b2501a19ebcf7c12692cd5e0e8c/azurerm/internal/services/storage/resource_arm_storage_account.go#L83) in Terraform, but it's been deprecated.

@stack72 What is our status of marking all the deprecated fields as such both in code and in docs? I can't see anything in [the code](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/storage/account.ts#L120) yet.

**Comment by stack72** [comment]
@mikhailshilkov the code is still waiting for a review... I think > 1 month now

**Comment by boillodmanuel** [comment]
Okay @mikhailshilkov. So no worry if the property exists in terraform code :)

**Comment by stack72** [comment]
ok @boillodmanuel 

Going to close this - the 2.0.0 TF provider has been released and we are going to  release this for Pulumi soon and that property will now disappear!
