### ISSUE TITLE
Missing support for CORS for Azure Function Apps

### ISSUE THREAD

**Issue by ChrisKlug** [pulumi/pulumi-azure#463]
I'm building a solution that needs CORS support for Azure function apps. Currently using MultiCallbackFunctionApp, but it doesn't seem to support adding CORS hosts. Would it be possible to add this feature? It seems like a pretty useful thing to support.

**Comment by thumbquat** [comment]
I have the same issue (I'm using ArchiveFunctionApp), siteConfig doesn't have a cors setting (at least for typescript, have not checked other bindings
