### ISSUE TITLE
Work with multiple azure subscriptions

### ISSUE THREAD

**Issue by Efp95** [pulumi/pulumi-azure#466]
Hi,

I'm about the need to create some resources in subscription A and also some other resources in subscription B
Is it possible to handle more than one subscription per stack?
Currently, I'm getting an error for attempting to access a resource from sub B while my account is set to use sub A

**Comment by lukehoban** [comment]
You can use `azure.Provider` to create a provider configured to talk to each account, and then loop over these providers deploying resources into each provider (or just deploy a few resources to each).

**Comment by Efp95** [comment]
Sounds good. I will give it a try. Thanks!

**Comment by stack72** [comment]
Hi @Efp95 

Just checking in here to see if there is anything further you need on this?

Thanks

Paul

**Comment by stack72** [comment]
Going to close this out as the OP hasn't responded in 21 days

@Efp95 if you need something more here - please let us know

**Comment by ChrisFulstow** [comment]
Perfect, the `azure.Provider` tip saved me some work.

To create a storage account in a another subscription:

```
const azProvider = new azure.Provider('otherSub', {
    subscriptionId: '<my-subscription-id>',
});

const rg = new ResourceGroup('my-rg', {
    name: 'my-rg',
    location: 'australiaeast',
}, { provider: azProvider });

new storage.Account('mysa', {
    resourceGroupName: rg.name,
    location: rg.location,
}, { provider: azProvider });
```

**Comment by PawelStadnicki** [comment]
> Perfect, the `azure.Provider` tip saved me some work.
> 
> To create a storage account in another subscription:
> 
> ```
> const azProvider = new azure.Provider('otherSub', {
>     subscriptionId: '<my-subscription-id>',
> });
> 
> const rg = new ResourceGroup('my-rg', {
>     name: 'my-rg',
>     location: 'australiaeast',
> }, { provider: azProvider });
> 
> new storage.Account('mysa', {
>     resourceGroupName: rg.name,
>     location: rg.location,
> }, { provider: azProvider });
> ```

Many thanks, it safe me a lot of time.
