### ISSUE TITLE
error: azure:storage/share:Share resource 'storageshare' has a problem: : invalid or unknown key: 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-azure#474]
After https://github.com/pulumi/pulumi-azure/pull/471 was merged, we're seeing Travis test failures in `master`.

**Comment by leezen** [comment]
Going to revert the change: https://github.com/pulumi/pulumi-azure/pull/475

**Comment by leezen** [comment]
Closed the revert. It appears that the tests themselves need to change as part of the Azure 2.0 change.

**Comment by mikhailshilkov** [comment]
The examples are adjusted and the build is green now
