### ISSUE TITLE
Enable Free Tier on CosmosDB

### ISSUE THREAD

**Issue by michaelmsm89** [pulumi/pulumi-azure#480]
CosmosDb now offers a free tier, where they give 400 RU/s and 5 GB of storage for free in an account. You can enable free tier on up to one account per subscription. Is it possible to enable this currently using the `azure.cosmosdb.Account` object in TypeScript?

I'm using
```
"@pulumi/pulumi": "1.12.0",
"@pulumi/azure": "1.14.0"
```

I've added the Azure ARM template below as reference to the `enableFreeTier` property.

```json
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "locationName": {
            "type": "string"
        },
        "defaultExperience": {
            "type": "string"
        },
        "isZoneRedundant": {
            "type": "string"
        }
    },
    "variables": {},
    "resources": [
        {
            "apiVersion": "2019-12-12",
            "kind": "GlobalDocumentDB",
            "type": "Microsoft.DocumentDb/databaseAccounts",
            "name": "[parameters('name')]",
            "location": "[parameters('location')]",
            "properties": {
                "databaseAccountOfferType": "Standard",
                "locations": [
                    {
                        "id": "[concat(parameters('name'), '-', parameters('location'))]",
                        "failoverPriority": 0,
                        "locationName": "[parameters('locationName')]"
                    }
                ],
                "enableMultipleWriteLocations": false,
                "isVirtualNetworkFilterEnabled": false,
                "virtualNetworkRules": [],
                "ipRangeFilter": "",
                "dependsOn": [],
                "capabilities": [],
                "enableFreeTier": true
            },
            "tags": {
                "defaultExperience": "[parameters('defaultExperience')]",
                "hidden-cosmos-mmspecial": "",
                "CosmosAccountType": "Non-Production"
            }
        }
    ],
    "outputs": {}
}
```

**Comment by leezen** [comment]
I see you opened a similar issue in the upstream provider https://github.com/pulumi/pulumi-azure/issues/480 -- we'll pick that change up once that happens

**Comment by michaelmsm89** [comment]
Hi @leezen, not sure I understand. I only opened the issue here, your issue link returns to this issue.

**Comment by leezen** [comment]
Sorry, I totally thought I had click through something on a search in the TF issues search (and I must've somehow misclicked something and ended up on this issue without realizing it). Sorry about that.

Your best bet is to have this change in the upstream provider https://github.com/terraform-providers/terraform-provider-azurerm and it'll get picked up in this repo.

**Comment by michaelmsm89** [comment]
Raised upstream at https://github.com/terraform-providers/terraform-provider-azurerm/issues/6030

**Comment by mikhailshilkov** [comment]
@michaelmsm89 Thanks for opening an upstream issue. We'll track it there and I'll close this issue here.
