### ISSUE TITLE
Recreate Azure Blob even if it already exists

### ISSUE THREAD

**Issue by Odonno** [pulumi/pulumi-azure#484]
There seems to be an issue with the `Blob` resource and I cannot find a way to make it work like I want.
Let suppose you want to store a static websites with some files: `index.html`, `main.ab123cd.chunk.js` and `main.ef.567gh.chunk.css`.

The first time, it will upload the files correctly. But if you generate a new bundle, you will get another files: `index.html`, `main.xy789z.chunk.js` and `main.c234ab.chunk.css`.

So, Pulumi will be smart enough to remove the previous chunked files but it won't replace the `index.html` file but it surely has been changed...

I try to use the `DeleteBeforeReplace` option in conjunction with a change in `Metadata` property but with no success. Example here:

```cs
var blob = new Blob(
    blobName,
    new BlobArgs
    {
        Name = blobName,
        StorageAccountName = frontendStorageAccount.Name,
        StorageContainerName = "$web",
        Type = "Block",
        Source = file,
        ContentType = contentType,
        Metadata = new Dictionary<string, string>
        {
             { "version", timestamp.ToString() }
        }
    },
    new CustomResourceOptions
    {
        DeleteBeforeReplace = true
    }
);
```

Even if the `Metadata` changed during each deployment, there is no replacement but just an update of the `Metadata` property.
Note that here I used a timestamp but I could also have used the file hash.

Another option would be to change the name of the resource. But if I do that, it will create and then delete the blobs, in that specific order. And it will obviously empty my storage account which is not what I ask...

I hope that there is a way to do what I want. Otherwise, I would suggest to add a `Hash` property in order to detect when to recreate or not the blob.

**Comment by mikhailshilkov** [comment]
With the latest 2.0 release, you should be able to write
```cs
Source = new FileAsset(file)
```

`FileAsset` will take care of noticing changes in the file and updating the resource. Do you mind giving this a try?

**Comment by Odonno** [comment]
@mikhailshilkov Oh, ok. I will try that.

**Comment by Odonno** [comment]
Well, I migrated to the latest release but now I got an error when creating Azure Storage Account:

```
Error reading static website for AzureRM Storage Account "frontendstorage5472f887": accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized to perform this operation using this permission.\nRequestId:21251404-401e-00c7-4b92-f7529d000000\nTime:2020-03-11T10:44:58.2186913Z"
```

I do nothing in particular on the storage account. I don't know where there is an error but it seems that the accounts are well created.

**Comment by simonwendel** [comment]
@Odonno I have just opened an issue #488 for that error. I can't create storage accounts either.

**Comment by Odonno** [comment]
Well, I was really full of hope to make my stuff work like a charm. But then this error came out...

I searched on the internet and it seems we are not the only. It looks like it is an error from terraform, maybe because we have the dependency to the wrong version of Terraform. I am not sure if I should blame Terraform but their versioning system is sometimes really a PINA, even without Pulumi.

I hope we could fix that soon.

**Comment by mikhailshilkov** [comment]
@Odonno You should be able to use `FileAsset` in 2.1 of the azure provider, please report back if you still face any issues

**Comment by Odonno** [comment]
Well, yes. Now, it works like magic!

Thank you very much.

![image](https://user-images.githubusercontent.com/6053067/76768983-1bf7b880-679c-11ea-9f2d-6c6d8367dbfa.png)
