### ISSUE TITLE
LinuxVirtualMachine et al. require customData to be base64-encoded

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#487]
The new OS-specific VM resources of 2.0 (`LinuxVirtualMachine`, `WindowsVirtualMachine`, `LinuxVirtualMachineScaleSet`, `WindowsVirtualMachineScaleSet`) require `customData` to be base-64 encoded ([TF def](https://github.com/terraform-providers/terraform-provider-azurerm/blob/029e4e0e6490c060184054fb55c6e3838eff3664/azurerm/internal/services/compute/linux_virtual_machine_resource.go#L136)). Otherwise, they fail at preview time:

```
error: azure:compute/linuxVirtualMachine:LinuxVirtualMachine resource 'server-vm' has 
a problem: expected "custom_data" to be a base64 string, got #!/bin/bash...
```

This code works:

``` ts
const vm = new azure.compute.LinuxVirtualMachine("server-vm", {
    resourceGroupName,
    networkInterfaceIds: [networkInterface.id],
    size: "Standard_A0",
    sourceImageReference: {
        publisher: "Canonical",
        offer: "UbuntuServer",
        sku: "16.04-LTS",
        version: "latest",
    },
    osDisk: {
        caching: "ReadWrite",
        storageAccountType: "Standard_LRS",
    },
    computerName: "hostname",
    adminUsername: username,
    adminPassword: password,
    disablePasswordAuthentication: false,
    customData: Buffer.from(`#!/bin/bash\n
echo "Hello, World!" > index.html
nohup python -m SimpleHTTPServer 80 &`).toString("base64"),
});
```

but ideally, we wouldn't require users to encode and would encode ourselves. Is this / should this be supported by the bridge?

**Comment by leezen** [comment]
An interesting point of comparison is `aws_instance` https://www.terraform.io/docs/providers/aws/r/instance.html which has both the `user_data` and `user_data_base64` fields. I wonder if it'd be better to include a new field, like `customDataUtf8` as a mixin, which provides the base64 encode/decode?

**Comment by mikhailshilkov** [comment]
@leezen In my ideal world, it would be one field that either accepts a string (and then it's UTF8), or a byte array/buffer (and then it's non-string data). However, we released this resource already :( so now we need to be more creative, and your suggestion makes sense in this reality.
