### ISSUE TITLE
Webhook classes are misspelled as "Webook"

### ISSUE THREAD

**Issue by kylehayes** [pulumi/pulumi-azure#492]
All related webhook classes seem to have a misspelling as "webook" for example: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/containerservice/#RegistryWebook

**Comment by stack72** [comment]
Hi @kylehayes 

I’m so sorry about this - I’ll have this fixed ASAP and try and make in next release

@stack72
