### ISSUE TITLE
Is it possible to override the resource name creation?

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi-azure#499]
The default in pulumi seems to be to create suffixes for all Azure resources eventhough those would not make anysense e.g. SQL Server Databases (those have only to be unique within a SQL Sever instance).

Is there a way to override this behaviour?

**Comment by mikhailshilkov** [comment]
@Rookian Yes, it's possible to specify an explicit physical name, see the docs here: https://www.pulumi.com/docs/intro/concepts/programming-model/#names
