### ISSUE TITLE
Import swagger-json (v3) to Api management

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azure#501]
When import swagger json file (v3). I got the below error.

```cmd
error: 1 error occurred:
Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Parsing error(s): The Swagger version specified is unknown.","target":"representation"}]       
```
Here is swagger sample
```json
{
   openapi: "3.0.1",
   info: {
      title: "API",
      description: "The API.",
}
```

However, I was imported successfully from the Azure Portal. Is it because Terreform is not supporting openapi 3.x document version yet?

**Comment by mikhailshilkov** [comment]
@baoduy I believe this is tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3203

**Comment by baoduy** [comment]
Thanks @mikhailshilkov, Hope terraform will support the openapi 3 soon. For workaround I'm using [this library](https://github.com/LucyBot-Inc/api-spec-converter) to convert to swagger 2 and imported to management successfully.

**Comment by mikhailshilkov** [comment]
Great to hear you could make progress there! As there isn't much we can do, I'll close the issue anf let's track on the terraform side.

**Comment by mastoj** [comment]
@mikhailshilkov I see the same issue with nextgen, is nextgen also using the terraform provider?

**Comment by mikhailshilkov** [comment]
@mastoj No, nextgen does not use the TF provider. It looks like the TF issue was fixed by upgrading to newer API versions?

**Comment by mastoj** [comment]
Ok, then I'll open an issue in the nextgen repo.
