### ISSUE TITLE
FunctionApp os_type in Python ignored

### ISSUE THREAD

**Issue by cecilphillip** [pulumi/pulumi-azure#502]
Setting the `os_type` property to linux still results in a Windows based function app
```python
appservice.FunctionApp("serverless-scheduler",
                       name="serverless-scheduler",
                       resource_group_name=resource_group.name,
                       app_service_plan_id=scheduler_plan.id,
                       https_only=True,
                       os_type="linux",  # doesn't work??                   
                       version="~3",
```

The resulting ARM template gets set to `"kind": "functionapp"` instead of `"kind": "functionapp,linux",`

**Comment by mikhailshilkov** [comment]
@cecilphillip I believe you need to set the app service plan to `reserved=true`. I agree this model is a bit weird.
Related: https://github.com/pulumi/examples/issues/610

**Comment by cecilphillip** [comment]
Thanks @mikhailshilkov that worked. Is this something that can get added to the Python doc strings? Alternatively, maybe setting `os_type="linux"` on `FunctionApp` could update the app service plan `reserved` property when the deployment is executed? 

Thoughts?

**Comment by mikhailshilkov** [comment]
@cecilphillip We use the terraform's azurerm provider to codegen the Pulumi provider SDKs, which gives us all the features of it (yay) but also bugs and shortcomings alike. We currently don't have a great way to augment aspects similar to what you describe.

Also, I think that terraform based their API on what ARM exposes: I believe `reserved: true` comes from ARM directly.

However, we can create higher-level components that combine multiple resources and expose easier-to-use API. In the node SDK, there is a component called `ArchiveFunctionApp` which creates storage components + plan + function app and does all the configuration, 100% under our control.

So, in the future, we can

- Expose higher-level components in all languages (working on the foundation for this right now)
- Explore a native Azure provider

For now, our best bet is investing in good examples.

**Comment by cecilphillip** [comment]
That makes sense. So it's probably better to derive and extend
