### ISSUE TITLE
How can we set the runtime of an Azure App Service?

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi-azure#508]
I would like to deploy an ASP.NET Core App to a Windows-based Azure App Service.
I would expect to find the configuration under `SiteConfig `but there I can only set up `DotnetFrameworkVersion`. When I serve my deployed app, I get an error 

> HTTP Error 500.32 - ANCM Failed to Load dll

**Comment by mikhailshilkov** [comment]
Hi @Rookian 
[This example](https://github.com/pulumi/examples/tree/master/azure-ts-appservice-devops) deploys an ASP.NET Core App to a Windows-based Azure App Service. I don't think you have to specify the .NET Core version in App Service settings. Could you try if that example works for you?

**Comment by Rookian** [comment]
I am doing basically the same as in your given example.

new AppService(GetResourceName("searchapi"), new AppServiceArgs
{
    Name = GetResourceName("searchapi"),
    ResourceGroupName = ResourceGroupName,
    Tags = GetTags(),
    AppServicePlanId = appServicePlan.Id,
    AppSettings =
    {
        { "ApplicationInsights:InstrumentationKey", insightsForSearchApi.InstrumentationKey },
        {"WEBSITE_RUN_FROM_PACKAGE", searchAPIBlobUrl},
    },
    HttpsOnly = true,
});

Have you any clue of how the WEBSITE_RUN_FROM_PACKAGE feature is working? 

What I understand is, is that it seems like that the app service is determining the runtime based on the deployed package. 

So I think my problem is how I use dotnet publish. Still investigating.

**Comment by mikhailshilkov** [comment]
"Run from package" means that you upload app binaries as a zip file in blob storage and then point the app service to it via a setting, see https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package#run-from-external-url-instead

**Comment by Rookian** [comment]
Got it to work :) The problem was in how I use dotnet publish. 

`dotnet publish -c Release -r win10-x64` --> does not work
dotnet publish -c Release --> works, contains a separate `runtimes` folder

The App Service itself still runs with `.NET` _stack_ and _.NET Framework version_ `4.7`. So it seems what you see in the Azure Portal does not matter.

**Comment by mikhailshilkov** [comment]
For reference, this is a corresponding issue in the TF provider: https://github.com/terraform-providers/terraform-provider-azurerm/issues/5350

The current workaround is to use `linuxFxVersion`, e.g.

```ts
siteConfig: {
    linuxFxVersion: "DOTNETCORE|3.1",
}
```
