### ISSUE TITLE
networkSecurityGroup Id missing in TS Provider

### ISSUE THREAD

**Issue by rafaribe** [pulumi/pulumi-azure#509]
Today I was trying to assign a Network Security Group to a Network Interface and I wasn't able to.
I've checked the corresponding[Terraform Provider ](https://www.terraform.io/docs/providers/azurerm/d/network_interface.html#network_security_group_id)but It seems that Pulumi is missing this in the [Azure Provider](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/network/networkInterface.ts)

**Comment by mikhailshilkov** [comment]
Hi @rafaribe 

Your terraform link is pointing to a data source, not a resource. The `network_interface` [resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html) doesn't have this field either. I think it existed but was deprecated.

I believe you should use a separate resource [`NetworkInterfaceSecurityGroupAssociation`](https://www.pulumi.com/docs/reference/pkg/azure/network/networkinterfacesecuritygroupassociation/).

**Comment by rafaribe** [comment]
Thank you very much @mikhailshilkov that resource indeed solves the problem.
