### ISSUE TITLE
Example for Blob Storage -> EventGrid -> Function

### ISSUE THREAD

**Issue by GeertVL** [pulumi/pulumi-azure#516]
Is it possible to add an example on how to create a EventGrid subscription between a blob storage and a function. Particularly on the BlobCreated event.

The trigger in the Azure function is an EventGrid trigger that received the EventGrid data so I can work with my function implementation on that?

Thank you!

**Comment by mikhailshilkov** [comment]
How about this one: https://www.pulumi.com/blog/ten-pearls-with-azure-functions-in-pulumi/#7-subscribe-to-azure-event-grid

**Comment by GeertVL** [comment]
Thank you @mikhailshilkov . How do you trigger an Azure Function EventGridTrigger instead of doing a context.log as in the example?

**Comment by mikhailshilkov** [comment]
Two lines with `context.log` *are* an Azure Function. This code is deployed as a Function App, read the post above.

If you want to trigger your custom function, you'd have to define a custom Event Grid Subscription to point to it, with key management etc. You may be able to extract this logic from https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/eventgrid/zMixins.ts#L132-L142

**Comment by GeertVL** [comment]
Thank you.

What needs to be the scope value and how do you "hook" it to the source Storage Account.

```
const subscription = new azure.eventgrid.EventSubscription('azfuneventsub', {
    webhookEndpoint: { url: liveUrl },
    eventDeliverySchema: "EventGridSchema",
    includedEventTypes: [ "BlobCreated" ],
    scope: "" 
});
```

**Comment by GeertVL** [comment]
Got it how to do it. Thank you for all your help @mikhailshilkov 

```
const metadataaccount = new azure.storage.Account("metadatastorage", {
    resourceGroupName: resourceGroup.name,
    accountTier: "Standard",
    accountReplicationType: "LRS",
});

const subscription = new azure.eventgrid.EventSubscription('azfuneventsub', {
    webhookEndpoint: { url: liveUrl },
    eventDeliverySchema: "EventGridSchema",
    includedEventTypes: [ "Microsoft.Storage.BlobCreated" ],
    scope: metadataaccount.id,
}, { parent: metadataaccount });
```
