### ISSUE TITLE
(Azure, .NET) Unable to add standalone subnet to virtual network if virtual network was create with subnet

### ISSUE THREAD

**Issue by OlegKarasik** [pulumi/pulumi-azure#525]
Here is a sequence of events:

1. Create a virtual network with a subnet

``` csharp
public MyStack()
{
  var resourceGroup = new ResourceGroup(
    "pulumi-vnet-issue", 
    new ResourceGroupArgs() { Location = "West Europe" });

    var virtualNetwork = new VirtualNetwork(
      "vnet",
      new VirtualNetworkArgs
      {
        AddressSpaces = "10.12.0.0/16",
        ResourceGroupName = resourceGroup.Name,
        Location = resourceGroup.Location,
        Subnets = new InputList<VirtualNetworkSubnetsArgs>()
        {
          new VirtualNetworkSubnetsArgs
          {
            AddressPrefix = "10.12.0.0/29",
            Name = "vnet-subnet"
          }
        }
      });
}
```

2. Do the following modifications:
    * Remove `Subnets` property from `VirtualNetworkArgs`
    * Initialize a standalone `Subnet` resource

``` csharp
public MyStack()
{
  var resourceGroup = new ResourceGroup(
    "pulumi-vnet-issue", 
    new ResourceGroupArgs() { Location = "West Europe" });
  var virtualNetwork = new VirtualNetwork(
    "vnet",
    new VirtualNetworkArgs
    {
      AddressSpaces = "10.12.0.0/16",
      ResourceGroupName = resourceGroup.Name,
      Location = resourceGroup.Location
    });
  var subnet = new Subnet(
    "subnet",
    new SubnetArgs
    {
      ResourceGroupName = resourceGroup.Name,
      VirtualNetworkName = virtualNetwork.Name,
      AddressPrefix = "10.12.0.0/29",
      Delegations = new InputList<SubnetDelegationsArgs>()
      {
        new SubnetDelegationsArgs
        {
          Name = "delegation",
          ServiceDelegation = new SubnetDelegationsServiceDelegationArgs
          {
            Name = "Microsoft.ContainerInstance/containerGroups",
            Actions = new [] { "Microsoft.Network/virtualNetworks/subnets/action" }
          }
        }
      }
    });
```

However, instead of updating virtual network the `pulumi up` results in the following error:
```
azure:network:Subnet (subnet):
  error: Error Creating/Updating Subnet "subnet476dc6b2" (Virtual Network "vnet0ba7456a" / Resource Group "pulumi-vnet-issuea864bcde"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'subnet476dc6b2' is not valid in virtual network 'vnet0ba7456a'." Details=[]
```

The interesting thing here is - if you execute `pulumi destroy` and then `pulumi up` the virtual network and subnet will be recreated without any issues.

At the first glance I thought this issue could be related to pulumi/pulumi#4260 but `pulumi refresh` didn't solves the problem.

## P.S.

Specifying a name `SubnetArgs` args doesn't change anything and results in the very similar error message:

```
azure:network:Subnet (subnet):
  error: Error Creating/Updating Subnet "subnet-name" (Virtual Network "vnet0ba7456a" / Resource Group "pulumi-vnet-issuea864bcde"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'just' is not valid in virtual network 'vnet0ba7456a'." Details=[]
```

## P.P.S

Specifying the same name (i.e. "vnet-subnet") as name in `SubnetArgs` results in the following error:

```
azure:network:Subnet (subnet):
  error: A resource with the ID "/subscriptions/d51c02c5-7375-44f0-b399-dc8adcc71456/resourceGroups/pulumi-vnet-issuea864bcde/providers/Microsoft.Network/virtualNetworks/vnet0ba7456a/subnets/vnet-subnet" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_subnet" for more information.
```

**Comment by mikhailshilkov** [comment]
I don't think we have any actionable here. The resource's behavior is derived from the terraform provider. I'll go ahead and close the issue, but feel free to let me know if you need further help.

**Comment by OlegKarasik** [comment]
Hi @mikhailshilkov,

I apologize for such a late response. 

The reason why I was asking about change/difference functionality is because when you are transferring from `MyStack` (1) to `MyStack` (2) using `pulumi up` the Pulumi CLI outputs the following:

```
> pulumi up

Previewing update (<stack name>):
     Type                     Name                      Plan
     pulumi:pulumi:Stack      <project name>
 +   └─ azure:network:Subnet  subnet                    create

Resources:
    + 1 to create
    3 unchanged
```

As you can see, Pulumi detects an intend to create a new virtual network subnet, however, the initial virtual network seems to be `unchanged`. 

Such behavior looks strange because from infrastructure code side I have done a resource modification i.e. I have updated virtual network subnet, so it is expected to see resource modification or create / delete sequence.

I am not really sure how closely Pulumi output is tied to actual actions performed but if they have close mapping then this situation looks like detect changes issue.

**Comment by mikhailshilkov** [comment]
@OlegKarasik I understand the confusion that this behavior causes. I really hope the subresource will disappear in the future and subnets will only be managed with the separate resource.

If you (or anybody reading this) need to do this migration from a subresource to a separate resource, you can do this with import.

Here are the steps:

1. You start with the subresource subnet:

```cs
var virtualNetwork = new VirtualNetwork(
    "vnet",
    new VirtualNetworkArgs
    {
        AddressSpaces = "10.12.0.0/16",
        ResourceGroupName = resourceGroup.Name,
        Location = resourceGroup.Location,
        Subnets =
        {
            new VirtualNetworkSubnetArgs
            {
                AddressPrefix = "10.12.0.0/29",
                Name = "vnet-subnet"
            }
        }
    });
```

You run `pulumi up` and deploy:

```
Updating (dev):
     Type                             Name               Status      
     pulumi:pulumi:Stack              azure-cs-dev                   
 +   ├─ azure:core:ResourceGroup      pulumi-vnet-issue  created     
 +   └─ azure:network:VirtualNetwork  vnet               created
```

2. Now, to transition, you define the separate resource with `ImportId` option:

```cs
var virtualNetwork = new VirtualNetwork(
    "vnet",
    new VirtualNetworkArgs
    {
        AddressSpaces = "10.12.0.0/16",
        ResourceGroupName = resourceGroup.Name,
        Location = resourceGroup.Location
    });

var subnet = new Subnet(
    "subnet",
    new SubnetArgs
    {
        Name = "vnet-subnet",
        ResourceGroupName = resourceGroup.Name,
        VirtualNetworkName = virtualNetwork.Name,
        AddressPrefix = "10.12.0.0/29",
    },
new CustomResourceOptions { ImportId = "/subscriptions/<your-sub>/resourceGroups/<your-rg>/providers/Microsoft.Network/virtualNetworks/<your-vnet>/subnets/vnet-subnet" });
```

You run `pulumi up` to import it:

```
     Type                     Name          Status       
     pulumi:pulumi:Stack      azure-cs-dev               
 =   └─ azure:network:Subnet  subnet        imported     
 
Resources:
    = 1 imported
    3 unchanged
```

Now you can remove the `ImportId` and start changing the subnet properties.

**Comment by OlegKarasik** [comment]
Thanks @mikhailshilkov! 

The sample you've provided worked as expected (here is a small typo in the code: In `1` the class name should be `VirtualNetworkSubnet**s**Args` rather than `VirtualNetworkSubnetArgs`).

I also have an additional question regarding the import process. The `ImportId` includes `<subscription id>`, `<resource group name>` and `<virtual network name>`. 

I have tried the following but it didn't work:

``` csharp
var config = Pulumi.Azure.Core.Invokes.GetClientConfig();
var resourceGroup = new ResourceGroup("pulumi-vnet-issue", new ResourceGroupArgs() { Location = "West Europe" });
var subscriptionId = config.ContinueWith(t => t.Result.SubscriptionId);

...

new CustomResourceOptions { ImportId = $"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup.Name}/providers/Microsoft.Network/virtualNetworks/{virtualNetwork.Name}/subnets/vnet-subnet" })
```

I also tried to use `Output.Create` to create an output string (because as I understand at the moment `ImportId` is consumed no values are resolved yet) but `ImportId` accepts a `string` type, so it didn't compile.

Do you know if it possible to dynamically substitute these values?

**Comment by mikhailshilkov** [comment]
>  the class name should be VirtualNetworkSubnet**s**Args rather than VirtualNetworkSubnetArgs

This has actually changed in the latest version of the provider (`3.*`) - this was our last set of breaking changes before GAing .NET.

> ImportId accepts a string type

I believe this is somewhat intentional. A typical import flow is that imported resources exist before the Pulumi program starts, so it needs to be resolved (as opposed to an `Output<t>`) when assigned.

What I did is exporting the ID of the subnet after the first run from the program 

```cs
this.SubnetId = virtualNetwork.Subnets.Apply(s => s[0].Id);
```

and then copy-pasting this ID to the new subnet resource on the second run.

**Comment by OlegKarasik** [comment]
Thank you for help!
