### ISSUE TITLE
Feedback: Pulumi CosmosDB APIs

### ISSUE THREAD

**Issue by prasannapad** [pulumi/pulumi-azure#526]
In playing around with the CosmosDB examples, I noticed that while it's easy to create new container/collection like this:

```
// Define a SQL Collection under the Cosmos DB Database
const collection = new azure.cosmosdb.SqlContainer("Urls", {
    resourceGroupName: resourceGroup.name,
    accountName: account.name,
    databaseName: database.name,
});

```

it doesn't offer an easy way to subsequently add items to that same container object. I would expect we can call something like :

`await collection.items.create({id: "foo", content: "bar"});`

similar to standard CosmosDB API but instead looks like I first have to call:

`const container = client.database(database.name.get()).container(collection.name.get());`

and only then be able to add items into that container. This seemed a little circuitous and not super intuitive.

Is there a reason for this?

**Comment by mikhailshilkov** [comment]
We don't currently integrate data plane SDKs into the control plane resources. If we ever decide to do so, we'll probably do it more holistically than just for the Cosmos DB items.
As there's nothing actionable here, I'll close this issue for now.

**Comment by mikhailshilkov** [comment]
For anyone interested, let's track this class of improvements in https://github.com/pulumi/pulumi/issues/4461
