### ISSUE TITLE
Support for Azure CDN delivery_rule and global_delivery_rule

### ISSUE THREAD

**Issue by jdudleyie** [pulumi/pulumi-azure#528]
Are Azure CDN delivery_rule and global_delivery_rule supported? I don't see them in the Pulumi docs or in the object definitions.

If not, is there a workaround in order to be able to use them?

https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html#global_delivery_rule

https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html#delivery_rule

**Comment by mikhailshilkov** [comment]
These options got introduced in the 2.6.0 version of the AzureRM Terraform provider just a couple of days ago. You should get them when we upgrade to this version soon.
cc @stack72

**Comment by stack72** [comment]
I am doing this right now :D

**Comment by stack72** [comment]
Closed via #529 and release will be very shortly
