### ISSUE TITLE
Missing option for the Python Package

### ISSUE THREAD

**Issue by sindre-nistad** [pulumi/pulumi-azure#532]
Hi,
The option to toggle / disable `purge_soft_delete_on_destroy` (for `pulumi_azure.keyvault.KeyVault`) is missing from the Python SDK. There is a reference to it in the documentation, referring to [how it may be disabled in Terraform](https://www.terraform.io/docs/providers/azurerm/r/key_vault.html).

**For context**
In a project I'm working on, I only have access to a resource group, and I have no access to its subscription, and so I get an error message saying I don't have permission to read soft-deleted key vaults.
In this case, I would be fine with Pulumi not restoring a soft-deleted key vault (as it is not used in this particular project).

**Comment by mikhailshilkov** [comment]
@stack72 Do we have an issue tracking exposing `features` options for the Azure provider?

**Comment by stack72** [comment]
Going to close this out - the provider has [ProviderFeatureArgs](https://github.com/pulumi/pulumi-azure/blob/master/sdk/python/pulumi_azure/provider.py#L202) included now
