### ISSUE TITLE
Supporting 'Consumption' Azure API Management SKU

### ISSUE THREAD

**Issue by jdudleyie** [pulumi/pulumi-azure#539]
Terraform has recently added support for newer Consumption SKU for Azure API Management it seems.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/6256

Would it be possible to include this in Pulumi? Thanks.

**Comment by leezen** [comment]
We track the upstream releases, so everything through 2.7.0 is released. We typically push out an update of our providers within 48 hours of upstream releases, so you'll see this get picked up once that happens.
