### ISSUE TITLE
AKS with only managed identity authentication can't be instantiated

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-azure#540]
With a recent release of the `azurerm` terraform provider, the mixed-mode authentication for AKS was discontinued.
During a small time frame it was required to provided both properties when creating a cluster 
```
ServicePrincipal: containerservice.KubernetesClusterServicePrincipalArgs{
	ClientId:     abc,
	ClientSecret: cde,
},
Identity: containerservice.KubernetesClusterIdentityArgs{
	Type: pulumi.String("SystemAssigned"),
},
```

According to [this](https://github.com/terraform-providers/terraform-provider-azurerm/commit/1837de7e87c9fcda751d9757b653bb396803cd01#diff-e790822df6884d45f840c553edb1ceadR135) commit moving forward only `identity` will be required.

Unfortunately, using `pulumi-azure v3.3.0` and `pulumi 2.1.0` I'm not able to omit the `ServicePrincipal` section:
```
error: azure:containerservice/kubernetesCluster:KubernetesCluster resource 'mycluster-k8s' has a problem: Missing required property 'servicePrincipal'
```

Thanks!

**Comment by leezen** [comment]
I tried to minimally reproduce this, but the preview succeeds.

**main.go**
```go
package main

import (
	"github.com/pulumi/pulumi-azure/sdk/v3/go/azure/containerservice"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		cluster, err := containerservice.NewKubernetesCluster(ctx, "cluster", &containerservice.KubernetesClusterArgs{
			DefaultNodePool: containerservice.KubernetesClusterDefaultNodePoolArgs{
				Name:   pulumi.String("default"),
				VmSize: pulumi.String("Standard_F1"),
			},
			DnsPrefix: pulumi.String("pulumitest"),
			Identity: containerservice.KubernetesClusterIdentityArgs{
				Type: pulumi.String("SystemAssigned"),
			},
			ResourceGroupName: pulumi.String("rg"),
		})

		if err != nil {
			return err
		}

		ctx.Export("cluster", cluster.ID())
		return nil
	})
}

```

**go.sum** | grep pulumi
```
github.com/pulumi/pulumi-azure/sdk/v3 v3.3.0 h1:GbERnN7AaWxjVEiSBzXkcR64sVyXEWqRFZ29+MXq3k8=
github.com/pulumi/pulumi-azure/sdk/v3 v3.3.0/go.mod h1:hZf4OGDeY+7Wbdq/3CbeuhbtRQw2UsRzs95f7mlCjfE=
github.com/pulumi/pulumi/sdk/v2 v2.1.0 h1:NZCLrvggMHlBzsaAcvChdDhQ5i9vJxARnLCY7NCFl18=
github.com/pulumi/pulumi/sdk/v2 v2.1.0/go.mod h1:W7k1UDYerc5o97mHnlHHp5iQZKEby+oQrQefWt+2RF4=
```

**Comment by EvanBoyle** [comment]
@elsesiy Is there any chance that you have a `vendor` directory in your project (it may be hidden by the default .gitignore)? This could cause the dependency issues that you're seeing.

To be 100% sure I'd recommend the following:

1. delete your project directory and clone into it again.
2. clear your go module cache: `rm -rf $GOPATH/pkg/mod`

Then try to do the preview again.

**Comment by elsesiy** [comment]
@EvanBoyle Yes I have a vendor dir but that's current. I actually found the issue for this, it's oudated plugins. I gave @leezen already a heads-up on this, the plugins are not acquired automatically which the should be according to [this change](https://github.com/pulumi/pulumi/pull/4297) so in my case they were super outdated and I had to manually `rm` the old ones and install the latest..

**Comment by EvanBoyle** [comment]
@elsesiy Perhaps some more information on your environment would be helpful. 

1. Are you using dep or mod, what does your `go.mod` look like if so? 
2. If you're using modules, why are you vendoring instead of using `go mod download`?
3. What version of the CLI are you using? `pulumi version`.

Happy to look into the plugin acquisition issues if you can help me get a repro of your environment.

**Comment by elsesiy** [comment]
@EvanBoyle Thanks.
1. mod
```
module github.com/snowflakedb/k8s-pulumi-azure

go 1.14

require (
	github.com/pulumi/pulumi-azure/sdk/v3 v3.3.0
	github.com/pulumi/pulumi-azuread/sdk/v2 v2.1.0
	github.com/pulumi/pulumi-random/sdk/v2 v2.1.0
	github.com/pulumi/pulumi-tls/sdk/v2 v2.1.0
	github.com/pulumi/pulumi/sdk/v2 v2.1.0
)
```

2. These operations are complimentary to each other and I don't want a CI system having to download any dependencies
3. `v2.1.0`
