### ISSUE TITLE
Newly added Consumption SKU for Azure API Management fails "expected sku_name capacity value to be greater that 1, got 0"

### ISSUE THREAD

**Issue by jdudleyie** [pulumi/pulumi-azure#542]
Terraform has recently added support for newer Consumption SKU for Azure API Management in terraform-provider-azurerm:

https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.8.0
https://github.com/terraform-providers/terraform-provider-azurerm/pull/6602

Pulumi-azure has included this in v3.4.0 it looks like:

https://github.com/pulumi/pulumi-azure/releases/tag/v3.4.0

However if I specify the value `skuName: 'Consumption_0'` I get the error `expected sku_name capacity value to be greater that 1, got 0`.

If I specify the value `skuName: 'Consumption_1'` I get the error `Invalid parameter: For Consumption SKU Type capacity must be specified as 0.`

Is there extra validation in Pulumi's code which does not allow a zero value that perhaps needs to be amended?

**Comment by jdudleyie** [comment]
If there is even a workaround for this I would be grateful to know it - thanks.

**Comment by jdudleyie** [comment]
It looks like this issue is being addressed here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/6733

**Comment by marklam** [comment]
This issue is marked as fixed in terraform, v2.42.0

**Comment by mikhailshilkov** [comment]
Closing since the upstream issue was fixed
