### ISSUE TITLE
Uploading a zero bytes file with Blob to a storage account fails

### ISSUE THREAD

**Issue by StefH** [pulumi/pulumi-azure#544]
When I have a file with 0 bytes (`.nojekyll`) in below screenshot:
![image](https://user-images.githubusercontent.com/249938/80858023-db260700-8c56-11ea-9283-ccc9a1673dc9.png)

This fails with this error:

> error: Error creating Blob ".nojekyll" (Container "$web" / Account "blazorhandlebarsa3c1ecf9"): Error PutBlockBlobFromFile: Error putting bytes: blobs.Client#PutBlockBlob: Invalid input: `input.Content` must either be nil or not empty.

However uploading the same file directly in Azure using the storage explorer is just fine.

**Comment by Vimary94** [comment]
Hello @StefH  did you find a solution? I'm facing the same issue but in Terraform :(

**Comment by StefH** [comment]
@Vimary94 

Actually when I read the error message correctly, in case of an empty file, I should just provide `null` (or not set the `Source` on the `BlobArgs`.

I fixed my code like this:
``` cs
var blobArgs = new BlobArgs
{
    AccessTier = args.AccessTier,
    ContentType = MimeTypeMap.GetMimeType(fileInfo.Extension),
    Name = blobName,
    Parallelism = args.Parallelism,
    StorageAccountName = args.StorageAccountName,
    StorageContainerName = args.StorageContainerName,
    Type = args.Type
};

// https://github.com/pulumi/pulumi-azure/issues/544
if (fileInfo.Length > 0)
{
    blobArgs.Source = new FileAsset(fileInfo.FullName);
}
```

Full source can be found here:
https://github.com/StefH/Pulumi.Azure.Extensions/blob/master/src/Pulumi.Azure.Extensions/Storage/BlobCollection.cs
