### ISSUE TITLE
App Service Plan is missing properties

### ISSUE THREAD

**Issue by ValkyrieUK** [pulumi/pulumi-azure#545]
Attempting to create an Azure App Service Plan.

```typescript
new azure.appservice.Plan(`orchestrator-app-plan`, {
  resourceGroupName: resourceGroup.name,
  maximumElasticWorkerCount: 2,
  kind: "elastic",
  sku: {
    tier: "ElasticPremium",
    size: "EP1",
  },
  appServiceEnvironmentId: orchestratorEnv.id,
});
```

This fails with the following error.

```
Error creating/updating App Service Plan "orchestrator-app-plan8e567180" (Resource Group "project-68fe883a"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="WorkerSizeId is invalid." Details=[{"Message":"WorkerSizeId is invalid."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51012","Message":"WorkerSizeId is invalid.","MessageTemplate":"{0} is invalid.","Parameters":["WorkerSizeId"]}}]
```

The `appservice.Plan` class does not seem to have the `WorkerSizeId` property. Perhaps this should be set via using `maximumElasticWorkerCount` or `maximumNumberOfWorkers`?

**Comment by ValkyrieUK** [comment]
I've noticed this only occurs if `appServiceEnvironmentId` is set.

**Comment by stack72** [comment]
Thanks for self closing that @ValkyrieUK :) I was just about to start triaging!

Paul

**Comment by ValkyrieUK** [comment]
@stack72 No worries, I managed to get a little bit further with it. It seems as theres so many options with app service plans that it hard to validate them against each other before attempting a deploy. I'll update this issue with what worked incase anyone else stumbles on this in the future.

**Comment by stack72** [comment]
You are a ⭐ - thanks!

**Comment by ValkyrieUK** [comment]
This is what worked in the end. I was trying to create an isolated environment for AZ functions to run in.

```
const orchestratorPlan = new azure.appservice.Plan(
  `orchestrator-app-plan`,
  {
    resourceGroupName: resourceGroup.name,
    kind: "Linux",
    sku: {
      tier: "ElasticIsolated",
      size: "I1",
      capacity: 1,
    },
    appServiceEnvironmentId: orchestratorEnv.id,
    reserved: true,
  }
);
```

Just a note that **this took over 2 hours** to deploy 😱

**Comment by stack72** [comment]
2 hours??!!! That sounds terrible - is it the same experience from the portal or is this a bug with Pulumi?

**Comment by ValkyrieUK** [comment]
Definitely Azure, I've run into a few instances of resource taking outrageously long to create.

One improvement that Pulumi _could_ include is a change of the default timeout for creating the plan (and event hubs for that matter). Pulumi would time out waiting for the resource to be in the available state. This in-turn means that the creation of the resource goes into the `pending_operations` section of the Pulumi state file and means having to go in to manually fix it.

I got around this issue by overriding the default timeout.

```
const orchestratorPlan = new azure.appservice.Plan(
  `orchestrator-app-plan`,
  {
    resourceGroupName: resourceGroup.name,
    kind: "Linux",
    sku: {
      tier: "ElasticIsolated",
      size: "I1",
      capacity: 1,
    },
    appServiceEnvironmentId: orchestratorEnv.id,
    reserved: true,
  },
  {
    customTimeouts: {
      create: "360m",
      update: "360m",
      delete: "360m",
    }
  }
);
```

**Comment by stack72** [comment]
So, in theory, I agree... *BUT* the chance of us (the Pulumi team) remembering how long it takes a service to deploy is low so whatever we set this value to be,  it may be wrong

But I am going to add an issue to pulumi-terraform-bridge to track this thought for enhancement

**Comment by ValkyrieUK** [comment]
Yeah that seems fair, pretty shocking it takes AZ that long. Glad I can contribute :)
