### ISSUE TITLE
Appservice HttpEventSubscription does not set runtime

### ISSUE THREAD

**Issue by ValkyrieUK** [pulumi/pulumi-azure#548]
Using a HttpEventSubscription to create an AZ function and have it deployed in an ASEv2.

All the resource get deployed fine but the AZ portal shows the `Azure Functions Runtime is unreachable.` Error. 

The reason for this is because when deploying a HttpEventSubscription it should have the configuration value of `FUNCTIONS_WORKER_RUNTIME` set to one of the [valid options](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_worker_runtime).

Setting this value in the config resolve the `Azure Functions Runtime is unreachable.` Error.

**Comment by ValkyrieUK** [comment]
Seems that including the follow will make the function work


```
    appSettings: {
      FUNCTIONS_WORKER_RUNTIME: "node",
    },
```

**Comment by mikhailshilkov** [comment]
It looks like Azure Functions switched from `runtime` to `FUNCTIONS_WORKER_RUNTIME` at some point and we missed that. We should set `FUNCTIONS_WORKER_RUNTIME`, basically always.

**Comment by stack72** [comment]
@ValkyrieUK so I am working on a fix for this right now - where in the console do  you see "Azure Functions Runtime is unreachable"?

**Comment by ValkyrieUK** [comment]
Hey @stack72,

It's worth noting that Azure has updated the front end on the portal for functions so the location may have changed.

I was able to see the warning just by clicking into the function on the portal. After a moment or two the warning would pop up with a link to common fixes.
