### ISSUE TITLE
Unable to get outputs from azure.appservice.FunctionApp

### ISSUE THREAD

**Issue by carterwilliamson** [pulumi/pulumi-azure#549]
I'm trying to use the outputs from the FunctionApp resource to build the URL for downstream automation. I expect the last line in the following code block to work correctly.

However, what I see is that the "apply" is never triggered. The print statement is never called and no output is shown. I've tried changing the print statement inside the apply lambda to print a static string and it did not print anything.

```python
resource_group = core.ResourceGroup(name, tags=tags)

# Additional Resources... (appservice, storage account, etc.)

function_app = appservice.FunctionApp(
    name,
    resource_group_name=resource_group.name,
    app_service_plan_id=plan.id,
    storage_account_name=account.name,
    storage_account_access_key=account.primary_access_key,
    version="~3",
    app_settings={
        "runtime": "python",
        "WEBSITE_RUN_FROM_PACKAGE": signed_blob_url,
    },
    tags=tags
)

# This works and prints a list of outputs
Output.all(resource_group.name, resource_group.id).apply(lambda _args: print(_args))

# This doesn't work
Output.all(function_app.name).apply(lambda _args: print(_args))
```

Packages:
pulumi==2.1.0
pulumi-azure==3.4.0

**Comment by leezen** [comment]
This looks like it might be https://github.com/pulumi/pulumi/issues/3991 -- in which case, the workaround will be to export `function_app.name` to ensure it gets awaited.

**Comment by carterwilliamson** [comment]
That work around did the trick, but certainly not the expected behavior. Thanks for the advice.

**Comment by leezen** [comment]
I'll close this issue and continue to track the fix in https://github.com/pulumi/pulumi/issues/3991
