### ISSUE TITLE
Creating a new EventHub Namespace actually creates a Service Bus Namespace

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-azure#550]
As of pulumi-azure 3.4.0 creating a new eventhub.Namespace resource creates a Service Bus Namespace instead.

A warning is printed about eventhub.Namespace being deprecated by servicebus.Namespace - this seems wrong as the they are two different resource types.

Calls to eventhub.getNamespace() that reference the same values passed to the constructor fail with a 404 that the event hub doesn't exist.

**Comment by mikhailshilkov** [comment]
@oliverholliday  The correct resource names are `eventhub.EventHubNamespace` and `servicebus.Namespace`. Calls are `eventhub.getEventHubNamespace` and `servicebus.getNamespace`.

I hope this helps.

**Comment by oliverholliday** [comment]
I went back to pulumi-azure:3.3.0 and the Service Bus Namespace was deleted and the correct Event Hub Namespace was created with no change in code.

**Comment by oliverholliday** [comment]
Ah I see - eventhub.getNamespace calls servicebus.getNamespace. 

I fixed the deprecation warnings from the previous version but I guess they were a mistake as they've gone now!


Thanks
