### ISSUE TITLE
Creating a VirtualNetworkGateway errors despite the resource creating correctly

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-azure#551]
Creating a VirtualNetworkGateway takes a long time on Azure but unlike most API timeouts, pulumi doesn't recognise that the resource was accepted and doesn't add it to the stack state.

(Azure docs say up to 45 minutes: https://docs.microsoft.com/en-us/azure/vpn-gateway/create-routebased-vpn-gateway-cli#CreateGateway)

```
Updating (advanced-networking-test):
     Type                                    Name                                               Status                  Info
     pulumi:pulumi:Stack                     advanced-networking-test-advanced-networking-test  **failed**              1 error
 +   └─ azure:network:VirtualNetworkGateway  vnet-gw                                            **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (advanced-networking-test-advanced-networking-test):
    error: update failed

  azure:network:VirtualNetworkGateway (vnet-gw):
    error: Error waiting for completion of AzureRM Virtual Network Gateway "vnet-gw" (Resource Group "test-dev-eu"): Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: 
context deadline exceeded

Resources:
    102 unchanged

~~~

Previewing update (advanced-networking-test):
     Type                                    Name                                               Plan
     pulumi:pulumi:Stack                     advanced-networking-test-advanced-networking-test
 +   └─ azure:network:VirtualNetworkGateway  vnet-gw                                            create

Resources:
    + 1 to create
    102 unchanged
```

**Comment by mikhailshilkov** [comment]
@oliverholliday Did you notice how much time passes until it fails?
@komalali Could this be related to https://github.com/pulumi/pulumi-terraform-bridge/issues/177?

**Comment by oliverholliday** [comment]
@mikhailshilkov I'm not certain but I did it a couple of times and about twenty minutes seems right.

**Comment by komalali** [comment]
Thanks for the info @oliverholliday! This definitely looks related to https://github.com/pulumi/pulumi-terraform-bridge/issues/177, which I'm looking into. In the meanwhile, you can use a [custom timeout](https://www.pulumi.com/docs/intro/concepts/programming-model/#customtimeouts) as a workaround.

**Comment by komalali** [comment]
The underlying problem should be fixed in https://github.com/pulumi/pulumi-azure/releases/tag/v3.5.1 so I’m closing out this issue but please feel free to re-open it if you come across this again.

**Comment by irom77** [comment]
I got the problem with it using pulumi-azure 3.11.0. It creates gateways quickly, but then error out waiting for completion . I can only setup timeout to short the waiting time.
`error: Error waiting for completion of AzureRM Virtual Network Gateway`
Anyways, creating resources look ok , pulumi can't just verify completion correctly
