### ISSUE TITLE
Api management Web service URL got blank after rerun

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azure#561]
Hi,
I got an issue with Azure API Management. The Web service URL got blank after rerun. However, the URL will have appeared if re-run with --refresh. 

_PS: The Api operation will be imported from a json URL during deployment._

**Comment by leezen** [comment]
Could you please provide an example of this?

**Comment by baoduy** [comment]
Hi @leezen here is a sample
```javascript
 const api = new azure.apimanagement.Api(name, {
    name: 'MyAPI',
    resourceGroupName: "StevenGroup",
    apiManagementName: "baoduy2412-apim",
    displayName: "My API",
    import: {
        contentFormat: 'openapi+json-link',
        contentValue: 'https://baoduy2412-api.azurewebsites.net/swagger/v1/swagger.json',
    },
    path: '',
    protocols: ['https'],
    revision:'v1',
    serviceUrl: 'https://baoduy2412-api.azurewebsites.net',
    subscriptionKeyParameterNames: { header: 'baoduy2412-api-key', query: 'baoduy2412-api-subscription' },
  });
```
The serviceUrl got blank after `pulumi up`. However, I ran refresh then up again the serviceUrl was appeared again.

**Comment by leezen** [comment]
I'm not really sure what you mean by "got blank" here. I tried a couple things around updating an input, but if I export the `serviceUrl` I always see the correct output value.

**Comment by baoduy** [comment]
Hi @leezen 
This is the result I got after run the script for the first time.
![image](https://user-images.githubusercontent.com/166953/81781390-9b023680-952a-11ea-8775-fe0adc66354c.png)

And this is the result of subsequence run with --refresh.
![image](https://user-images.githubusercontent.com/166953/81781822-617dfb00-952b-11ea-9af4-39dd620dd27c.png)

**Comment by leezen** [comment]
That looks like a bug in the Azure console if anything? When I checked both the statefile and against the Azure API, the `serviceUrl` never goes missing.
