### ISSUE TITLE
Can not create Kusto Database Principal

### ISSUE THREAD

**Issue by xadcoh** [pulumi/pulumi-azure#569]
```
$ pulumi version
v2.1.1
```
```
$ pulumi plugin ls
NAME        KIND      VERSION  SIZE    INSTALLED  LAST USED
azure       resource  3.4.0    177 MB  n/a        1 week ago
azuread     resource  2.1.1    41 MB   n/a        1 day ago
azuread     resource  2.1.0    41 MB   n/a        1 week ago
kubernetes  resource  2.0.0    52 MB   n/a        1 week ago

TOTAL plugin cache size: 312 MB
```

Using slightly modified code from [example](https://www.pulumi.com/docs/reference/pkg/azure/kusto/databaseprincipal/)

```
import pulumi
import pulumi_azure as azure

tags = {"Owner": "user@company.net"}

current = azure.core.get_client_config()
rg = azure.core.ResourceGroup("rg", location="East US", tags=tags)
cluster = azure.kusto.Cluster("cluster",
    location=rg.location,
    resource_group_name=rg.name,
    sku={
        "name": "Standard_D13_v2",
        "capacity": 2,
    })
database = azure.kusto.Database("database",
    resource_group_name=rg.name,
    location=rg.location,
    cluster_name=cluster.name,
    hot_cache_period="P7D",
    soft_delete_period="P31D")
principal = azure.kusto.DatabasePrincipal("principal",
    resource_group_name=rg.name,
    cluster_name=cluster.name,
    database_name=database.name,
    role="Viewer",
    type="User",
    client_id=current.tenant_id,
    object_id=current.client_id)
```

Added tags and changed 
```
database_name=azurerm_kusto_database["test"]["name"] -> database_name=database.name
```

Kusto cluster and Database are created, but DatabasePrincipal returned an error:

```
Diagnostics:
  azure:kusto:DatabasePrincipal (principal):
    error: Error creating Kusto Database Principal (Resource Group "rg-kusto-testdcc32db9", Cluster "cluster9c203712"): kusto.DatabasesClient#AddPrincipals: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The request is invalid."
```

**Comment by mikhailshilkov** [comment]
I think this depends on your current authentication mechanism that you use with Pulumi. I'm logged in as a user with `az login` and the following snippet worked for me (note a different `object_id`):

```py
principal = azure.kusto.DatabasePrincipal("principal",
    resource_group_name=rg.name,
    cluster_name=cluster.name,
    database_name=database.name,
    role="Viewer",
    type="User",
    client_id=current.tenant_id,
    object_id=current.object_id)
```

Here is my new principal in the portal:

![image](https://user-images.githubusercontent.com/1454008/82184795-7e7a4b80-98e8-11ea-8443-7e8690045906.png)

In case of a doubt, you should export all the properties from `current` and double-check whether the IDs that you are passing are actually valid. I suspect that the original example is intended to be used with a SP.

I hope this helps.

**Comment by xadcoh** [comment]
Hi

`object_id` did the trick. Next I created SP and used the code:

`
kusto_application = Application("kusto-app")

kusto_service_principal = ServicePrincipal("kustoServicePrincipal",
 application_id=kusto_application.application_id)

kusto_service_principal_password = ServicePrincipalPassword("kustoServicePrincipalPassword",
    end_date="2099-01-01T01:02:03Z",
    service_principal_id=kusto_service_principal.id,
    value=config.require("service_principal_password")
)

resource_group = ResourceGroup(
    'kusto-rg',
    tags=tags)

kusto_cluster = Cluster(
    "kusto-cluster",
    name=config.require("kusto_cluster_name"),
    tags=tags,
    resource_group_name=resource_group.name,
    sku={
        "name": "Standard_D11_v2",
        "capacity": 2
    }
)

kusto_database = Database(
    "kusto-database",
    cluster_name=kusto_cluster.name,
    name="pulumidb",
    resource_group_name=resource_group.name
)

kusto_database_principal = DatabasePrincipal(
    "kusto-database-principal",
    client_id=subscription.tenant_id,
    cluster_name=kusto_cluster.name,
    database_name=kusto_database.name,
    object_id=kusto_service_principal.object_id,
    resource_group_name=resource_group.name,
    role="Admin",
    type="App"
)
`

I got an error:

`
Diagnostics:
  azure:kusto:DatabasePrincipal (kusto-database-principal):
    error: expected non-nil error with nil state during Create of urn:pulumi:dev-kusto::kusto::azure:kusto/databasePrincipal:DatabasePrincipal::kusto-database-principal
`

Meanwhile SP was added to Database Permissions

**Comment by mikhailshilkov** [comment]
This issue is three years old and hasn't got any recent comments. I'll assume it's been fixed in https://github.com/pulumi/pulumi-terraform-bridge/issues/114
