### ISSUE TITLE
Add listKeys, listSecrets, and list* resource functions

### ISSUE THREAD

**Issue by loic-sharma** [pulumi/pulumi-azure#57]
This is necessary to fetch keys from resources like Azure Search.

See this documentation: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#listkeys-listsecrets-and-list

**Comment by lukehoban** [comment]
@jen20 Do we have a sense of how critical important these are?  The Azure Terraform provider does not appear to expose them - and instead exposes keys off of specific resources in many cases.  Is there something we can/should do here in the nearterm?  Or is this something that should be feedback to the Azure Terraform provider?

**Comment by jen20** [comment]
As of the latest version, these still aren't exposed directly by the Terraform provider, but I think some of the list* functions are implemented as data sources. I think if we're going to implement them it would be best to upstream implementations.

@loic-sharma - can you elaborate on which of these you need?

**Comment by loic-sharma** [comment]
So far, I've only needed `listAdminKeys` to connect an [Azure App Service](https://azure.microsoft.com/en-us/services/app-service/) to an [Azure Search Service](https://azure.microsoft.com/en-us/services/app-service/). The "admin keys" are the secret used to authenticate to the Azure Search Service. I'm not sure what else use these resource functions.

**Comment by stack72** [comment]
Hi @loic-sharma 	

I just opened this issue upstream as this needs added there https://github.com/terraform-providers/terraform-provider-azurerm/issues/3607

If you can provide a little more detail about why you need to use these endpoints on that issue, then that would help the Terraform team prioritise it

I am going to close this issue out as a duplicate. We can track that upstream issue and when support is added in Terraform, we will inherit it 

Thanks

Paul
