### ISSUE TITLE
Access Denied (403) when installing pulumi-resource-azure-v3.7.0-alpha.1590702640+g1d381320-windows-amd64.tar.gz

### ISSUE THREAD

**Issue by sfmskywalker** [pulumi/pulumi-azure#586]
Hi!

I just upgraded to the latest version (https://get.pulumi.com/releases/sdk/pulumi-v2.3.0-windows-x64.zip) and updated the `Pulumi.Azure` package to the latest preview version (`3.7.0-alpha.1590702640`)

However, when I now do `pulumi up`, I receive the following error:

```bash
Diagnostics:
  pulumi:providers:azure (default_3_7_0_alpha_1590702640_g1d381320):
    error: no resource plugin 'azure-v3.7.0-alpha.1590702640+g1d381320' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure v3.7.0-alpha.1590702640+g1d381320`
```

So I tried the recommendation and performed:

```bash
pulumi plugin install resource azure v3.7.0-alpha.1590702640+g1d381320
```

Which returned the following response:

```bash
[resource plugin azure-3.7.0-alpha.1590702640+g1d381320] installing
error: [resource plugin azure-3.7.0-alpha.1590702640+g1d381320] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-azure-v3.7.0-alpha.1590702640+g1d381320-windows-amd64.tar.gz
```
Indeed, when I try to [download the zip file directly](https://get.pulumi.com/releases/plugins/pulumi-resource-azure-v3.7.0-alpha.1590702640+g1d381320-windows-amd64.tar.gz) using the browser, I receive a 403:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>875B85C2E8E7E738</RequestId>
<HostId>sIwo29eQf3AFKS0Ie0ZSFNA7+j9QU2A+mWD3jpRykCYiQnVGN7kJmu04oY1c9ymRq4TdiL0rfnQ=</HostId>
</Error>
```

I'll try previous versions of the package to see if that helps.

**Comment by stack72** [comment]
Hi @sfmskywalker 

I would suggest to not use the alpha releases if possible - these are generated on every merge to master and nightlies and may change between versions

the non-alpha releases are much more stable - e.g. v3.7.0

**Comment by stack72** [comment]
@sfmskywalker 

Also, please note, that you did indeed find a bug here :) These *should* be able to be downloaded but for some reason they are not 

I am looking into this

Thanks

Paul

**Comment by sfmskywalker** [comment]
Roger that. Thanks for the quick reply 😄

**Comment by leezen** [comment]
Thanks again for reporting this. This has been fixed and those URLs should be working now.

**Comment by AIZ-THerring** [comment]
Did this ever get fixed?  If so, it's happening again:

[resource plugin Azure-5.49.0] installing
error: [resource plugin Azure-5.49.0] downloading from : failed to download plugin: Azure-5.49.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-Azure-v5.49.0-windows-amd64.tar.gz
