### ISSUE TITLE
Create an equivalent of serverless.Function

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#60]
We want a serverless function abstraction, akin to https://github.com/pulumi/pulumi-aws/blob/master/overlays/nodejs/serverless/function.ts, for Azure, to make it more seamless to express function code in your Pulumi programs.

**Comment by CyrusNajmabadi** [comment]
pre-alpha bits added in: https://github.com/pulumi/pulumi-azure-serverless/pull/1
