### ISSUE TITLE
Azure DevOps Pulumi task - assumes v.3.8.0

### ISSUE THREAD

**Issue by CortalUX** [pulumi/pulumi-azure#601]
The latest Azure Provider python package is v3.9.0.
https://pypi.org/project/pulumi-azure/

```
Collecting pulumi-azure<4.0.0,>=3.0.0
  Downloading pulumi_azure-3.9.0.tar.gz (598 kB)
```

The Azure DevOps Pipeline task installs azure-v3.8.0 by default when previewing an update.
```
D:\a\_temp\7118935f-b211-40f2-b85b-a475f99254fe\pulumi\bin\pulumi.exe up --yes
Previewing update (dev):
[resource plugin random-2.1.2] installing

Downloading plugin: 0 B / 15.65 MiB    0.00%
Downloading plugin: 4.05 MiB / 15.65 MiB   25.85%
Downloading plugin: 9.43 MiB / 15.65 MiB   60.23%
Downloading plugin: 15.65 MiB / 15.65 MiB  100.00%[resource plugin azure-3.8.0] installing
[....]
    pulumi:providers:azure default_3_9_0  error: no resource plugin 'azure-v3.9.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure v3.9.0`
    pulumi:providers:azure default_3_9_0  1 error
    pulumi:pulumi:Stack smart-buildings-dev  3 messages
 
Diagnostics:
  pulumi:providers:azure (default_3_9_0):
    error: no resource plugin 'azure-v3.9.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure v3.9.0`

```

**Comment by stack72** [comment]
Hi @CortalUX 

v3.9.0 was opened just a matter of hours ago - therefore, I think if you rerun the task from scratch, it may well update?

P.

**Comment by CortalUX** [comment]
v1.0.6 ( https://get.pulumi.com/releases/sdk/pulumi-v2.4.0-windows-x64.zip ) of the task seems to still be downloading v3.8.0 of the Pulumi provider on re-run of the task.

It's a clean build - it's a microsoft hosted build machine, so discarded after each use, so shouldn't be an issue with the environment.

```
Prepare build directory.
Set build variables.
Download all required tasks.
...
Downloading task: Pulumi (1.0.6)
...
Task         : Pulumi Azure Pipelines Task
Description  : Azure Pipelines task extension for running Pulumi apps.
Version      : 1.0.6
...
Diagnostics:
  pulumi:providers:azure (default_3_9_0):
    error: no resource plugin 'azure-v3.9.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure v3.9.0`

```

For now, I'll pin the requirements.txt file to 3.8.0, as a workaround.

**Comment by stack72** [comment]
@CortalUX that's really weird...

I am able to install it fine here:

```
▶ pulumi plugin install resource azure 3.9.0
[resource plugin azure-3.9.0] installing
Downloading plugin: 50.18 MiB / 50.18 MiB [=========================] 100.00% 3s
Moving plugin... done.
```

**Comment by CortalUX** [comment]
yeah, that works entirely fine on my machine too - but the Azure Pipelines task selects and installs what it thinks to be the correct plugin automatically.

![image](https://user-images.githubusercontent.com/19361656/84524153-645a4000-acd1-11ea-9956-6bd6f2be6b0a.png)

![image](https://user-images.githubusercontent.com/19361656/84524091-4d1b5280-acd1-11ea-8e99-4a09519e65a7.png)

**Comment by stack72** [comment]
ok, let's leave this open - something is weird here for sure!

**Comment by CortalUX** [comment]
sounds good! 

my potentially incorrect understanding is that Python properly detects that 3.9.0 has been released. and I can install that on my machine too. but the automated task in Azure DevOps believes the current provider for Azure to be 3.8.0 when it runs Pulumi up. 

pinning the requirement:
`pulumi-azure==3.8.0` rather than `pulumi-azure>=3.0.0,<4.0.0` is a functioning workaround for now.

I'll check after the weekend too. maybe Azure is cacheing the download or something similar.

**Comment by stack72** [comment]
👍 please do let me know here

**Comment by CortalUX** [comment]
So I'm getting the same issue at present.
Requirements.txt which causes the issue:
```
pulumi>=2.0.0,<3.0.0
pulumi-random>=2.0.0,<3.0.0
pulumi-azure>=3.0.0,<4.0.0
```

I have a workaround, pinning the version `pulumi-azure==3.8.0` in requirements.txt, but this just seems a bit odd.

The Azure pipeline:
![image](https://user-images.githubusercontent.com/19361656/84658402-c43d2a80-af0d-11ea-981d-c22dc3a92951.png)

And version is set to latest:
![image](https://user-images.githubusercontent.com/19361656/84658513-e9ca3400-af0d-11ea-8eda-6f55781c8d88.png)


The task output
```
Starting: Run Pulumi up on Dev stack
==============================================================================
Task         : Pulumi Azure Pipelines Task
Description  : Azure Pipelines task extension for running Pulumi apps.
Version      : 1.0.6
Author       : Pulumi
Help         : Join us on Slack at https://slack.pulumi.com.
==============================================================================
Downloading: https://get.pulumi.com/releases/sdk/pulumi-v2.4.0-windows-x64.zip
Extracting archive
C:\windows\system32\chcp.com 65001
Active code page: 65001
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\c7895891-31b7-40ec-9777-f863b713cfba', 'D:\a\_temp\a81c0345-c8b1-4917-89c5-53a068fffb6c')"
Prepending PATH environment variable with directory: D:\a\_temp\a81c0345-c8b1-4917-89c5-53a068fffb6c\pulumi\bin
D:\a\_temp\a81c0345-c8b1-4917-89c5-53a068fffb6c\pulumi\bin\pulumi.exe version
v2.4.0

D:\a\_temp\a81c0345-c8b1-4917-89c5-53a068fffb6c\pulumi\bin\pulumi.exe login
Logging in using access token from PULUMI_ACCESS_TOKEN
Logged in to pulumi.com as [removed]

D:\a\_temp\a81c0345-c8b1-4917-89c5-53a068fffb6c\pulumi\bin\pulumi.exe stack select dev

D:\a\_temp\a81c0345-c8b1-4917-89c5-53a068fffb6c\pulumi\bin\pulumi.exe up --yes
Previewing update (dev):
[resource plugin azure-3.8.0] installing

Downloading plugin: 0 B / 49.65 MiB    0.00%[resource plugin random-2.1.2] installing

Downloading plugin: 0 B / 15.65 MiB    0.00%
Downloading plugin: 10.55 MiB / 49.65 MiB   21.25%
Downloading plugin: 12.17 MiB / 15.65 MiB   77.78%
Downloading plugin: 32.00 MiB / 49.65 MiB   64.45%
Downloading plugin: 15.65 MiB / 15.65 MiB  100.00%
Downloading plugin: 49.65 MiB / 49.65 MiB  100.00%
Downloading plugin: 15.65 MiB / 15.65 MiB  100.00%
```

**Comment by CortalUX** [comment]
I'm getting this with the release/update to v2.1.3 for pulumi-random too.
The Pulumi build task downloads the plugin for v2.1.2. I have v2.1.3 specified in requirements.txt.
```
pulumi:providers:random (default_2_1_3):
    error: no resource plugin 'random-v2.1.3' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource random v2.1.3`
```

**Comment by justinvp** [comment]
@CortalUX, what does your "Install Python dependencies in venv" do? Does it "activate" the virtual environment such that `pulumi up` will be using the `python` and dependencies in the virtual environment?

**Comment by justinvp** [comment]
@CortalUX, I think I know what's going on... You have a task to "Install Python dependencies in venv" that looks like it runs before Pulumi is installed. But installing the `pulumi-random` and `pulumi-azure` Python packages actually requires Pulumi to already be installed, because as part of installing those packages it shells out to `pulumi plugin install` to install the native plugin.

https://github.com/pulumi/pulumi-azure/blob/43ef7546149b0ffe01db1e67de0471a07a61607c/sdk/python/setup.py#L11-L26

When `pulumi up` runs, it attempts to make sure the plugins it needs are installed and it does this by looking at what plugins were referenced in the current snapshot, which may be referencing a prior version from the previous deployment.

Is there a way you can rework your pipeline to install Pulumi first, before installing the dependencies for the Python program and running `pulumi up`?

**Comment by CortalUX** [comment]
This sounds right - I'm installing Pulumi via Python, but I haven't already installed it on the host machine before that point (and it's an MS hosted machine, so should be clean beforehand, and destroyed after.) Let me change the pipeline to install Pulumi on the host machine first, and I'll let you know how that gets on!

**Comment by jaxxstorm** [comment]
We are tracking this issue here: https://github.com/pulumi/pulumi/issues/4877

So I'm closing this to consolidate all reports into a single issue

**Comment by justinvp** [comment]
> Let me change the pipeline to install Pulumi on the host machine first, and I'll let you know how that gets on!

@CortalUX, did installing Pulumi before installing the Python dependencies address the issue?
