### ISSUE TITLE
Output<string> to string always give 'Pulumi.Output`1[System.String]'

### ISSUE THREAD

**Issue by atifgk** [pulumi/pulumi-azure#603]
```
public static void AddSqlRoles( Output<string> server)
        {
            using var connection = new SqlConnection($"Server={server.Name}");
            connection.Open();
            connection.Close();
        }
```

         connection = "Server=Pulumi.Output`1[System.String]"

**Comment by EvanBoyle** [comment]
Hi @atifgk,

An `Output` is an async future (similar to promises in javascript). To access the value within the output you need to use the `Apply` function. You can read more about that here: https://www.pulumi.com/docs/intro/concepts/programming-model/#apply

**Comment by atifgk** [comment]
@EvanBoyle i have tried Apply function as well but same result

**Comment by mikhailshilkov** [comment]
I'm thinking we should implement `ToString` function that would print a more helpful message. Opened https://github.com/pulumi/pulumi/issues/4824

**Comment by atifgk** [comment]
@mikhailshilkov i have tried Apply function as well but same output

`using var connection = new SqlConnection($"Server=tcp:{sqlServer.FullyQualifiedDomainName.Apply(a => a)};Initial Catalog={database.Name.Apply(a => a)};Persist Security Info=False;User ID={sqlUser.Apply(a => a)};Password={sqlPassword.Apply(a => a)};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");`


> Server=tcp:Pulumi.Output`1[System.String];Initial Catalog=Pulumi.Output`1[System.String];Persist Security Info=False;User ID=Pulumi.Output`1[System.String];Password=Pulumi.Output`1[System.String];MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30

**Comment by EvanBoyle** [comment]
@atifgk `.Apply` also returns a new output. If you want to print the value or access the raw value, you will need to do it from within the `Apply` callback.

**Comment by Trubador** [comment]
> @atifgk `.Apply` also returns a new output. If you want to print the value or access the raw value, you will need to do it from within the `Apply` callback.

Can you share code to do this in C#?
