### ISSUE TITLE
Create an azure-serverless package

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#61]
Just as we have the [AWS Serverless](https://github.com/pulumi/pulumi-aws-serverless) package, we will want the moral equivalent for Azure, to help wire up functions to existing resources in an event-driven style of programming.

**Comment by lukehoban** [comment]
This is being tracked in https://github.com/pulumi/pulumi-azure-serverless/pull/1.

**Comment by CyrusNajmabadi** [comment]
pre-alpha bits added in https://github.com/pulumi/pulumi-azure-serverless/pull/1
