### ISSUE TITLE
Refreshing a Resource Group with deleted resources fails

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#62]
If you manually delete a resource from your Azure Resource Group in the console, we should be able to recover simply by running `pulumi refresh`.  Unfortunately, doing so fails:

```
    error: refreshing urn:pulumi:joe-ts-func::azure-functions::azure:HttpFunction$azure:appservice/functionApp:FunctionApp::fn-app's state: rpc error: code = Unknown desc = refreshing urn:pulumi:joe-ts-func::azure-functions::azure:HttpFunction$azure:appservice/functionApp:FunctionApp::fn-app: Error making Read request on AzureRM Function App AppSettings "fn-app67f7247a": web.AppsClient#ListApplicationSettings: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/fn-app67f7247a' under resource group 'fn-rgfeb8e772' was not found."
```

Notice the relevant bit, wherein some Azure SDK failure occurs due to the deleted resource having gone missing: `The Resource 'Microsoft.Web/sites/fn-app67f7247a' under resource group 'fn-rgfeb8e772' was not found."`

I believe this must be due to some bug in the underlying resource provider.

**Comment by pgavlin** [comment]
This is fixed.
