### ISSUE TITLE
How to set SQL Azure firewall policies with Pulumi?

### ISSUE THREAD

**Issue by Aaronontheweb** [pulumi/pulumi-azure#626]
Whoops, hit enter before I had a chance to type in my issue.

How do you set Azure Firewall policies in Pulumi? At the moment, my SQL Azure database isn't accessible from within my AKS cluster and I would like to go about changing that so all of those resources appear on the same network.

**Comment by Aaronontheweb** [comment]
Edit: I should note that I am using the C# provider to do this

**Comment by leezen** [comment]
Have you had a look at https://www.pulumi.com/docs/reference/pkg/azure/sql/firewallrule/ by chance? It has an example as well.

**Comment by Aaronontheweb** [comment]
No I haven't! That is perfect - let me go try that out.

**Comment by Aaronontheweb** [comment]
Yep, that helped a lot! Creating a VNet rule and a ServiceEndpoint for the same subnet that my AKS cluster uses did the trick.
