### ISSUE TITLE
Azure Key Vault SKU - Pulumi uses "standard" whereas Azure is "Standard"

### ISSUE THREAD

**Issue by CalumJEadie** [pulumi/pulumi-azure#629]
I've found myself in something of a catch 22! Pulumi allows you to specify "standard" for a key vault SKU (but not Standard") whereas Azure uses "Standard". I've worked around to make an import work by ignoring "sku" but would be great to manage properly with Pulumi. Any ideas?

**Comment by mikhailshilkov** [comment]
I believe this is https://github.com/terraform-providers/terraform-provider-azurerm/issues/7254

**Comment by CalumJEadie** [comment]
Thanks @mikhailshilkov - is this a case of waiting for terraform to fix?

**Comment by mikhailshilkov** [comment]
Yes... There is a PR open for several weeks but I'm not sure why it's not merged.

**Comment by mikhailshilkov** [comment]
The upstream issue has been fixed a while ago, so closing this one too
