### ISSUE TITLE
Additional option for Network access on Container Registry

### ISSUE THREAD

**Issue by lbargery** [pulumi/pulumi-azure#635]
Hey,

Small one, but just span up an Azure Container Registry using Pulumi and even though I set my NetworkRuleSet up like this

```
NetworkRuleSet = new RegistryNetworkRuleSetArgs()
{
   DefaultAction = "Deny",
},
```

I found in Azure it said that "Allow public network access" was set to "Selected Networks". It seems like the additional level of moving this to "Disabled" (I am using private endpoints) is controlled by this flag in the ARM template:

```
"publicNetworkAccess": "Disabled"
```

Is this able to be replicated in Pulumi?

Thanks

**Comment by leezen** [comment]
Not yet -- this is tracked upstream in https://github.com/terraform-providers/terraform-provider-azurerm/issues/7334

**Comment by mikhailshilkov** [comment]
The upstream change has been resolved a while ago, so I'm closing this one as done
