### ISSUE TITLE
Application Insights samplingPercentage Null handling

### ISSUE THREAD

**Issue by chr15murray** [pulumi/pulumi-azure#639]
When attempting to import an Application Insights resource that was created via the Azure portal, Pulumi incorrectly suggest the value for `samplingPercentage` should be `0` when it is actually `null` in in the azure api output.

`null` in this instance is equivalent to 100 and not 0. After importing `pulumi preview` will show no required changes. 

Furthermore, when making a change such as adding Tags the `pulumi preview` now only shows the tags as being updated. However when running `pulumi up` the `samplingPercentage is updated from null to 0 which stops it accepting any application logs/metrics.

## Steps to reproduce
- Create an appinsights resource in the azure portal and note the resource id.
- Get the current config of the resource using the id from above
`az resource show --ids "/subscriptions/......"  -o json > before.json`
- Create a pulumi stack setup for azure and define the app insights object you wish to import.
```
const appInsights = new azure.appinsights.Insights("appInsights", {
    name: `exampleai`,
    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,
    applicationType: "web",
},{import:".....<resourceid>...."});
```

- Run Pulumi preview. You will get the response below despite them being equivalent.
```
warning: inputs to import do not match the existing resource; importing this resource will fail
    = azure:appinsights/insights:Insights: (import)
       ...
      ~ samplingPercentage: 0 => 100
```

- Update the resource definition and import successfully
```
const appInsights = new azure.appinsights.Insights("appInsights", {
    name: `exampleai`,
    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,
    applicationType: "web",
    samplingPercentage: 0
},{import:".....<resourceid>...."});
```

- run `pulumi preview` and confirm no changes are required
- Add tags to the resource and preview
```
const appInsights = new azure.appinsights.Insights("appInsights", {
    name: `exampleai`,
    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,
    applicationType: "web",
    samplingPercentage: 0,
   tags: { sometag: "value" }
},{import:".....<resourceid>...."});
```

- This will show the tags being added only. Apply the change

- Get the current config
`- Get the current config of the resource using the id from above
`az resource show --ids "/subscriptions/......"  -o json > after.json`

- Compare before and after json files and note the SamplingPercentage update among others that were not detailed.
```
diff before.json after.json
2c2
<   "etag": "\"1c006d8c-0000-0200-0000-5f1734410000\"",
---
>   "etag": "\"1c00e18d-0000-0200-0000-5f17351c0000\"",
15a16
>     "DisableIpMasking": false,
20a22
>     "Retention": "P90D",
22c24
<     "SamplingPercentage": null,
---
>     "SamplingPercentage": 0.0,
31c33,35
<   "tags": {},
---
>   "tags": {
>     "sometag": "value"
>   },
```

I'm logging the issue purely on the SamplingPercentage changing the behaviour and breaking appinsights. 

## Workaround
After importing the AppInsights resource remove the `samplingPercentage` line from the config or set it to 100. Applying this change will result the in the same functionality.

**Comment by mikhailshilkov** [comment]
I tried this today and did not get a diff. I'll close as fixed.
