### ISSUE TITLE
ProviderArgs now requires undocumented metadataHost

### ISSUE THREAD

**Issue by gpduck** [pulumi/pulumi-azure#642]
I just upgraded to @pulumi/azure 3.13.0 (from 3.6.0) and the ProviderArgs interface now requires metadataHost to be set, but this property does not appear on the [documentation page](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/#ProviderArgs).

Also according to the [Terraform Documentation](https://www.terraform.io/docs/providers/azurerm/index.html) that property is optional. Not sure if that is supposed to line up or not?

**Comment by stack72** [comment]
Hi @gpduck 

I will get this fixed up and released asap!

Paul
