### ISSUE TITLE
Naming restrictions for API Management APIs are too strict

### ISSUE THREAD

**Issue by Gerrit-K** [pulumi/pulumi-azure#644]
Similarly to #159 the naming restrictions for the `API` resource within the API Management are too strict. I get an error if I exceed 16 characters (24 - 8 random), which I believe is the (conservative) default value for all Pulumi resources. 

According to [the Azure docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftapimanagement) however, the maximum for this type should be 256. I can confirm that it's possible to manually create APIs with names of more than 24 characters from within the portal.

**Comment by stack72** [comment]
Hi @Gerrit-K 

Ok, now I understand what you mean, I am going to try and file a PR upstream to the Terraform provider we derive this provider from

I will also undo the change originally associated with this issue

Paul

**Comment by stack72** [comment]
ok, on further investigation @Gerrit-K 

The offending line isn't upstream it's actually https://github.com/pulumi/pulumi-azure/blob/master/provider/resource.go#L1947 🤦 

Looking at the impact of changing this now

Paul

**Comment by Gerrit-K** [comment]
@stack72 
Hey Paul,

well, yes, that's something from Pulumi and I believe I've read somewhere that this limit - while being very conservative - is necessary to avoid errors for cases when the limits are unknown or subject to change. The linked docs however describe many limits in great detail and I've seen a couple of resources in Pulumi where these limits are not accounted for. Ideally I would love to see all of them implemented, but I can also imagine that this might be a better fit for the upstream terraform provider (does it have those limits as well?).

**Comment by stack72** [comment]
Hi @Gerrit-K 

This PR #648 will fix the issue - you can see, it's quite easy to change these restrictions 

Hope this helps

Paul
