### ISSUE TITLE
Compilation errors for missing required values?

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure#660]
Is there a way to improve the developer experience for required values? For instance,

`ResourceGroupName` is required for many resources, but if I forget to add it, I don't get any feedback in the IDE like a warning or error. It's not until I run `pulumi up` (or similar), that I finally see I'm missing it.

It happens at the individual resource level as well. For instance, if I don't know what's required for a KeyVault resource and just create an empty `KeyVaultArgs`, the IDE is happy to let me. But if I then run `pulumi up`, it is going to complain that I am missing `ResourceGroupName`, then `SkuName`, then `TenantId`.

This is a long and annoying cycle.

Should required values be moved into the constructor to make this clear? 

```csharp
var keyVault = new KeyVault(name, resourceGroup.Name,
    new KeyVaultArgs(skuName, tenantId)
    {
        AccessPolicies = new[]
```

Are there better options?

**Comment by lukehoban** [comment]
I believe this is the same issue tracked in https://github.com/pulumi/pulumi/issues/3808?

**Comment by MisinformedDNA** [comment]
Thanks.
