### ISSUE TITLE
Cannot set "Deployment Slot Setting" for App Services

### ISSUE THREAD

**Issue by thomaslundgaard** [pulumi/pulumi-azure#662]
I am trying to set up App Settings and Connection Strings on some deployment slots in my App Service. In azure portal I can select a boolean option called "Deployment Slot Setting" for each App Setting or Connection String. I am unable to set this option through Pulumi.

There are similar options for Function Apps, which are also missing in Pulumi.

**Comment by leezen** [comment]
I think you're referring to https://www.pulumi.com/docs/reference/pkg/azure/appservice/slot/ and  https://www.pulumi.com/docs/reference/pkg/azure/appservice/functionappslot/

Going to close for now, but please re-open if that doesn't address your question.

**Comment by thomaslundgaard** [comment]
That is not what I'm referring to.

One or more App Settings or Connection Strings can be configured for each App Service Slot. This is done through [https://www.pulumi.com/docs/reference/pkg/azure/appservice/slot/#slotconnectionstring](https://www.pulumi.com/docs/reference/pkg/azure/appservice/slot/#slotconnectionstring).

On each of the App Settings or Connection Strings i want to be able to select "Deployment slot setting" through pulumi. See screenshot below.

![image](https://user-images.githubusercontent.com/121421/90114769-7b5df280-dd53-11ea-8f1a-0f1d32e9fa52.png)


@leezen  I am unable to reopen the issue, can you do it for me?

**Comment by leezen** [comment]
Sorry about my confusion and I see what you mean now. This is called `sticky` in the API and not yet supported in the provider. The upstream issue tracking this is https://github.com/terraform-providers/terraform-provider-azurerm/issues/1440

**Comment by Wtiben** [comment]
Is this currently possible yet?

**Comment by thomaslundgaard** [comment]
I do not know if this ever got implemented.

**Comment by Viehwoidler** [comment]
Sticky slot settings can be defined using resource [WebAppSlotConfigurationNames](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappslotconfigurationnames/).

**Comment by hurt1030** [comment]
> Sticky slot settings can be defined using resource [WebAppSlotConfigurationNames](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappslotconfigurationnames/).

@Viehwoidler Thank you!
