### ISSUE TITLE
CosmosDB autoscale

### ISSUE THREAD

**Issue by GoGoris** [pulumi/pulumi-azure#667]
I would like to set my CosmosDB to autoscale throughput, but this does not seem to be an option yet in the CosmosDB SqlDatabase or SqlContainer.

**Comment by leezen** [comment]
Tracked upstream in https://github.com/terraform-providers/terraform-provider-azurerm/issues/6164

**Comment by mikhailshilkov** [comment]
Shipped upstream a while ago
