### ISSUE TITLE
Azure Function RepoUri issue

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi-azure#671]
Hi, I got this error when updating the Azure Functions after migrated to the latest package `3.16.0`.
Error: `Code="BadRequest" Message="Operation not supported: RepoUrl VSTSRM is not supported."`

**Comment by mikhailshilkov** [comment]
Sounds like an issue upstream, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/8171

**Comment by baoduy** [comment]
I would like to close this issue as the workaround solution is run up with refresh option. Hope the upstream issue will be fixed soon.
Thanks
