### ISSUE TITLE
Associate Network Security Group to subnet during subnet creation

### ISSUE THREAD

**Issue by evgenyb** [pulumi/pulumi-azure#675]
This is more like feature request, rather than a bug.
My client has an Azure Policy that prevents creation of subnets without Network Security Group (further nsg) assigned to it. As of now, using Pulumi I need to create nsg, then create subnet and then use `SubnetNetworkSecurityGroupAssociation` to assign nsg to subnet.

What would be really nice is to have a possibility to assign NSG to subnet during creation of the subnet. Something like 

```csharp
var rg = new ResourceGroup("rg", ...);
var vnet = new VirtualNetwork("vnet", ...);
var nsg = new NetworkSecurityGroup("subnet", ...);

var subnet = new Subnet("subnet", new SubnetArgs
{
    ResourceGroupName = rg.Name,
    VirtualNetworkName = vnet.Name,
    AddressPrefix = "10.0.2.0/24",
    NetworkSecurityGroupId = nsg.Id   // <---- this doesn't exists today :)
});
```

**Comment by mikhailshilkov** [comment]
The corresponding upstream issue https://github.com/hashicorp/terraform-provider-azurerm/issues/20581 has been closed as won't do, so I'll apply the same here
