### ISSUE TITLE
LinuxVirtualMachine and LilzgaugeWebServerScalingSet - resource_name characters length limit

### ISSUE THREAD

**Issue by kuba-lilz** [pulumi/pulumi-azure#678]
Pulumi (v2.9.0) requires that `resource_name` for `pulumi_azure.compute.LinuxVirtualMachine is max 24 characters, including 8 characters suffix pulumi adds.`
This makes it very challenging to use any descriptive names at all, e.g. `production-server` is invalid for being one character too long.

Terraform doesn't have this limitation, and I routinely create 50+ characters names for virtual machines with it.
Googling a bit my understanding is 24 is a default value, but could be changed with a bit of work?
https://github.com/pulumi/pulumi-azure/pull/256/

Any chance of change for `LinuxVirtualMachines` and `LilzgaugeWebServerScalingSet` coming sometime soon?

**Comment by stack72** [comment]
Closed via #681
