### ISSUE TITLE
azure:monitoring/autoscaleSetting:AutoscaleSetting - increase resource_name limit beyond 24 characters

### ISSUE THREAD

**Issue by kuba-lilz** [pulumi/pulumi-azure#696]
Follow up request to #678

Could resource_name for autoscale settings also be increased?

**Comment by stack72** [comment]
Hi @kuba-lilz 

Any thoughts on what you believe the naming conventions for the name need to be for this? I can't find anything in the ARM naming document

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

**Comment by kuba-lilz** [comment]
@stack72 
Are you asking about what type of case and characters set name Azure accepts for auto scale settings resource?
Looking at our terraform scripts samples, I am reasonably sure it's alphanumerics and hyphens, e.g. `foo-and-bar`.

As for resource name length, which is what I hope would get an increase in Pulumi, we are currently using names up to 51 characters  long in our Terraform scripts without a hitch, whereas Pulumi only accepts up to 24 characters. I'm assuming 80 is the hard limit on Azure side, but hasn't confirmed this.

In the end what we hope to be able to do in Pulumi is to have descriptive resource names for scaling sets (which we already can, yay!), and be able to name scaling settings for a scaling set with `resource_name=scaling_set_name + "-autoscale"` or similar ^^;

**Comment by kuba-lilz** [comment]
Thank you!
