### ISSUE TITLE
Insights action group name too limiting

### ISSUE THREAD

**Issue by recumbent** [pulumi/pulumi-azure#703]
An action group: `Pulumi.Azure.Monitoring.ActionGroup`

Name limit is 260 from: [Naming rules and restrictions for Azure resources - Microsoft.Insights](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftinsights)

**Comment by recumbent** [comment]
Same problem for azure:monitoring/scheduledQueryRulesAlert:ScheduledQueryRulesAlert

I'm attempting to find a reference for the limit, but its not on the above page

**Comment by stack72** [comment]
@recumbent are you sure that is the correct name limit for ActionGroup?

**Comment by recumbent** [comment]
Confident but not certain - I will check via CLI and Web console.

There has to be a better way 🤔

**Comment by recumbent** [comment]
I'm sure now:
> Create or update action group
> Failed to create or update action group 'This is my action group name how long can it be8901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'. Error 'The provided resource name 'This is my action group name how long can it be8901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' has a length of '300' which exceeds the maximum length of '260'.'

**Comment by recumbent** [comment]
> @stack72 Same problem for azure:monitoring/scheduledQueryRulesAlert:ScheduledQueryRulesAlert
> 
> I'm attempting to find a reference for the limit, but its not on the above page

According to the UX: "This field has a limit of 128 characters."
