### ISSUE TITLE
Add support for Azure Stack

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-azure#71]
A new TF provider for Azure Stack was released earlier today - see https://www.terraform.io/docs/providers/azurestack/index.html.

We should be able to add support for that in a very similar manner to the existing Azure provider support.

We will probably want to follow the design in the TF provider of having this be a separate package - perhaps `@pulumi/azurestack`.

**Comment by stack72** [comment]
@lukehoban I think we should close this out - it would be a completely difference provider like it is in Terraform - what do you think?

**Comment by lukehoban** [comment]
I think this was intended to track creating a Pulumi provider mapped to the Azure Stack Terraform Provider.  I have not yet heard concrete demand for this - so I'm happy to close this out until we do.

**Comment by rauanmayemir** [comment]
I was bummed to discover azurestack works differently from azure.
There's a new terraform provider for azurestack: https://github.com/hashicorp/terraform-provider-azurestack.

Could this issue be re-opened?
