### ISSUE TITLE
Different resource name in preview plan and after deployment  

### ISSUE THREAD

**Issue by evgenyb** [pulumi/pulumi-azure#719]
How to reproduce:

1. Simple resource group definition 
```c#
var resourceGroup = new ResourceGroup("foobar");
```

2. Run `pulumi up` with details and then select `yes` to deploy

```bash
$ pup
Please choose a stack, or create a new one: dev
Previewing update (dev)

View Live: 

     Type                         Name           Plan
 +   pulumi:pulumi:Stack          pws-lab01-dev  create
 +   └─ azure:core:ResourceGroup  foobar         create

Resources:
    + 2 to create

Do you want to perform this update? details
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:dev::pws-lab01::pulumi:pulumi:Stack::pws-lab01-dev]
    + azure:core/resourceGroup:ResourceGroup: (create)
        [urn=urn:pulumi:dev::pws-lab01::azure:core/resourceGroup:ResourceGroup::foobar]
        [provider=urn:pulumi:dev::pws-lab01::pulumi:providers:azure::default_3_24_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        location  : "westeurope"
        name      : "foobar8c6de1f5"

Do you want to perform this update? yes
Updating (dev)

View Live: 

     Type                         Name           Status
 +   pulumi:pulumi:Stack          pws-lab01-dev  created
 +   └─ azure:core:ResourceGroup  foobar         created

Resources:
    + 2 created

Duration: 50s
``` 

3. Run `pulumi stack -i`

```bash
$ pulumi stack -i
Current stack is dev:
    Owner: evgenyb
    Last updated: 46 seconds ago (2020-10-06 13:36:33.0312218 +0200 CEST)
    Pulumi version: v2.11.2
Current stack resources (3):
    TYPE                                           NAME
    pulumi:pulumi:Stack                            pws-lab01-dev
    ├─ azure:core/resourceGroup:ResourceGroup      foobar
    │     ID: /subscriptions/.../resourceGroups/foobar2ae87716
    └─ pulumi:providers:azure                      default_3_24_0
          ID: a6ce109d-5aa0-4385-8472-d68ac3dc63ca

Current stack outputs (0):
    No output values currently in this stack

More information at: https://app.pulumi.com/evgenyb/pws-lab01/dev

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones
```

As you can see, the name of the resource shown at the plan is `foobar8c6de1f5`, but the actual resource group name is `foobar2ae87716`

**Comment by stack72** [comment]
Hi @evgenyb 

Please can you tell me what version of pulumi and pulumi-azure you are using for this?

Paul

**Comment by evgenyb** [comment]
Hi @stack72,

Pulumi version: v2.11.2
pulumi-azure: 3.24.0

**Comment by stack72** [comment]
Thanks @evgenyb 

I am seeing the sae behaviour

We can look into this

Paul

**Comment by stack72** [comment]
Hi @evgenyb 

So I discussed this with the team internally - this is actually intended behaviour as there is no state being saved between a preview and an apply

There is an issue open in pulumi/pulumi to allow applies of a preview plan which would solve the issue

I hope this answers your question - sorry that it may not be what you were hoping :/

P.

**Comment by evgenyb** [comment]
Hi Paul, 
I am fine with this behavior. I normally don't use autonamibg anyways, but during the workshop me and other attendee noticed that behavior and it looked a bit suspicious, so, I just wanted your team to know in case it's actually a bug :) Feel free to close this issue. 

Thanks
--
Evgeny

**Comment by stack72** [comment]
Thanks @evgenyb for being in contact about this!
