### ISSUE TITLE
Add support for creating a VPN Gateway subnet

### ISSUE THREAD

**Issue by scottmckenzie** [pulumi/pulumi-azure#72]
An Azure VPN Gateway requires a subnet named GatewaySubnet to work properly:
https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings#gwsub

Pulumi transforms all subnet names to lowercase and appends a random eight character string.  This should not happen for subnets named GatewaySubnet.

**Comment by lukehoban** [comment]
You should be able to set a `name` property on the Subnet to force that specific name to be used. When the name is left off, Pulumi provides a default with some randomness appended to ensure uniqueness by default. But in scenarios where a fixed name is required, that `name` property ought to enable full control.

**Comment by scottmckenzie** [comment]
I am setting the name property on the subnet.  Pulumi sets the name to lowercase and appends eight random characters.

Tested with both python and javascript and get the same result.  I believe it is this line that is the culprit:
https://github.com/pulumi/pulumi-azure/blob/28b906b7dfc3000a3eca2885613529cc9fa2203b/resources.go#L436-L441

**Comment by lukehoban** [comment]
I tried the following:

```javascript
const azure = require("@pulumi/azure");

let resourceGroup = new azure.core.ResourceGroup("server", {
    location: "West US",
});

let network = new azure.network.VirtualNetwork("server-network", {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
    addressSpaces: ["10.0.0.0/16"],
    subnets: [{
        name: "default",
        addressPrefix: "10.0.1.0/24",
    }],
});

let subnet = new azure.network.Subnet("server-subnet", {
    name: "thenameipicked",
    resourceGroupName: resourceGroup.name,
    virtualNetworkName: network.name,
    addressPrefix: "10.0.2.0/24",
});

exports.subnetName = subnet.name;
```

The result was subnets named `default` and `thenameipicked`:

![screen shot 2018-06-25 at 9 04 33 am](https://user-images.githubusercontent.com/223467/41861704-d79b0f10-7856-11e8-984e-29b7f26af840.png)

Do you have a code snippet you could share to highlight the issue you are seeing?

**Comment by scottmckenzie** [comment]
I am seeing the same results as you.  I was confusing the resource name ("server-subnet" in your example) with the name property.  I hadn't seen any examples using that property and IntelliSense told me the first parameter was called name.

Sorry for wasting your time.
