### ISSUE TITLE
Postgres Connections docs page is missing name parameter in examples

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azure#721]
Reference: https://www.pulumi.com/docs/reference/pkg/azure/postgresql/configuration/

The examples on this page are missing the "name" property in the configuration creation.
This causes the examples to fail since Pulumi is defaulting to using the name of the configuration itself - which of course is not the name of a postgres configuration parameter.
Therefore, the examples should be changed as shown in this example: 
```
const exampleConfiguration = new azure.postgresql.Configuration('mitchCfg', {
  name: 'backslash_quote',
  resourceGroupName: exampleResourceGroup.name,
  serverName: exampleServer.name,
  value: 'on',
});
```

**Comment by stack72** [comment]
The issue here is that we cannot use autonaming for this resource as the name of the resource MUST BE a valid postgres name

So we need to disable autonaming for this resource
