### ISSUE TITLE
FYI: error refreshing AKS cluster because of Terraform provider issue

### ISSUE THREAD

**Issue by Josh-Tilles** [pulumi/pulumi-azure#735]
(Since the problem's likely upstream, please just consider this issue a heads-up.)

The specific error text I see when running `pulumi preview` in my TypeScript project is:

    flattening `default_node_pool`: The Default Agent Pool "" was not found

The relevant Terraform AzureRM provider issues that I found are:
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/8869
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/7813

FWIW, in my own project, I was able to make progress by downgrading to version 3.8.0 of `@pulumi/azure`.

**Comment by mikhailshilkov** [comment]
Since upstream issues are closed, I'll go ahead and close this issue too
