### ISSUE TITLE
Azure SqlServer - Invalid parameter 'storageEndpoint'

### ISSUE THREAD

**Issue by andlju** [pulumi/pulumi-azure#745]
Getting this error message when creating a new Azure Sql Server:

```
__ (azure:sql:SqlServer)
error: 1 error occurred:
	* creating urn:pulumi:local::__::azure:sql/sqlServer:SqlServer::__: Error issuing create/update request for SQL Server "__" Blob Auditing Policies(Resource Group "__"): sql.ExtendedServerBlobAuditingPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DataSecurityInvalidUserSuppliedParameter" Message="Invalid parameter 'storageEndpoint'. Value should be a blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net)."
```

After some googling it appears that this is a regression in the Azure Api:
https://github.com/Azure/azure-rest-api-specs/issues/11271

As a workaround I added the following to all SqlServer and Database entries:

```
        extendedAuditingPolicy: {
            storageEndpoint: storageAccount.primaryBlobEndpoint,
            storageAccountAccessKey: storageAccount.primaryAccessKey,
            retentionInDays: 1
        },
```

I see that Terraform have a temporary workaround merged already:
https://github.com/terraform-providers/terraform-provider-azurerm/pull/8975

**Comment by stack72** [comment]
Hi @andlju 

Apologies here - this is actually fixed in https://github.com/pulumi/pulumi-azure/pull/744 and will get merged and released before Monday

Paul
