### ISSUE TITLE
GetFunctionAppHostKeysArgs should take Input<string> instead of string

### ISSUE THREAD

**Issue by goutham-pai-hc** [pulumi/pulumi-azure#748]
I'm trying to setup a situation in which I can provision a Function App and pull its hostkey for use in configuring some other resource in the same stack. I think `GetFunctionAppHostKeys` can be used to achieve this. However, it seems like the `GetFunctionAppHostKeysArgs` type expects strings for the resource group name and the functionApp name. This means that I cannot pass values of type `Output<string>` into the args.. This is problematic since a lot of values that I work with in Pulumi are of type `Output<T>`. Can I get some guidance on this?

**Comment by justinvp** [comment]
The typical way to handle this is to use [`Apply`](https://www.pulumi.com/docs/intro/concepts/programming-model/#apply) on the `Output<string>` and call `GetFunctionAppHostKeys` inside the `Apply`, where the value will be a `string`.

**Comment by goutham-pai-hc** [comment]
I suppose that's true. Is there a concern it could get unwieldy to be using Output<T>.Apply() all over the place? 
Anyway, I ended up doing this to set things up:
```
// get node function info
var hostKeysArgs = Output
    .Tuple(functionApp.Name, resourceGroup.Name)
    .Apply(t => new GetFunctionAppHostKeysArgs()
    {
        Name = t.Item1,
        ResourceGroupName = t.Item2
    });

var hostKeys = hostKeysArgs.Apply(async (x) => await GetFunctionAppHostKeys.InvokeAsync(x));
var defaultFunctionKey = hostKeys.Apply(result => result.DefaultFunctionKey)
```

**Comment by justinvp** [comment]
For posterity, there's now a cleaner way to do this:

```c#
var defaultFunctionKey = GetFunctionAppHostKeys.Invoke(new()
{
    Name = functionApp.Name,
    ResourceGroupName = resourceGroup.Name,
}).Apply(result => result.DefaultFunctionKey);
```
