### ISSUE TITLE
It's not possible to create a CDN Endpoint with a DeliveryRule that matches "Any"

### ISSUE THREAD

**Issue by nathanwinder-perficient** [pulumi/pulumi-azure#757]
It's not possible to create a CDN Endpoint with a DeliveryRule that matches "Any". Pulumi validation requires a Match List but azure does not allow a match list. 

``` csharp
 var endpoint = new Endpoint(n.CdnEndpointName(name), new EndpointArgs
            {
                ResourceGroupName = resourceGroupName,
                ProfileName = cdnProfile.Name,
                OriginHostHeader = storageAccount.PrimaryWebHost,
                Origins = new List<EndpointOriginArgs>
                {
                    new EndpointOriginArgs
                    {
                        Name = "blobstorage",
                        HostName = storageAccount.PrimaryWebHost
                    }
                },
                DeliveryRules = new EndpointDeliveryRuleArgs
                { 
                    Name = "deeplinkredirect",
                    Order = 1,
                    UrlFileExtensionConditions = new EndpointDeliveryRuleUrlFileExtensionConditionArgs
                    {
                        MatchValues = new InputList<string>(),
                        Operator = "Any",
                        NegateCondition = true,
                    },
                    UrlRewriteAction = new EndpointDeliveryRuleUrlRewriteActionArgs
                    {
                        SourcePattern = "/",
                        Destination = "/"
                    }
                }
            });
```

Updating (test):
     Type                            Name                  Status                  Info                                      pulumi:pulumi:Stack             Test.Proj.Infra-test  **failed**              1 error                               +   ├─ azure:cdn:Endpoint           app-spa-cdn-ep        **creating failed**     1 error                               +   └─ azure:appservice:AppService  app-app-api           created                                                      
Diagnostics:
  azure:cdn:Endpoint (app-spa-cdn-ep):
    error: Error waiting for CDN Endpoint "app-spa-cdn-ep78bd5ab" (Profile "app-spa-cdn290c7b0" / Resource Group "rg-appef85df78") to finish creating: Code="BadRequest" Message="{\"ErrorMessage\":\"**Invalid RulesEngineConfig: (Match value(s) must not be provided for Operator 'Any'**).\"}"

...

Previewing update (test):
     Type                   Name                  Plan       Info                                                            pulumi:pulumi:Stack    Test.Proj.Infra-test             1 error                                                     +   └─ azure:storage:Blob  index.html            create                                                                
Diagnostics:
  pulumi:pulumi:Stack (Test.Proj.Infra-test):
    error: Running program 'C:\repos\prft\at-rest-test\Test.Proj.Infra\bin\Debug\netcoreapp3.1\Test.Proj.Infra.dll' failed with an unhandled exception:
    System.ArgumentNullException: [Input] **Pulumi.Azure.Cdn.Inputs.EndpointDeliveryRuleUrlFileExtensionConditionArgs._matchValues is required but was not given a value (Parameter '_matchValues')**
...
Previewing update (test):
     Type                   Name                  Plan     Info                                                              pulumi:pulumi:Stack    Test.Proj.Infra-test                                                                             └─ azure:cdn:Endpoint  app-spa-cdn-ep                 1 error                                                      
Diagnostics:
  azure:cdn:Endpoint (app-spa-cdn-ep):
    error: azure:cdn/endpoint:Endpoint resource 'app-spa-cdn-ep' has a problem: **delivery_rule.0.url_file_extension_condition.0.match_values: attribute supports 1 item as a minimum, config has 0 declared**

**Comment by nathanwinder-perficient** [comment]
I can't be sure but according to this question on stackoverflow "not any" is not supported for Extension matches. So this may be a non-issue. https://stackoverflow.com/questions/58914446/azure-cdn-microsoft-standard-rules-engine-rewrite-url-for-single-page-applicatio

**Comment by mikhailshilkov** [comment]
Thank you for reporting!
This is an issue from the upstream provider, let's track it here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8770
We'll get the fix as soon as it's released upstream, so I'll close this issue here
