### ISSUE TITLE
Associate existing Security Group with Network Interface on creation

### ISSUE THREAD

**Issue by sindre-nistad** [pulumi/pulumi-azure#764]
Hi,
Is there a way to create a network interface, and have it associated / assigned to an existing security group?

My use case is thus;
A customer I work for require all network interfaces created in Azure has a security group.
This is enforced though a policy assignment.
Through a separate process, I have an existing vnet, and subnet (which is already assigned to a security group).
I'd like the network interface to inherit the existing security group of the subnet.

_example code_

```python
import pulumi_azure as azure

name = "resource-prefix"

resource_group_name = "<Company subscription>-network"

subnet = azure.network.get_subnet(
    name="<Company subscription>-subnet",
    virtual_network_name="<Company subscription>-vnet",
    resource_group_name=resource_group_name,
)

network_interface = azure.network.NetworkInterface(
    f"{name}:server-nic",
    ip_configurations=[
        azure.network.NetworkInterfaceIpConfigurationArgs(
            name="ip-config",
            private_ip_address_allocation="Dynamic",
            subnet_id=subnet.id,
        ),
    ],
    resource_group_name=resource_group_name,
)

nic = azure.network.NetworkInterfaceSecurityGroupAssociation(
    f"{name}:server-nic:sg",
    network_interface_id=network_interface.id,
    network_security_group_id=subnet.network_security_group_id,
)
```

This code fails at the creation of `network_interface`, due to policy assignment.

**Comment by mikhailshilkov** [comment]
Apologies for never responding to this question.

I think the answer is "no". The policy would probably need to change to account for this.

Since the issue is three years old, I'll go ahead and close it.
