### ISSUE TITLE
Import of existing storage account blob container fails

### ISSUE THREAD

**Issue by KatoStoelen** [pulumi/pulumi-azure#767]
**dotnet SDK (Pulumi.Azure v3.30.1)**

Having issues importing existing storage account blob containers.

Running `pulumi preview` with the following code:

```csharp
_ = new Pulumi.Azure.Storage.Container(
    "[container_name]",
    new ContainerArgs
    {
        Name = "[container_name]", // Disable auto-naming
        StorageAccountName = "[storage_account]",
        ContainerAccessType = "private"
    },
    new CustomResourceOptions
    {
        ImportId = "/subscriptions/[subscription_id]/resourceGroups/[resource_group]/providers/Microsoft.Storage/storageAccounts/[storage_account]/blobServices/default/containers/[container_name]"
    });
```

yields:

```console
Preview failed: resource '/subscriptions/[subscription_id]/resourceGroups/[resource_group]/providers/Microsoft.Storage/storageAccounts/[storage_account]/blobServices/default/containers/[container_name]' does not exist
```

Copy-pasting the resource ID from the error message into the Azure CLI `az resource show --ids [resource_id_from_error]` confirms that the resource does indeed exist:

```json
{
  "id": "/subscriptions/[subscription_id]/resourceGroups/[resource_group]/providers/Microsoft.Storage/storageAccounts/[storage_account]/blobServices/default/containers/[container_name]",
  "name": "[container_name]",
  "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
  ...
}
```

Tested with several different blob containers.

**Comment by mikhailshilkov** [comment]
Hi @KatoStoelen apologies for the slow response.

Storage containers are managed via the data plane API, which means their IDs aren't based on ARM paths. Storage container ID should be in the format of `https://mystorageaccount.blob.core.windows.net/mycontainer`.

You could create a sample container with Pulumi and then inspect its ID by looking it up in the output of `pulumi stack export`. This way you can discover the ID formats if in doubt.

**Comment by KatoStoelen** [comment]
I see. Thanks for feedback @mikhailshilkov ! Was able to import it using that format.

**Comment by mikhailshilkov** [comment]
To add to that, we've just rolled out an extra section in the docs that shows an example of import command usage. The example also contains the ID format: https://www.pulumi.com/docs/reference/pkg/azure/storage/container/#import
