### ISSUE TITLE
Create an "Azure reference architecture" example

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#77]
We agreed recently, when talking to a recent customer, to create an "Azure reference architecture" example.  This would simply provision the basic networking components and Kubernetes cluster -- [ACS Engine](https://github.com/Azure/acs-engine)-like -- and then deploy some services on top.

Eventually, we know we want a more first class ACS Engine component, but to get started we can probably just import it as an ARM template.  We also want to demonstrate deploying Helm charts, but until we have https://github.com/pulumi/pulumi-kubernetes/issues/54, we can simply deploy Kubernetes resources manually atop our provisioned cluster.

We agreed to get back to the customer in about two weeks' time, so this should go early in M16.

**Comment by lukehoban** [comment]
This issue was moved to pulumi/customer-azurespeech#1
