### ISSUE TITLE
Duplicate resource URN static-website

### ISSUE THREAD

**Issue by remojansen** [pulumi/pulumi-azure#773]
I'm using `@pulumi/azure"3.30.1` as:

```ts
this.storageAccount = new azure.storage.Account(name, {
      resourceGroupName: this.resourceGroup.name,
      accountReplicationType: "LRS",
      accountTier: "Standard",
      accountKind: "StorageV2",
      staticWebsite: {
        indexDocument: "index.html",
        error404Document: "404.html",
      },
});
```

And I'm getting:

>  Duplicate resource URN 'urn:pulumi:dev::xxxxx::static-website::xxxxx'; try giving it a unique name

I have tried to delete the resources in azure and the stack in Pulumi. I have also tried using a randomly generated name but it seems like somehow it still remembers the static-website name.

**Comment by mikhailshilkov** [comment]
Hi @remojansen 
Any chance you could share your full program? It sounds like there is another resource with the same logical name that you create in your program. This is not about the name in Azure, it's about `name` - the first parameter in `azure.storage.Account(name,`.

**Comment by remojansen** [comment]
Hi, @mikhailshilkov thanks for your answer I just noticed that I had two classes extending `ComponentResource` with the same name passed to the `super`constructor.
