### ISSUE TITLE
AutoscaleSetting recurrence does not allow specifying an end time

### ISSUE THREAD

**Issue by reddyalready** [pulumi/pulumi-azure#774]
`Azure.Monitoring.Inputs.AutoscaleSettingProfileRecurrenceArgs` does not seem to allow specifying an end time (or only allows specifying intervals), and one is not specified in the [example](https://www.pulumi.com/docs/reference/pkg/azure/monitoring/autoscalesetting/#repeating-on-weekends):

```
Recurrence = new Azure.Monitoring.Inputs.AutoscaleSettingProfileRecurrenceArgs
                    {
                        Frequency = "Week",
                        Timezone = "Pacific Standard Time",
                        Days = 
                        {
                            "Saturday",
                            "Sunday",
                        },
                        Hours = 
                        {
                            12,
                        },
                        Minutes = 
                        {
                            0,
                        },
                    },
```

The screenshot below from Azure Portal allows specifying two values.

![image](https://user-images.githubusercontent.com/7541378/100518259-62edd880-3188-11eb-80f5-1a4a0aca67e1.png)

Please let me know if I'm missing something obvious!

**Comment by stack72** [comment]
Hi @reddyalready 

There is no endDate as part of recurrence

There is an endDate as part of fixedDate

https://www.pulumi.com/docs/reference/pkg/azure/monitoring/autoscalesetting/#autoscalesettingprofile

Paul

**Comment by reddyalready** [comment]
Taking a look at the JSON for the scaling settings in Azure Portal, it seems there is indeed only one value in `hours` and `minutes`, so you are right. I think the UI works out and "end" from other scale conditions that are present.

I will close this issue now - thank you for your quick response!
