### ISSUE TITLE
Pulumi and AKS with EnableAutoScaling on

### ISSUE THREAD

**Issue by evgenyb** [pulumi/pulumi-azure#780]
We have experienced an interesting (and actually expected) pulumi behavior today with regards to AKS resource with `EnableAutoScaling` set to true.

1. 2 days ago we provisioned AKS cluster with 5 nodes pool and `EnableAutoScaling` set to `true`.
2. There were no workload deployed to this cluster last 2 days.
3. Today, when we updated stack where AKS is deployed, deployment failed with the following error message
```txt
updating urn:pulumi:uat-blue::foo-bar::azure:containerservice/kubernetesCluster:KubernetesCluster::foo-bar-aks: expanding `default_node_pool`: cannot change `node_count` when `enable_auto_scaling` is set to `true`
```

Checked the AKS cluster pool size and it was 2 nodes. Basically, since there is no workload at the cluster, it scaled down to 2 nodes. Our configuration, of course, still have 5 nodes, so pulumi tried to update cluster, but failed because `EnableAutoScaling` is set to true.

I think that if AKS cluster is configured with `EnableAutoScaling` and is already provisioned, `node_count` at the pool level can be ignored...

**Comment by leezen** [comment]
This makes sense and thank you for pointing it out. I'm not sure if you've tried this yet, but I assume if you use [`IgnoreChanges`](https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges) on the `NodeCount` property this works? Separately, it does seem like that ignoring the field should be automatically applied when setting `EnableAutoScaling`.

**Comment by evgenyb** [comment]
Thanks @leezen! Adding 
```c#
IgnoreChanges =
{
    "defaultNodePool.nodeCount"
}
```

did the trick :) Please feel free to close this issue

**Comment by leezen** [comment]
I should probably also note that I believe if you use the `pulumi-azure-nextgen` provider, you don't need this workaround because the ARM API ignores `count` when autoscaling is enabled: https://github.com/Azure/AKS/issues/1627#issuecomment-642835250
