### ISSUE TITLE
Unable to downgrade to previous terraform provider version v2.33.0 whereas I downgraded to @pulumi/azure v3.28.0

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure#783]
Hello,

I’m trying to debug an issue introduced by the  `terraform azurerm - v2.34.0` provider.

## Context

In my project, I got the following error:
 ```
error: azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace resource 'log-f-stack-s-a-sb' has a problem: expected daily_quota_gb to be at least (0.000000), got -1.000000
The daily_quota_gb property was not present beforeterraform azurerm v2.34.0 so I wonder why I still got this error.
```

After analysis, this was a terraform regression which has been introduced in terraform `v2.36.0` by this [commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/07938e516ee958d31c98c34dbdaec120ccbad255)

And code related to `daily_quota_gb` property  has been introduced in terraform `v2.34.0` by this [commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/539b9e33c7191a2205ab836b8b4d328219ece7b8)

So I try do downgrade to terraform provider version v2.33.0 by downgrading to @pulumi/azure v3.28.0 (According to [pulumi-azure CHANGELOG.md](https://github.com/pulumi/pulumi-azure/blob/master/CHANGELOG.md) )

After that, I still got the same error message
```
    error: azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace resource 'log-f-stack-s-a-sb' has a problem: expected daily_quota_gb to be at least (0.000000), got -1.000000
The daily_quota_gb property was not present beforeterraform azurerm v2.34.0 so I wonder why I still got this error.
```

# Issue

After having downgraded to @pulumi/azure v3.28.0  I still got the error :thinking_face:

# Tests

I created a new pulumi project (@pulumi/azure v3.32.0) with a new `AnalyticsWorkspace` resource from scratch and I was able to reproduce the error message.
Then I downgraded to @pulumi/azure v3.28.0 and I didn’t have the error anymore :+1:

The only difference I see is that in my real project the AnalyticsWorkspace resource already exists.
Do you have any idea?

# Debug

I set the verbose to `9` and got this:
```
I1207 14:37:59.165317   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: __defaults={[{dailyQuotaGb} {internetIngestionEnabled} {internetQueryEnabled} {location}]}
I1207 14:37:59.165358   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: dailyQuotaGb={-1}
I1207 14:37:59.165376   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: internetIngestionEnabled={true}
I1207 14:37:59.165390   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: internetQueryEnabled={true}
I1207 14:37:59.165403   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: location={francecentral}
I1207 14:37:59.165413   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: name={log-f-stack-s-a-sb-yh}
I1207 14:37:59.165439   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: resourceGroupName={rg-cloud-platform}
I1207 14:37:59.165465   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: retentionInDays={30}
I1207 14:37:59.165488   71348 rpc.go:247] Unmarshaling property for RPC[Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb).inputs]: sku={PerGB2018}
I1207 14:37:59.165509   71348 provider_plugin.go:574] Provider[azure, 0xc0013b7c80].Check(urn:pulumi:sandbox::foundations::maif:subscription$azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace::log-f-stack-s-a-sb) success: inputs=#9 failures=#1
I1207 14:37:59.165530   71348 eventsink.go:86] eventSink::Error(<{%reset%}>azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace resource 'log-f-stack-s-a-sb' has a problem: expected daily_quota_gb to be at least (0.000000), got -1.000000<{%reset%}>)
```

I don’t understand why I got the error after having downgrade to @pulumi/azure v3.28.0. 
Do you have any idea? 
How can I debug this?

Discussion on slack: https://pulumi-community.slack.com/archives/CRVK66N5U/p1607345666305100

**Comment by leezen** [comment]
Pulumi will attempt to use the version of the plugin associated with the version of the provider that's recorded in your state. Since you created the resource with the v3.32 version of the provider, it'll use that plugin as well. One option would be to attempt to manually alter your state by doing a `pulumi stack export`, modifying the provider version, then reimporting that state via `pulumi stack import`

Another workaround could be to rename the directory in `.pulumi/plugins` so that v3.32 actually points to a v3.28 binary.

**Comment by boillodmanuel** [comment]
Hi @leezen ,
Okay, that explains why we got this error.
But I don't understand exactly how and which provider version is used during pulumi operations. That may need to be documented a bit more.

As far as I know, there are 2 location that declare versions, and the version could be different:
- the one declared in dependencies (`package-lock.json` in ts)
- the one stored in the state

So I wonder which one is used depending on the pulumi operation:
- `pulumi preview` and `pulumi up` (we may need to distinguish `data sources` and `resources` which are not executed at the same time or with the same provider version?) 
- `pulumi refresh`

And when is the state updated to reflect the real provider version (the one declared in dependencies)?

**Comment by leezen** [comment]
This is something we could definitely improve in our documentation on plugin versioning (cc @davidwrede).

To answer your question above, when performing a refresh, pulumi will use the provider plugin associated with the resource in state. When writing the resource, pulumi will use the provider specified in the program (i.e. what is declared in dependencies).

**Comment by boillodmanuel** [comment]
I didn't mentioned it, but I got the error above during a `pulumi up`, so pulumi should somehow use the provider plugin associated with the resource in state during a `pulumi up`. Or I should miss something

**Comment by leezen** [comment]
When you say during `pulumi up` is it happening during the preview portion of the up? During the preview, the provider will perform a read, and I believe that will use the plugin version associated with state.

**Comment by boillodmanuel** [comment]
Yes, it's during the preview phase.

At first thought, I wonder why preview (and refresh) is not using the version declared in the dependencies, but it may be the same as in the terraform side.
That's said, thanks for the explanation.

You can close this issue if you think there is nothing else to do with.

**Comment by boillodmanuel** [comment]
Hello,
I just tried to apply the workaround today, and it didn't work but I think I figured out why.

In my stack I've got several Azure Provider (to manage resources in several subscriptions).

In the exported stack, I can see the default provider got a version whereas the custom provider didn't have one, and I can pass the version in Provider Arguments.

**Default provider:**
```json
{
    "urn": "urn:pulumi:prod::foundations::pulumi:providers:azure::default_3_19_0",
    "custom": true,
    "id": "<hidden>",
    "type": "pulumi:providers:azure",
    "inputs": {
        "clientId": "<hidden>",
        "clientSecret": "<hidden>",
        "environment": "public",
        "location": "FranceCentral",
        "subscriptionId": "<hidden>",
        "tenantId": "<hidden>",
        "version": "3.19.0"
    },
    "outputs": {
        "clientId": "<hidden>",
        "clientSecret": "<hidden>",
        "environment": "public",
        "location": "FranceCentral",
        "subscriptionId": "<hidden>",
        "tenantId": "<hidden>",
        "version": "3.19.0"
    }
},
```

**Custom provider:**
```json
{
    "urn": "urn:pulumi:prod::foundations::pulumi:providers:azure::azure-provider-custom-1",
    "custom": true,
    "id": "6e170709-472a-4814-96b6-e8e85f41964c",
    "type": "pulumi:providers:azure",
    "inputs": {
        "clientId": "<hidden>",
        "clientSecret": "<hidden>",
        "environment": "public",
        "metadataHost": "",
        "metadataUrl": "",
        "skipProviderRegistration": "false",
        "storageUseAzuread": "false",
        "subscriptionId": "<hidden>",
        "tenantId": "<hidden>",
    },
    "outputs": {
        "clientId": "<hidden>",
        "clientSecret": "<hidden>",
        "environment": "public",
        "metadataHost": "",
        "metadataUrl": "",
        "skipProviderRegistration": "false",
        "storageUseAzuread": "false",
        "subscriptionId": "<hidden>",
        "tenantId": "<hidden>",
    },
    "parent": "urn:pulumi:prod::foundations::pulumi:pulumi:Stack::foundations-prod",
    "propertyDependencies": {
        "clientId": null,
        "clientSecret": null,
        "environment": null,
        "metadataHost": null,
        "metadataUrl": null,
        "skipProviderRegistration": null,
        "storageUseAzuread": null,
        "subscriptionId": null,
        "tenantId": null
    }
},
```

It seems that without the version, the custom provider use the latest version available in the `.pulumi/plugins` folder.
I dropped the whole folder and it worked 👍 ! Pulumi was using the provider 3.19 for default and custom provider.

So I'm able to use that workaround to make it working, but as soon as I will use another project with a greater version, the workaround will stop working. I'll open a dedicated issue for that.

**Comment by boillodmanuel** [comment]
*previous comment updated by replacing `I can pass` by `I can not pass`
