### ISSUE TITLE
Webapp autoscale statusCode=409 error when provisioning multiple webapps

### ISSUE THREAD

**Issue by shahiddev** [pulumi/pulumi-azure#787]
If I'm trying to provision multiple App services in a loop and I'm configuring autoscale settings on them in each iteration, however I get this error

`insights.AutoscaleSettingsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>`

This only happens if I'm creating multiple webapps in the loop, so suggests a possible race condition.

The autoscale setting name is unique.

Repro project available here: https://github.com/shahiddev/pulumi-autoscale-bug

This happens in latest Pulumi.Azure nuget (3.33.0)

**Comment by mikhailshilkov** [comment]
I'm curious - nowhere in the `AutoscaleSetting` definition are you using `app`, only `appServicePlan`. Why do you need to create it N times then?

**Comment by shahiddev** [comment]
Ah good spot, I had refactored this from something that was previously using different app service plans. 

As you've highlighted don't need more than one scale setting per app service plan so I can sort that out (although I'm pretty sure this was working before, albeit quite a while ago).

I'll close this 

Thanks @mikhailshilkov
