### ISSUE TITLE
Unable to disable compression on Azure CDN

### ISSUE THREAD

**Issue by fpoliquin** [pulumi/pulumi-azure#794]
Nothing happens when setting azure.cdn.Endpoint.isCompressionEnabled to false after being true. The compression setting in Azure remains active no matter what I try.

**Comment by mikhailshilkov** [comment]
I believe this is tracked upstream in https://github.com/hashicorp/terraform-provider-azurerm/issues/22326 and has been fixed today. We should get the fix with the next provider release (5.48.0).
