### ISSUE TITLE
Breaking change - resource id seems to have changed for Azure SQL Administrators

### ISSUE THREAD

**Issue by scp-mb** [pulumi/pulumi-azure#798]
Using Pulumi version 2.16.0 with Pulumi.Azure 3.40.0

It seems the resource id for SQL AD administrators has changed, which breaks `pulumi refresh` operations

The previous format was:
`/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Sql/servers/<sqlServerName>/activeDirectory/administrator`

And the documentation specifies 
`/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myresourcegroup/providers/Microsoft.Sql/servers/myserver/administrators/activeDirectory`

When attempting a refresh, this error is thrown:
`error: Preview failed: refreshing urn:pulumi:<stackname>::<projectName>::azure:sql/activeDirectoryAdministrator:ActiveDirectoryAdministrator::<resourceName>: ID was missing the `administrators` element`

**Comment by leezen** [comment]
From the git history, it doesn't appear this ID has changed in some time. What provider version are you upgrading from that you're seeing this?

**Comment by scp-mb** [comment]
v3.33.2 I believe, we try to keep it up to date within a few days of a new version being released. The resource would have been imported somewhere around v3.24.0

I've had a bit of a closer look and our other stacks don't appear to be affected. I suspect I know how it got into that state which is that stack was the only one where that resource already existed, and was imported using the `activeDirectory/administrator` path for the ID. The others were created directly via Pulumi.

I've since deleted the resource from the stack and reimported it with the correct resource path, but if there's multiple ways of importing resources that may still be an issue.

**Comment by leezen** [comment]
Thanks for clarifying the situation. The import ID you mention is interesting. I don't think there's any ID validation except from trying to perform the read against the resource at import time. Looking at the code though, I'm also not sure how this was possible as the read for this resource seems to always have used `administrators` (https://github.com/simongh/terraform-provider-azurerm/blame/a02d35a7638a972455b9f8ff268cbe43a0455cd4/azurerm/resource_arm_sql_administrator.go#L102)

Any chance you happen to have the way you successfully imported this w/the incorrect ID available?

**Comment by scp-mb** [comment]
Sure, going back to the earliest point I can find in our git history for that resource it was imported using the following (redacted information where necessary)

```new Pulumi.Azure.Sql.ActiveDirectoryAdministrator("sql-ad-admin",
            new Pulumi.Azure.Sql.ActiveDirectoryAdministratorArgs()
            {
                ResourceGroupName = resourceGroupName,
                TenantId = <tenantId>,
                ObjectId = <objectId>,
                ServerName = sqlServer.Name,
                Login = "SQL Admins"
            },
            new CustomResourceOptions
            {
                ImportId = $"/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Sql/servers/<sqlServerName>/activeDirectory/administrator"
            });

**Comment by scp-mb** [comment]
Small update, it turns out we have one other stack that has the same type of resource imported in the same way. A refresh was working fine on that, but I've just done a `pulumi up` for some unrelated appservice changes, and now running a `pulumi refresh` gives the same error.

When running a refresh does it use the provider version from when `pulumi up` was last run? If so, that might explain why it wasn't erroring until just now, even though the project was updated to a newer version

**Comment by scp-mb** [comment]
If it helps, here's a redacted version of what is in the stack whilst the failure is present:

```{
    "urn": "urn:pulumi:<stackName>::<projectName>::azure:sql/activeDirectoryAdministrator:ActiveDirectoryAdministrator::sql-ad-admin",
    "custom": true,
    "id": "/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Sql/servers/<sqlServerName>/activeDirectory/administrator",
    "type": "azure:sql/activeDirectoryAdministrator:ActiveDirectoryAdministrator",
    "inputs": {
        "__defaults": [],
        "login": "SQL Admins",
        "objectId": "<objectId>",
        "resourceGroupName": "<resourceGroupName>",
        "serverName": "<sqlServerName>",
        "tenantId": "<tenantId>"
    },
    "outputs": {
        "__meta": "{\"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0\":{\"create\":1800000000000,\"delete\":1800000000000,\"read\":300000000000,\"update\":1800000000000}}",
        "id": "/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Sql/servers/<sqlServerName>/activeDirectory/administrator",
        "login": "SQL Admins",
        "objectId": "<objectId>",
        "resourceGroupName": "<resourceGroupName>",
        "serverName": "<sqlServerName>",
        "tenantId": "<tenantId>"
    },
    "parent": "urn:pulumi:<stackName>::<projectName>::pulumi:pulumi:Stack::<projectName>-<stackName>",
    "provider": "urn:pulumi:<stackName>::<projectName>::pulumi:providers:azure::default_3_40_0::f9986ce1-1ad4-4ce2-93b0-70791d710a22",
    "propertyDependencies": {
        "login": null,
        "objectId": null,
        "resourceGroupName": null,
        "serverName": null,
        "tenantId": null
    }
},

**Comment by leezen** [comment]
`pulumi refresh` will use the provider version specified in the state file (i.e. the version of the plugin last used). So yes, that would explain why you're now getting the errors. Unfortunately, I'm not sure of a 'clean' way to fix this except to modify the state files to reflect the correct ID.

**Comment by scp-mb** [comment]
Yeah, I've since removed the resources from the state and reimported them under the new path, but I guess the issue remains that you can even import it like that in the first place. I imagine there might be other people with a similar issue.

Unless that's now changed and is no longer possible?

**Comment by leezen** [comment]
Sorry for the slow reply here. I don't think this is possible any longer, so I'll go ahead and close this issue. Apologies for the inconvenience this has caused.
