### ISSUE TITLE
Blob containers cannot be found when specifying ImportId

### ISSUE THREAD

**Issue by scp-mb** [pulumi/pulumi-azure#801]
Seems there's a bug in importing blob containers, even with the correct resource Id importing will fail as it cannot find the resource.

Run `pulumi up` with the following resources under Pulumi v2.16.2 and Pulumi.Azure v3.41.0:

```
var resourceGroup = new Pulumi.Azure.Core.ResourceGroup("testresourcegroup",
            new Pulumi.Azure.Core.ResourceGroupArgs
            {
                Location = "UKSouth",
                Name = "testresourcegroup",
            });

        var account = new Pulumi.Azure.Storage.Account("teststorageaccount",
            new AccountArgs
            {
                ResourceGroupName = resourceGroup.GetResourceName(),
                Name = "teststorageaccount",
                Location = "UKSouth",
                AccountReplicationType = "LRS",
                AccountKind = "StorageV2",
                AccountTier = "Standard",
                AccessTier = "Hot",
            });

        new Pulumi.Azure.Storage.Container("testcontainer",
            new ContainerArgs
            {
                Name = "testcontainer",
                StorageAccountName = account.GetResourceName(),
                ContainerAccessType = "container"
            });
```

The blob container will be created successfully at this point with no issues. If you then get the resource Id from the the resources list for that stack when logged in on the pulumi.com and pass that as the `ImportId` under `CustomResourceOptions` it will fail to find the resource when attempting to run the stack again.

Obviously you wouldn't normally be attempting to import a resource created via pulumi, but it does the same thing with a non-imported resource.

`error: Preview failed: resource '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Storage/storageAccounts/<accountName>/blobServices/default/containers/<containerName>' does not exist`

**Comment by mikhailshilkov** [comment]
This looks like https://github.com/pulumi/pulumi-azure/issues/767 - does https://github.com/pulumi/pulumi-azure/issues/767#issuecomment-732288871 help?

**Comment by scp-mb** [comment]
I had missed that bit and assumed it would be the same syntax as seemingly every other resource, it does seem to find it using the URL instead of the usual Azure resource Id, however that does come across as inconsistent. 

The Pulumi web UI shows the normal Azure resource Id on a created container (not the URL), the Azure portal also sends queries based on the full resource Id and the AzureNextGen provider also allows you to import it using the same full resource id (which is how I've worked around it for now). If the nextgen provider more closely follows the ARM template definitions I'm surprised it doesn't work with this provider.

See: https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts/blobservices/containers

**Comment by mikhailshilkov** [comment]
There are two APIs to manage containers: an older data-plane API and a newer control-plane one. The Azure provider is based on the Terraform provider which uses the former. Azure NextGen uses the latter. IDs depend on the API, unfortunately.

I understand it's confusing but I don't think we can change it.

**Comment by scp-mb** [comment]
Fair enough, if it's an upstream issue hopefully it'll get updated there eventually.

However, perhaps it would be a good idea to improve the error messaging assuming that's also not coming from the upstream provider? Instead of just saying it can't find the resource perhaps some validation to feedback that the format is incorrect? I know it does that in some places already if you're missing part of the Azure resource id it'll complain about it so perhaps that could be expanded to this case as well? It's easy to miss this as one of the few (if any others exist) resources that have a vastly different import syntax.

For example, omitting `serverFarms` when importing an app service plan will throw an error stating `Error parsing Resource ID <resourceId>: ID was missing the serverfarms element`

**Comment by mikhailshilkov** [comment]
The ID validation happens upstream too, and that's where the last error message comes from

**Comment by scp-mb** [comment]
Welp. I guess there really isn't much that can be done then. Feel free to close unless there's any other ideas you may have.
