### ISSUE TITLE
Cannot create free tier search service 

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-azure#818]
Using the following code:

```csharp
using Pulumi;
using Azure = Pulumi.Azure;

class MyStack : Stack
{
    public MyStack()
    {
        var resourceGroup = new Azure.Core.ResourceGroup("pk-search-rg", new Azure.Core.ResourceGroupArgs
        {
            Name = "pk-search-rg",
            Location = "uksouth"
        });

        var searchService = new Azure.Search.Service("pk-search-service", new Azure.Search.ServiceArgs
        {
            Name = "pk-search-service",
            ResourceGroupName = resourceGroup.Name,
            Sku = "free", // NOTE - 'basic' works, 'free' does not
        });
    }
}
```

I can't create a new search service on the free tier. If I change the SKU from `free` to `basic` it works. If I go into the portal and create a free tier service it works. It also works using the nextgen provider

**Comment by mikhailshilkov** [comment]
Which error are you getting? Isn't it the same as https://github.com/terraform-providers/terraform-provider-azurerm/issues/10151 ?

**Comment by mikhailshilkov** [comment]
Tried the repro today and it works. The upstream issue is closed too.
