### ISSUE TITLE
Public IP Zone property should be a collection

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/pulumi-azure#826]
The "Zones" property of Pulumi.Azure.Network.PublicIp resource expects an Input<string> however both the Terraform and the ARM API expect a collection of strings.  Trying to define the zones as a string such as:

 Zones = "1,2,3",

Get's the following error:
`
Code="InvalidAvailabilityZone" Message="The zone(s) '1,2,3' for resource 'Microsoft.Network/publicIPAddresses/PUBIP-core01' is not supported. The supported zones for location 'westeurope' are '1,2,3'"`

**Comment by mikhailshilkov** [comment]
Fixed in https://github.com/pulumi/pulumi-azure/pull/1059
