### ISSUE TITLE
How the Enabled properties of app service is working

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure#827]
I created Azure.AppService with Enabled set to false.
Now I have a banch of app services that are disabled and needs to be quickly enabled.
Unfortunately I don't have access to pulumi code that set it any more.
I cannot find how to enable it via powershell or az CLI. How this is solved under the cover with Pulumi.Azure, which API Azure provider uses in this case (or how does it terraform)?

**Comment by mikhailshilkov** [comment]
It's all Terraform behind the scenes, which is open source. Feel free to check it here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/web/app_service_resource.go

**Comment by PawelStadnicki** [comment]
Thanks, it helped!

it turned out to be easy:

```
$Resource = (Get-AzResource  -Name MyAppServiceName -ResourceGroupName MyResourceGroup -ExpandProperties)
$Resource.Properties.Enabled = "True"
Write-Output $Resource
$Resource | Set-AzResource -Force
```
