### ISSUE TITLE
RoleDefinition deploy fails due to delayed creation

### ISSUE THREAD

**Issue by TheAsteroid** [pulumi/pulumi-azure#840]
When attempting to create a `Pulumi.Azure.Authorization.RoleDefinition` with `Pulumi.Azure v3.47.0`, the resource gets created, but Pulumi throwns an error that it cannot find it:

>   azure:authorization:RoleDefinition (test-peering-role):
>     error: authorization.RoleDefinitionsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="RoleDefinitionDoesNotExist" Message="The specified role definition with ID 'd840520b-e698-cf0d-4940-5825bce188ca' does not exist."

Running pulumi a second time results in an error that the resource already exists:

>   azure:authorization:RoleDefinition (test-peering-role):
>     error: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleDefinitionWithSameNameExists" Message="A role definition cannot be updated with a name that already exists."

It appears there's a multi-second delay in creating the RoleDefinition which Pulumi doesn't wait for, causing the failure the first time. I've been able to reproduce this delay by running `az role definition list --name d840520b-e698-cf0d-4940-5825bce188ca`, which returns an empty array the first couple of attempts after running pulumi up. I'm not sure this is an issue that should be solved on Azure's side or in pulumi-azure.

Example code (simplified to omit business details):
```
var subscriptionId = "...";
var scope = "...";

var roleDefinition = new RoleDefinition($"test-peering-role", new RoleDefinitionArgs
{
    Name = "test-peering-role",
    Description = "Test description",
    AssignableScopes = scope,
    Permissions = new RoleDefinitionPermissionArgs
    {
        Actions = new[]
        {
            "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/read",
        }
    },
    Scope = $"/subscriptions/{subscriptionId}"
});
```
![2021-02-18 12_37_18-posh~git ~ slimmingworld azure infrastructure  feature_rename-platform-to-comput](https://user-images.githubusercontent.com/41196601/108353230-31653600-71e8-11eb-9a4a-6e025b739a34.png)

**Comment by mikhailshilkov** [comment]
This sounds like an upstream issue tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/10602 (and described in https://github.com/terraform-providers/terraform-provider-azurerm/issues/10442)

**Comment by TheAsteroid** [comment]
Ah, great that they're working on it. Do you mind if I keep this open for visibility for other devs running into this issue?
