### ISSUE TITLE
importing a azure VM gives an error 

### ISSUE THREAD

**Issue by lily1098** [pulumi/pulumi-azure#844]
wile trying to import an existing machine in azure to pulumi state, I get the below error:

error: azure:compute/linuxVirtualMachine:LinuxVirtualMachine resource 'example' has a problem: Cannot parse Azure ID: parse "": empty url
    error: Preview failed: one or more inputs failed to validate

## Expected behavior
it should import the Vm and shows the code to add.

## Current behavior
I get an aerror
error: azure:compute/windowsVirtualMachine:WindowsVirtualMachine resource 'example1' has a problem: Cannot parse Azure ID: parse "": empty url

## Steps to reproduce

1. VM is already created in azure
2. Execute : pulumi import azure:compute/linuxVirtualMachine:LinuxVirtualMachine VMname /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Compute/virtualMachines/machine1

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
