### ISSUE TITLE
Cannot have different key vaults with different secrets with the same name?

### ISSUE THREAD

**Issue by fabiomilheiro** [pulumi/pulumi-azure#846]
I successfully created a bunch of key vaults for different services.
However, each service needs to have secrets that have the same name but different values per service/key vault e.g.:

| Key vault | Secret name | Secret value |
| --------------- | --------------- | --------------- |
| kv-1 | RedisConnectionString | redis1.redis.cache.windows.net:6380,ssl=True,... |
| kv-2 | RedisConnectionString | redis2.redis.cache.windows.net:6380,ssl=True,... |

However, I'm having a little problem with this.

```csharp
new Secret(
  settings.Key,
  new SecretArgs
  {
    KeyVaultId = keyVault.Id,
    Name = settings.Key,
    Value = settings.Value.Apply(Output.CreateSecret)
  });
```

```
azure:keyvault:Secret (RedisConnectionString):
    error: Duplicate resource URN 'urn:pulumi:serviceTests::Tests::azure:keyvault/secret:Secret::RedisConnectionString'; try giving it a unique name
```

Is there a solution to achieve this?

**Comment by fabiomilheiro** [comment]
The only idea that seems to work is to prefix each secret name with the service name e.g. `service1-RedisConnectionString` but would require the services to use that key as well. May work but still wonder if we can do it better?

**Comment by mikhailshilkov** [comment]
You should prefix the logical names (the first parameter) but not the actual resource names:

```cs
new Secret(
  "prefix1" + settings.Key,
  new SecretArgs
  {
    KeyVaultId = keyVault.Id,
    Name = settings.Key, // this will be the secret name in Azure
    Value = settings.Value.Apply(Output.CreateSecret)
  });
```

**Comment by fabiomilheiro** [comment]
It worked perfectly and it makes sense. Thanks 👍
