### ISSUE TITLE
Pulumi CosmosDB Account is returning error with EnableServerless condition

### ISSUE THREAD

**Issue by kimic79** [pulumi/pulumi-azure#855]
I am trying to deploy CosmosDB Account with  EnableServerless option, as Pipeline task within Azure Devops  Pulumi@1
In the debug there is  version 1.0.8, downloads latest PulumiSDK 2.21.2  
I have added to the Pulumi project additional property  `Capabilities = { new AccountCapabilityArgs { Name = "EnableServerless" } },` 

however  the deployment fails on error:
**expected capabilities.0.name to be one of [EnableAggregationPipeline EnableCassandra EnableGremlin EnableTable EnableMongo MongoDBv3.4 mongoEnableDocLevelTTL], got EnableServerless** 

I have found it could be related to old Terraform provider version.

## Expected behavior
Accept EnableServerless condition option

## Current behavior
EnableServerless condition  is unknown by Terraform provider

## Steps to reproduce
```
 return new Account(
                name: "name",
                args: new AccountArgs
                {
                    Name = "name",
                    ResourceGroupName = "rgname",
                    Location = "West Europe",
                    OfferType = "Standard",
                    Kind = "GlobalDocumentDB",
                    ConsistencyPolicy = new AccountConsistencyPolicyArgs
                    {
                        ConsistencyLevel = "Session"
                    },
                    Capabilities = { new AccountCapabilityArgs { Name = "EnableServerless" } },
                    GeoLocations =
                    {
                        new AccountGeoLocationArgs
                        {
                            Location = "West Europe",

                            // Failover priority 0 indicates write region.
                            FailoverPriority = 0
                        }
                    }
                }
            );


```
## Context (Environment)
Deploy CosmosDB Account using Pulumi with Azure devops pipeline.

**Comment by kimic79** [comment]
I suppose the provider was enabled by the installed Pulumi task in the Azure DevOps pipelines. I did not notice any option to upgrade version of the provider under that task. I did not have access to admin options, I suppose the provider came with the pipeline task. However if the Terraform provider is installed/configured separately to Pulumi task then probably ignore this issue.

**Comment by leezen** [comment]
Thank you for clarifying the above. The task shouldn't be bringing in its own version of the `pulumi-azure` dependency. Within your pulumi project, you should be able to control the versioning yourself. Do you mind checking how that's setup? The way you wrote the original description of the issue also seems to suggest you're basing this from some example or sample? In which case, do you mind pointing me to what example?

**Comment by mikhailshilkov** [comment]
This issue is more than 2 years old with no recent interactions. I'm fairly sure it's been fixed in more recent versions of the provider, so I'll go ahead and close it.
