### ISSUE TITLE
Looks like v3.51 broke LinuxVirtualMachine

### ISSUE THREAD

**Issue by khellang** [pulumi/pulumi-azure#860]
The upgrade to v2.51.0 of the AzureRM Terraform Provider (#854) added a new property `PlatformFaultDomain`:

https://github.com/pulumi/pulumi-azure/blob/b2481d61664a2227e512e8bb6d2d8a5a0e1bfa4f/sdk/dotnet/Compute/LinuxVirtualMachine.cs#L545-L549

This update seems to have borked Pulumi.Azure with the following error:

> error: azure:compute/linuxVirtualMachine:LinuxVirtualMachine resource 'srm-dev-docker-vm' has a problem: "platform_fault_domain": all of `platform_fault_domain,virtual_machine_scale_set_id` must be specified

Both of those properties should be optional for `LinuxVirtualMachine`. We've tried setting `PlatformFaultDomain` to its default value (`-1`), but it still fails. We don't want to have to add a scale set just to please Pulumi 😝

I noticed in [the azurerm PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10803) that the `platform_fault_domain` is `RequiredWith: []string{"virtual_machine_scale_set_id"}`, but we haven't specified any of them in the stack.

// @stack72

**Comment by ArcturusZhang** [comment]
Hey @khellang actually the default value of `-1` in the terraform provider is a workaround because in the API the default value of this property `platformFaultDomain` is `null` which means that Azure will assign a `platformFaultDomain` automatically for you. But terraform schema does not support `null` and `0` is a legal input for this property, we have to use `-1` as its default value to emphasize this.

**Comment by khellang** [comment]
@ArcturusZhang Right, that's fine, but for some reason, the introduction of this property (at either terraform or Pulumi level) fails validation of `linuxVirtualMachine` when none of the (optional) properties have been set, or when only `platformFaultDomain` has been set to `-1`. 

Judging by the error message, it seems this validation fails at the terraform level, which leads me to believe that the Pulumi terraform bridge passes some invalid data down 🤷🏻‍♂️

**Comment by mreadings** [comment]
Getting the same thing on Azure.Compute.WindowsVirtualMachine
using Pulumi.Azure 3.53.0

I see giving a 
PlatformFaultDomain = 1

still gives the same problem
    
error: azure:compute/windowsVirtualMachine:WindowsVirtualMachine resource 'jumpVM-zga' has a problem: "platform_fault_domain": all of `platform_fault_domain,virtual_machine_scale_set_id` must be specified

**Comment by khellang** [comment]
Yeah, anyone using `WindowsVirtualMachine` or `LinuxVirtualMachine` with Pulumi.Azure v3.51.0 and above is broken by this. The only solution (that we've found) is to downgrade to v3.50.0 😞

**Comment by mreadings** [comment]
thanks for the quick answer at least I can get back to work... might want to drop the stable version in the nuget repo, that problem will probably scare a lot of newbies

dotnet add package Pulumi.Azure -v 3.50.0

**Comment by agileramblings** [comment]
Chiming in on this. We are encountering this problem as well. 
```
    "dependencies": {
        "@pulumi/azure": "3.50.0", // <-- sadness
        "@pulumi/pulumi": "^2.17.0"
    }
```
.. is unfortunately our fix.

**Comment by yellowhat** [comment]
I have just tried with:
- pulumi: 3.0.0
- pulumi_azure: 4.0.0
still:
```bash
 error: azure:compute/linuxVirtualMachine:LinuxVirtualMachine resource 'jumpVM' has a problem: "platform_fault_domain": all of `platform_fault_domain,virtual_machine_scale_set_id` must be specified
```

**Comment by khellang** [comment]
It's kinda worrying that nothing's done about this. Seems like a blocker that no one are able to use virtual machines on Azure above v3.50.

Is this considered legacy? Are everyone focused on the new native Azure provider? I wish I could send a PR to fix this, but honestly I don't even know where to start 😅

**Comment by stack72** [comment]
@khellang et al - I am super sorry I've not been able to get to this - I promise I will start looking tomorrow (now that the major work I was finishing is taken care of!)

This is definitely NOT a legacy provider

**Comment by yellowhat** [comment]
Sorry for bring this up again, but this bug is an hard blocker for using pulumi 3 and any other latest pulumi provider.

**Comment by stack72** [comment]
Hi folks

I just brought this issue to "in progress" state! I am looking through to try and get a fix in place

P.

**Comment by stack72** [comment]
Ok folks, I just opened a pull request that fixes this bug - as soon as it's green, I will get a patch of the provider cut!
