### ISSUE TITLE
AKS Provider missing ingress_application_gateway

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/pulumi-azure#884]
It looks like the legacy Azure provider is missing the "ingress_application_gateway" property that is availible on the Terraform provider, and so it is not possible to use an App Gateway Ingress controller. Is it possible to get the provider updated to add this. I know it is present in the Azure Native provider but I am not able to update to this yet.

## Expected behavior
ingress_application_gateway is present and can be configured

## Current behavior
ingress_application_gateway is not present

**Comment by justinvp** [comment]
@stack72, any idea why we're not including this?

**Comment by stack72** [comment]
Hey @sam-cogan 

This was published just this afternoon (hours after your issue) as part of pulumi-azure v4.1.0

Paul
