### ISSUE TITLE
After importing a resource, a diff is created on __defaults property on next preview

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi-azure#890]
After importing a resource (e.g. ResourceGroup) utilizing the `pulumi.ResourceOptions.import_` and `pulumi.ResourceOptions.id` properties, the next `preview` command detects a diff on the (internal??) property `__defaults` and Pulumi wants to replace the existing (imported) resource.

## Expected behavior

After successfully imported a resource, the next `preview` command shall display no differences.

## Current behavior

A diff is detected  on the `__defaults` property:

![image](https://user-images.githubusercontent.com/14177833/118314971-2c690780-b4f5-11eb-9d55-c0318e36fa9e.png)

## Steps to reproduce

1. Create a resource group in Azure e.g. with `az group create -l westus -n MyResourceGroup`
2. Import the resource group using the following code and `pulumi up`. 

Data of the existing resource group is retrieved by the following endpoint `'https://management.azure.com/subscriptions/{wl_subscription}/resourcegroups/{rg_managed_resources}?api-version=2020-10-01`

![image](https://user-images.githubusercontent.com/14177833/118315297-9f727e00-b4f5-11eb-8d4b-111d74853fb5.png)

![image](https://user-images.githubusercontent.com/14177833/118315050-499dd600-b4f5-11eb-81db-cc72a41645e1.png)

3. Perform a `pulumi preview`
4. Difference is reported and Pulumi wants to recreate the imported (existing) Resource Group

![image](https://user-images.githubusercontent.com/14177833/118315558-f5472600-b4f5-11eb-881e-0cd1c800cacd.png)

## Context (Environment)

Using the Automation API to automatically import existing cloud resources.

The complete source code, that has been created to verify this issue, can be provided on request.

**Comment by tmeckel** [comment]
@lblackstone did anyone at Pulumi looked at this issue already?

**Comment by tmeckel** [comment]
Seems to be a pretty old issue which still lingers around.
https://github.com/pulumi/pulumi/issues/2579

**Comment by tmeckel** [comment]
As proposed by @stack72 I setup a small Pulumi program to test the import of a Azure Resource Group:

![image](https://user-images.githubusercontent.com/14177833/119142239-88c4ad80-ba46-11eb-9973-b9aa565ae625.png)

**Performing the import:**

![image](https://user-images.githubusercontent.com/14177833/119142274-92e6ac00-ba46-11eb-8a70-48dafbc5263b.png)

**Status:** successful

![image](https://user-images.githubusercontent.com/14177833/119142304-a134c800-ba46-11eb-8661-a807222da6b6.png)

After a refresh, Pulumi still shows a diff on the `__defaults` attribute:

![image](https://user-images.githubusercontent.com/14177833/119142394-bd386980-ba46-11eb-9eb2-8a4e9ade7c3d.png)

For reference puposes I attached my two test programs here:

1. `pulumi-import-test-classic`: A "classic" Pulumi program
2. `pulumi-import-test`: A Python program which utilizes the Automation API and performs "automatic" import of Azure resources by getting the required information (property data) via the ARM API (HTTP REST calls)

[pulumi-import-test.tar.gz](https://github.com/pulumi/pulumi-azure/files/6522683/pulumi-import-test.tar.gz)
[pulumi-import-test-classic.tar.gz](https://github.com/pulumi/pulumi-azure/files/6522684/pulumi-import-test-classic.tar.gz)

**Comment by lukehoban** [comment]
Sorry for the trouble here @tmeckel. I actually thought this had been fixed recently - so am surprised it is still surfacing in the repo. We'll need to look back into this. 

FWIW - I believe this is different than the issue in #2579, which is about the non-interactive display mode. Though it's possible something has changed since that issue was filed.

**Comment by tmeckel** [comment]
@lukehoban @stack72 The issue with `__defaults` shows up as well with "normal" Azure resource deployment using TypeScript/Javascript. Luckily the diff on `__defaults`  does not lead to a resource replacement in this case. 

![image](https://user-images.githubusercontent.com/14177833/122366644-07384080-cf5c-11eb-861d-c3c15f70f83e.png)

**Comment by tmeckel** [comment]
@lukehoban @stack72 is there any update on this issue here?

**Comment by peterhriser** [comment]
@tmeckel was this resolved? Im encountering something similar (with the aws provider).

**Comment by tmeckel** [comment]
@peterhriser You didn't share any code but I suspect you might have fallen into the same trap as I did when I used the import functionality of Pulumi the first time. Rule: Never ever assign the  `id` property of  the `ResourceOptions` class. Only assign the id of the resource you wanna import to the `import_` property. When I changed my code that way, the above issue vanished. Pulumi still prints differences on `__defaults` but there will be no changes.

**Comment by semoog** [comment]
>Pulumi still prints differences on __defaults but there will be no changes.

This can't be the desired behavior of the tooling. When importing and running `up` or preview on freshly imported resources, I do not want to wade through all of the attached `__defaults` that it says are changing, when nothing has changed and I am about to apply it across my entire infrastructure. What's the deal?

I am using the `pulumi import` command as described, and copying the outputted code directly to my stack.

![Screenshot_2022-03-31_08-55-53](https://user-images.githubusercontent.com/1973922/161140127-a8d693d6-01e1-4d74-9a9a-f8fac843844f.png)
![Screenshot_2022-03-31_14-05-19](https://user-images.githubusercontent.com/1973922/161140228-0cb46166-75d1-479f-87e8-8abf1df98f6e.png)
