### ISSUE TITLE
provider config warning: "metadata_url": [DEPRECATED] use `metadata_host` instead

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure#891]
I'm getting the warning mentioned in the issue title since I remember.
I cannot find anything that is responsible for it and want to finally get rid off it.
Any clues?

**Comment by stack72** [comment]
Hi @PawelStadnicki 

Is this on *any* request with the azure provider? Or are you configuring a provider block and getting this request?

Paul

**Comment by stack72** [comment]
Checking in here @PawelStadnicki

**Comment by PawelStadnicki** [comment]
Please give me a time until end of this week for confirmation, I switched the task/context
