### ISSUE TITLE
Improve namespace structure 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-azure#97]
The namespacing being used is somewhat too “opinionated”, and doesn’t match the common namespace structure of Azure services as seen in SDKs. We should pick a stable reference point and cleanly align namespacing to ensure APIs are available with meaningful and correct fully qualified names.

**Comment by jen20** [comment]
This would likely result in breaking changes relying on pulumi/pulumi#2389 being implemented, so I'm moving it to M22.

**Comment by stack72** [comment]
There needs to be some discussion about what we are going to move and what we are not going to move. Therefore, this will not be completed in 0.25 milestone - it will move to the 0.26 milestone
