### ISSUE TITLE
Provisioning Azure Key Vault says that argument is deprecreated but missing property name

### ISSUE THREAD

**Issue by robertlyson** [pulumi/pulumi-azure#998]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

Hi :wave:

When I provision an instance of [Azure Key Vault](https://azure.microsoft.com/pl-pl/services/key-vault/)
```
var keyVaultName = "some_name";                           
var keyVault = new KeyVault(keyVaultName, new KeyVaultArgs           
{                                                                    
    Name = keyVaultName,                                             
    ResourceGroupName = resourceGroupShared.Name,                    
    Location = resourceGroupShared.Location,                         
    SkuName = "standard",                                            
    TenantId = currentConfig.Apply(c => c.TenantId),                 
    SoftDeleteEnabled = true,                                        
    AccessPolicies =                                                 
    {                                                                
        new KeyVaultAccessPolicyArgs                                 
        {                                                            
            TenantId = currentConfig.Apply(c => c.TenantId),         
            ObjectId = currentConfig.Apply(c => c.ObjectId),         
            KeyPermissions = { "Get", },                             
            SecretPermissions = { "Get", "List", "Set", "Purge", "Rec
            CertificatePermissions = { "Get", "Import", "List" },    
            StoragePermissions = { "Get", },                         
        },                                                           
    },                                                               
    NetworkAcls = new KeyVaultNetworkAclsArgs                        
    {                                                                
        Bypass = "AzureServices",                                    
        DefaultAction = "Deny",                                      
    }                                                                
});                                                                  
```

and run `pulumi up` I get 
```
  azure:keyvault:KeyVault (some_name):
    warning: .. verification warning: Argument is deprecated
```

Expected: would be great to see which argument is deprecated
Actual: currently it just says "Argument is deprecated"

Don't know if that is Pulumi thing or maybe Azure, but wanted to let you know, thanks.

**Comment by emiliza** [comment]
Lurking [upstream](https://github.com/hashicorp/terraform-provider-azurerm/pull/10088) it looks like the problematic field is `SoftDeleteEnabled` which is now defaulting to true. Can you try omitting that and see if the error goes away?

**Comment by robertlyson** [comment]
@emiliza thank you, warning is now gone, many thanks for your help :) 
Do you have advice for me on how to debug such issues? Asking because have similar issue with Azure Front Door instance but can't figure out
![image](https://user-images.githubusercontent.com/2392583/145711278-5b0b3667-ede6-4613-b298-1dfbbdc6d336.png)

**Comment by emiliza** [comment]
For Frontdoor I suspect it's erroring on `location` which is deprecated and defaults to `global`

For debugging which fields could be deprecated - we also log this in our docs, so searching there would be my recommendation, eg:  https://www.pulumi.com/registry/packages/azure/api-docs/frontdoor/frontdoor/#properties

**Comment by robertlyson** [comment]
@emiliza thanks for your help!
